### ISSUE TITLE
Configuration fails when Henhouse or egs-home path is longer than 80 chars

### ISSUE THREAD

**Issue by KaiHabermann** [nrc-cnrc/EGSnrc#1039]
The title says it all. The configuration fails in a verry unclear way, when your path is too long.
Further attempts to use the ill defined and ill compiled software result in faulty fortran files created by mortran.

There is a warning about an 80 char limit somewhere in the logs of the install, but it does not really point to the correct source of the issue.

The issue was found on OpenSuse Linux, but could be reproduced on Ubuntu20.04 aswell.

Im not sure, if this is really an issue of EGSnrc or rather a Mortran issue, but I think catching it in the installer should be doable.

The reason for the issue was found in this reddit post:
https://www.reddit.com/r/EGSnrc/comments/btgay1/dosxyznrc_compile_failed/

**Comment by crcrewso** [comment]
@ftessier I know we fixed this for egsinp files. Did this not get fixed for the install itself?

**Comment by ftessier** [comment]
@KaiHabermann this is a long standing issue in EGSnrc, which we have not addressed yet. In the mean time, you can shorten your install path by using `$HOME`, `~`, or a symbolic link (alias) to the actual folder location on disk.
