### ISSUE TITLE
BEAMnrc Phase Space File Termination on Windows 7 machine

### ISSUE THREAD

**Issue by syedbasim** [nrc-cnrc/EGSnrc#104]
After successful installation of the EGSnrc 2016 on a 32 bit Windows 7 machine, I am having issues with the BEAMnrc simulation as follows:

Simulating a linac head with limited number of histories say less than a million (where the phase space file is around 2 GB) has no issues. Once the phase space size exceeds this value the simulation fails. I am attaching a snapshot including the one from the Error File as well. The errors that are listed in the error file also appear when the simulation is successfully run for limited number of histories (i.e. 10 batches are run successfully). The file system is NTFS so i presume that it has no file storage limitation issues in the phase file size with which we are working here.

The BEAMnrc input files that I have been using have been previously tested on a High Performance

 Computing Machine in Brisbane

Regards,
Basim
 
![latest issue](https://cloud.githubusercontent.com/assets/19832589/15921354/499a69f8-2e3a-11e6-909a-65632cf4f86b.jpg)

**Comment by rtownson** [comment]
You're hitting the 2GB physical memory limit for a process on 32-bit systems, so this is not an issue with EGSnrc. There may be other solutions, but simplest is to split the job into smaller runs (with different random number seeds) and combine the results.

**Comment by crcrewso** [comment]
I've been thinking about this for a while. Is the simulation storing all histories until the end of the simulation? I thought (though I have not read the save code) that it was more like a queue where each saved particle is removed from active memory. If this is the case then the 2 GB memory limit should not exist. Is there a memory leak in the save code I wonder.

**Comment by rtownson** [comment]
I bet it is related to the number of bytes assigned to ints and longs on a 32-bit system then :)
