### ISSUE TITLE
DOSXYZnrc compile error

### ISSUE THREAD

**Issue by CymV** [nrc-cnrc/EGSnrc#1049]
Hi, 

I am getting the following error message when attempting to compile in DOSXYZnrc on Windows 10:

![Compileerror](https://github.com/nrc-cnrc/EGSnrc/assets/49775488/54b8040f-b288-497c-81a6-259774a318f5)

I believe I have installed the latest/recommended version of egsnrc as per the instructions and was able to set up my simulation with parameters via the GUI with no problem  Any ideas on what could be causing this issue?

**Comment by ftessier** [comment]
Indeed, this is an issue with EGSnrc 2023, that was addressed in [Release 2023a](https://github.com/nrc-cnrc/EGSnrc/releases/tag/v2023a) last week. Can you confirm which version your are using, and how you obtained it (clone, download zip, etc.)?

**Comment by CymV** [comment]
> Indeed, this is an issue with EGSnrc 2023, that was addressed in [Release 2023a](https://github.com/nrc-cnrc/EGSnrc/releases/tag/v2023a) last week. Can you confirm which version your are using, and how you obtained it (clone, download zip, etc.)?

Thanks, I downloaded the 2023 EGSnrc-master zip file back in May '23, so I've installed the 2023a release as a new install as per instructions (I just renamed the old egsnrc directory.  Installation was fine and compilation was also successful, however I'm not able to run a batch:
![runerror](https://github.com/nrc-cnrc/EGSnrc/assets/49775488/392a6494-7d93-477f-97e8-2d10cceb4a29)

It seems to indicate that the run_user_code_batch file doesn't exist when it clearly does.  Thoughts?  Thanks for all your help :)

**Comment by rtownson** [comment]
> It seems to indicate that the run_user_code_batch file doesn't exist when it clearly does. Thoughts? Thanks for all your help :)

The scripts for parallel runs do not work on Windows, so it's not finding that file because it's not a valid Windows executable. You can use this one, running from the command line instead:

https://gist.github.com/ftessier/ce46e990139f70b54352

**Comment by ftessier** [comment]
@rtownson does `egs-parallel` work on Windows (in `git bash`)? I presume it does.

**Comment by rtownson** [comment]
@ftessier Yes, it does work, good point! So @CymV just install git for windows, and use the `git bash` command prompt that it installs to run `egs-parallel`. You will need to `cd` into `HEN_HOUSE/scripts/bin`. E.g. for 4 parallel jobs running locally:

```
egs-parallel --batch cpu -q short -n4 -v -c 'egs_app -i slab'
```

**Comment by CymV** [comment]
Thanks all, just to be clear it seems I can't "run" any simulations regardless of it being a 'batch' with 'run in parallel' checked or unchecked, or even an 'interactive' run.  

Am I still required to install egs-parallel to enable any kind of simulation run on windows or is there something fundamentally wrong here?  Note: I get the same error message above for a batch run with 'run in parallel' checked or unchecked; an interactive run just gives the error 'The job has failed'.  Cheers.

**Comment by rtownson** [comment]
The job should run in interactive mode, and it's a good idea to always test this for a small number of histories before trying to run in parallel. You don't need to use egs-parallel at all, it's just for when you want to use more cores on your computer. 

For the crashing runs - what do you get in terms of simulation output? Check the .egslog file. Does it create one? Do any other simulations run or do they all crash? If even `egs_app -i slab` (on the command line) crashes, then also share your installation log, found in `HEN_HOUSE/log`.

**Comment by CymV** [comment]
> The job should run in interactive mode, and it's a good idea to always test this for a small number of histories before trying to run in parallel. You don't need to use egs-parallel at all, it's just for when you want to use more cores on your computer.
> 
> For the crashing runs - what do you get in terms of simulation output? Check the .egslog file. Does it create one? Do any other simulations run or do they all crash? If even `egs_app -i slab` (on the command line) crashes, then also share your installation log, found in `HEN_HOUSE/log`.

it looks like the simulations are now able to run with a simple filename change to remove spaces for the input file.  Thanks for everyone's help here, it's invaluable!
