### ISSUE TITLE
DOSXYZnrc monoenergetic Vs spectrum

### ISSUE THREAD

**Issue by CymV** [nrc-cnrc/EGSnrc#1051]
Hi, 

I'm having a peculiar issue where I'm recording the transmitted dose through a barrier and getting a significantly _**greater**_ dose using a spectrum file as a source than when I select a monoenergetic beam of the same kVp as the spectrum.  In other words, the lower mean energy source is much more penetrating than the higher energy monoenergetic beam, which doesn't make sense. 

All other sim factors remain the same; I'm simply changing the nature of the source (0) and using a 521ICRU.pegs4dat file for all materials.  There doesn't appear to be any errors when running the sims, only that a few of the kV bins in the spectrum file "have such small probabilities that they may be missed" - if they were, I suspect that would only make this issue more of a problem. 

Any thoughts?

**Comment by rtownson** [comment]
What happens if you use a spectrum file but have all the bins zero except for the energy at the peak (same as your monoenergetic)? Note that all energies should be in MeV, and pay attention to the definitions of the upper vs. lower edges of the energy bins.

**Comment by CymV** [comment]
> What happens if you use a spectrum file but have all the bins zero except for the energy at the peak (same as your monoenergetic)? Note that all energies should be in MeV, and pay attention to the definitions of the upper vs. lower edges of the energy bins.

Nice suggestion, when I zeroed all kV bins in the spectrum except the peak kV the sim gave similar/expected results as with the monoenergetic selection. I've attached a txt copy of the normalized spectrum file I want to use that has the issues, can you see anything wrong with it?  

My only other thought would be scatter of lower energies somehow going "around" the barrier, which would be outside the defined phantom, and somehow depositing dose back in the downstream phantom measurement voxel.  Not sure if this is possible.  Note that my photon source is the same size (x,y dimensions) as the downstream barrier and the subsequent measurement voxel.  I experimented here with reducing the size of the source and found 'better' results, or at least trending in the right direction.  I've also set 0 MeV for global electron/photon cutoffs. Thanks again. 

[egspectrum.txt](https://github.com/nrc-cnrc/EGSnrc/files/12364126/egspectrum.txt)

**Comment by rtownson** [comment]
There are some mistakes in the energy bins, e.g.:
```
     0.0170E+00,     3.2180E-05
     0.0180E+01,     6.4486E-05
     0.0190E+00,     3.9424E-04
```

**Comment by CymV** [comment]
> There are some mistakes in the energy bins, e.g.:
> 
> ```
>      0.0170E+00,     3.2180E-05
>      0.0180E+01,     6.4486E-05
>      0.0190E+00,     3.9424E-04
> ```

Damn, can't believe I missed that.....all is right with the world :) thank you so much!
