### ISSUE TITLE
Geometry errors when pyramid or prism is inscribed in composite geometry

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#106]
Another CD geometry error issue from me, what a surprise!

Create a prism or a pyramid. Inscribe it in a CD geometry (for example, use a box as the base). Envelope the CD geometry in a box. Look at the geometry in egs_view and you'll notice _tons_ of geometry errors. See the input files for tutor7pp below.

I know where the code is getting confused: when a particle is sitting on one of the sides of the prism or pyramid (type EGS_Polygon) and leaving the CD geometry. The howfar of CD geometry somehow does not catch this. My problem is that I find the EGS_Polygon's howfar method hard to read through and understand what's going on, so if someone else wants to tackle this case, be my guest.

[prism_cdgeom_errors.txt](https://github.com/nrc-cnrc/EGSnrc/files/309500/prism_cdgeom_errors.txt)
[pyramid_cdgeom_errors.txt](https://github.com/nrc-cnrc/EGSnrc/files/309501/pyramid_cdgeom_errors.txt)

**Comment by mchamberland** [comment]
So it turns out that this issue is **not** limited to CD geometries. It affects any composite geometry with prisms or pyramids: CD, envelope, and union. See the simple geometry file below and the symptoms of geometry errors in egs_view. The geometry is simply the union of a prism and a box.

Anything I can do to help get this fixed? I know my way around a debugger, but as I wrote in the original report, I'm getting lost in the polygon's howfar routine.
[prism_union.txt](https://github.com/nrc-cnrc/EGSnrc/files/335676/prism_union.txt)
![prism_union](https://cloud.githubusercontent.com/assets/1675666/16392701/39a66e80-3c7b-11e6-9200-3c3ed7356b3d.png)

**Comment by gwu-reflexionmedical** [comment]
I had the same problem. What I did was using CD in the last step, and avoid CD after another CD in a different direction.

**Comment by rtownson** [comment]
Fixed in release-2017.
