### ISSUE TITLE
Errors in MC transport parameters

### ISSUE THREAD

**Issue by physicsmed** [nrc-cnrc/EGSnrc#1084]
i am trying to simulate a Linac using Full beam simulation in DOSXYZnrc, but i am wondering why these errors were created in the file of errors ? you found bellow the list of errors in the inputfile.errors file.
"
  If you are not trying to reset transport parameters,
  ignore all the output until the message
  ******************** end input transport parameter ***********************

 ***************ERROR***************
 >>Radiative Compton corrections<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Triplet production<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>scale L EII cross-sections<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Electric Field<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Magnetic Field<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>EM ESTEPE<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Photonuclear attenuation<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Photonuclear cross sections<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Set ECUT<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Set ECUT start region<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Set PCUT<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Set PCUT start region<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Set PCUT stop region<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Set SMAX<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Set SMAX start region<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER
 ***************ERROR***************
 >>Set SMAX stop region<< NOT FOUND
 END OF DELIMETER: MC TRANSPORT PARAMETER

  ******************** end input transport parameter ***********************
"

**Comment by rtownson** [comment]
You can safely ignore these errors, they are always printed. They're just letting you know that you didn't specify your own values for these transport parameters, which means the defaults are being used. I understand that it's misleading that they are called errors, it should really be a warning or not printed at all.
