### ISSUE TITLE
Statistics irregularity in dosrznrc

### ISSUE THREAD

**Issue by hbouchard** [nrc-cnrc/EGSnrc#1093]
**Describe the bug**

While teaching the students on the behaviour of statistical uncertainties as a function of the number of histories, I found an unexpected behaviour of the displayed statistics while using the template input file provided with the distribution. 

**To Reproduce**

1. Use the dosrnrz_template.egsinp input file provided by the distribution, located in the dosrznrc folder
2. Set the number of histories to about 4 million (2 million work as well, but in this example I used 4 M)
3. Run the simulation interactively with dosrznrc
4. Note the peak region statistics (%) as a function of batch number

**Expected behavior**

Statistics of the peak region stats (%) as a function of batch # should follow ~1/sqrt(N). At batch number 4 (after 1.6 M hist), it drastically fall apart from the 1/sqrt(N) behaviour. I see no variance reduction techniques defined in the input file that could explain that behaviour.

**Screenshots**

![Screenshot 2024-01-23 at 11 46 53 AM](https://github.com/nrc-cnrc/EGSnrc/assets/17842624/87f83978-e109-4379-bc17-9440d220e68f)

**Operating system**

- macOS

**EGSnrc version**

- v2023 (Jan 2023)

**Additional context**

None.

**Comment by rtownson** [comment]
Hi Hugo! dosrznrc actually does something unconventional here compared to the other applications. It's recording the *peak* dose, i.e. it searches through all of the dose regions after each batch and determines which one has the highest dose. Then it reports the uncertainty on that region. I expect that the region with the highest dose changes in that batch, hence the sudden jump in uncertainty. Then that region maintains its status as having the highest dose, explaining the return to a smooth curve.

I tried hard-coding it to use a single region (64) and the issue went away.

**Comment by hbouchard** [comment]
Hello Reid!

Wow this is reassuring. Thanks for your help.

Best, Hugo

---
Hugo Bouchard
Professeur agrégé, Département de physique
Université de Montréal, Campus MIL B-4435
1375 Ave.Thérèse-Lavoie-Roux, Montréal, QC H2V 0B3
514-343-6111 poste 34879
***@***.******@***.***>



From: Reid Townson ***@***.***>
Reply-To: nrc-cnrc/EGSnrc ***@***.***>
Date: Friday, February 2, 2024 at 12:32 PM
To: nrc-cnrc/EGSnrc ***@***.***>
Cc: Hugo Bouchard ***@***.***>, Author ***@***.***>
Subject: Re: [nrc-cnrc/EGSnrc] Statistics irregularity in dosrznrc (Issue #1093)


Hi Hugo! dosrznrc actually does something unconventional here compared to the other applications. It's recording the peak dose, i.e. it searches through all of the dose regions after each batch and determines which one has the highest dose. Then it reports the uncertainty on that region. I expect that the region with the highest dose changes in that batch, hence the sudden jump in uncertainty. Then that region maintains its status as having the highest dose, explaining the return to a smooth curve.

I tried hard-coding it to use a single region (64) and the issue went away.
