### ISSUE TITLE
Fortran runtime error: error during floating point read

### ISSUE THREAD

**Issue by anshusaluja2000** [nrc-cnrc/EGSnrc#1094]
I was trying to execute the code given in 'getting started with EGSnrc' manual and followed the steps as given, but after I run the command 
myapp -i slab.egsinp 
it doesn't complete the execution, stating the following error: 
Output from subroutine EDGSET:
==============================
 Atomic relaxations requested!

 Reading simplified photo-absorption data .....At line 19067 of file egsnrc_win3264.F (unit = 77, file = 'C:\mingw64\EGSnrc\HEN_HOUSE\data\photo_relax.data')
Fortran runtime error: Error during floating point read

no .ptracks file was generated, but I can view the slab without electron transport in egs_view.

**Comment by rtownson** [comment]
This is a pretty unusual error - I imagine something is wrong with the installation. Can you provide the installation log found in HEN_HOUSE/log?

Generally one would install in C:\EGSnrc, not within the mingw directory, but I'm not sure this is the cause of the problem.

**Comment by anshusaluja2000** [comment]
> This is a pretty unusual error - I imagine something is wrong with the installation. Can you provide the installation log found in HEN_HOUSE/log?
> 
> Generally one would install in C:\EGSnrc, not within the mingw directory, but I'm not sure this is the cause of the problem.

Thank you for replying. I was able to solve this issue after deleting and reinstalling both MinGW and EGSnrc, but encountered another error that said: "Cannot find [library] in [location]". I figured it was a path issue but I had already added the path to my system variables. In the end, I just copied the library and associated files to the folder it was looking it in and was able to execute the program.
