### ISSUE TITLE
egs_view reports "too big: inf" when translating a prism in the negative x-direction

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#111]
Try viewing the following file in egs_view, which is simply a base prism which is transformed by translating it in the negative x direction. egs_view complains about `too big: inf` and does not display anything. This seems to be caused by the negative translation along x. Remove the negative sign and it displays properly.

[translate_prism_egs_view.txt](https://github.com/nrc-cnrc/EGSnrc/files/337431/translate_prism_egs_view.txt)

**Comment by rtownson** [comment]
Appears to be a bug. Crashes when you have a closed prism trying to "straddle" the axis it is closed along. For example, closed = -1 1 crashes in this same way without any translation.

**Comment by rtownson** [comment]
Fixed in release-2017.
