### ISSUE TITLE
Rotation around y-axis is in the opposite direction as rotation around x and z

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#112]
I'm not sure if this is a bug or if this is by design: rotation around the y-axis is in the opposite direction as rotation around the x- or z-axis.

[Rotation around the x-axis is defined as clockwise around the axis.](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/egs_transformations.h#L283-L285)

[But rotation around y is the opposite.](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/egs_transformations.h#L292-L294)

To be consistent with x- and z-, it should be:

`        return EGS_RotationMatrix(cphi, (EGS_Float)0,         -sphi,
                                  (EGS_Float)0, (EGS_Float)1, (EGS_Float)0,
                                  sphi, (EGS_Float)0,         cphi);
`

**Comment by ftessier** [comment]
This is most likely a typo: forgot to change the sign of `sphi` for the rotation around the `y` axis. We'll fix this, thank you!

**Comment by ftessier** [comment]
Fix is pending in pull request #131.

**Comment by ftessier** [comment]
Fixed in 0cf6670.
