### ISSUE TITLE
Rotations incorrect for some shapes

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#113]
Rotations are not properly applied to some shapes. For example, the following should produce a line that is along `z`, but ends up producing a line at 45°.
      
```
:start shape:
   library = egs_line_shape
   points = 0 -1 0 1
   :start transformation:
      rotation = -1.5707963268, 0, 0
   :stop transformation:
:stop shape:

```
I know this affects at the very least the line and polygon shapes, but not the box or cylinder shapes. I have not tested any more shapes.

I'm using a custom egs++ application to list the initial position of particles, so unfortunately, I don't have an input file to share. Hopefully, it's trivial for you to verify the initial location of particles.

**Comment by ftessier** [comment]
@rtownson can you look into this issue?

**Comment by rtownson** [comment]
Could not reproduce! Can you provide example input @mchamberland?

I used ptracks to look at this. The line appears to be emitting particles correctly, from a line along `z`. My source:

```
    :start source:
        library = egs_parallel_beam
        name = my_source
        :start shape:
            library = egs_line_shape
            points = 0 -1 0 1
            :start transformation:
                rotation = -1.5707963268, 0, 0
            :stop transformation:
        :stop shape:
        direction = 1 0 0
        charge = 0
        :start spectrum:
            type = monoenergetic
            energy = 1.0
        :stop spectrum:
    :stop source:
```

**Comment by mchamberland** [comment]
Oh, using particle tracks is a good idea. I will make sure I can still reproduce this on my system and report back.

**Comment by mchamberland** [comment]
You can close this issue. The bug seems to involve how we record the initial location of particles in our custom application, and not how the particles are actually emitted (as shown by the particle tracks).

**Comment by rtownson** [comment]
Ok! :)
