### ISSUE TITLE
ENSDF file for Cu-67

### ISSUE THREAD

**Issue by thanhtaiphys** [nrc-cnrc/EGSnrc#1138]
Dear Developer:

I am reaching out to seek your expertise regarding a significant discrepancy I encountered while simulating radionuclide energy deposition using egs_mird, specifically for Cu-67.

**Simulation Details:**
Phantom: Water, 102x102x102 cm³
Radionuclides: Lu-177, Tb-161, Cu-67, Sc-47, I-131, Y-90
Simulation Tools: **egs_mird and TOPAS**
Comparison Metric: Total Energy Deposited vs. Q-value.

**Comparison Results:**
For most radionuclides (Lu-177, Tb-161, Sc-47, I-131, Y-90), the results from both TOPAS and egs_mird simulations are consistent with the theoretical Q-values. However, there is a significant discrepancy for Cu-67 when using egs_mird.

**Cu-67 Results:**
TOPAS Simulation: 264.49 keV
egs_mird Simulation: 176 keV
Theoretical Q-value: 271.10 keV
Discrepancy: 54.03% (egs_mird), 2.50% (TOPAS)

**Issue:**
In the EGSnrc_CLRP\HEN_HOUSE\spectra\lnhb\ensdf directory, there is no ENSDF file for Cu-67. Therefore, I downloaded the ENSDF file for Cu-67 from the IAEA Nuclear Data Services website: https://www-nds.iaea.org/relnsd/vcharthtml/VChartHTML.html#dcy2 and used it for the simulation. 
I suspect that the ENSDF file for Cu-67 might not be accurate or up-to-date, leading to this large discrepancy. Please see the attached file. 
[Cu-67.txt](https://github.com/nrc-cnrc/EGSnrc/files/15502283/Cu-67.txt)

Could you please assist in verifying the ENSDF data for Cu-67 or suggest any other potential causes for this discrepancy? Any guidance or suggestions to resolve this issue would be greatly appreciated.

Thank you for your time and support.

Best regards,
Tai

**Comment by rtownson** [comment]
Indeed, the ensdf file did not provide the beta decay maximum energies, which is used to calculate the beta energy spectra. I edited the file to add these in. Please do not assume that this is correct - use the `output beta spectra = yes` option to output those energy spectra and compare with literature.

[Cu-67.txt](https://github.com/user-attachments/files/15516369/Cu-67.txt)

**Comment by thanhtaiphys** [comment]
Hi @rtownson 
Thanks to your guidance and the modifications you suggested for the ENSDF file, I have successfully conducted 5 simulation runs, each with 10^8 histories. The simulation results now exhibit a remarkably low difference of just 0.15%, which is a significant improvement.
