### ISSUE TITLE
Segfault when destructing polygon shape

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#114]
The `EGS_PolygonShape` destructor tries to delete `n` triangles, but a polygon shape does not have `n` triangles, it has fewer than `n` triangles:

[Here is where `n` is set.](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/shapes/egs_polygon_shape/egs_polygon_shape.cpp#L68)

[Here is where the triangle array is allocated.](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/shapes/egs_polygon_shape/egs_polygon_shape.cpp#L90)

[Here the comment is wrong.](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/shapes/egs_polygon_shape/egs_polygon_shape.h#L139)

[Here is the destructor.](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/shapes/egs_polygon_shape/egs_polygon_shape.h#L125)

**Comment by ftessier** [comment]
Fixed in 9ef97f1.
