### ISSUE TITLE
EGS_View Crashing

### ISSUE THREAD

**Issue by AydinAgh** [nrc-cnrc/EGSnrc#1149]
To whom it may concern,

I recently downloaded EGSnrc and every aspect of the program is working thus far. However, EGS_View is not. I am on step 4 of the starters manual where we are entering "egs_view slab.egsinp slab.ptracks" into cmd. Anytime I attempt to do this, the view control page for EGS_View pops up, and within seconds closes itself. I have attempted to directly use the egs_view application, it allows me to select a file (I select the .egsinp file first) but it still has the same issue. I have also attempted to open other files in case these files were corrupt the same thing happens everytime. the view control opens only momentarily before closing. I am using Windows OS. Can someone assist with this endeavor? Below I attached a video

https://github.com/nrc-cnrc/EGSnrc/assets/171975191/0b880d60-2b53-4f22-8fcd-a8859f4648fe

**Comment by AydinAgh** [comment]
<img width="1280" alt="EGS additional info" src="https://github.com/nrc-cnrc/EGSnrc/assets/171975191/de10f394-9801-4218-9185-54850b8fc97d">
Some additional information that may be helpful

**Comment by rtownson** [comment]
Please post your .egsinp file. If the geometry is not valid, this will happen. Have you tried using the example .egsinp file in egs_app?
