### ISSUE TITLE
Segfaults and other crashes due to possible floating point errors in EGS_PolygonShape / EGS_2DPolygon

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#115]
Polygon shapes are built from the triangles of a polygon. The triangles of an EGS polygon are stored in a pre-allocated array of triangle shapes. For example, a trapeze (4 sides) would only need to store two triangles.

In some cases, one more triangle than is needed ends up being created [in this block of code](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/shapes/egs_polygon_shape/egs_polygon_shape.cpp#L90-L130). I suspect floating point errors in EGS_2DPolygon::isInside(). 

I consider this floating point issue more serious than the CD geometry errors because in this situation, it can lead to segmentation faults (e.g., [here](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/shapes/egs_polygon_shape/egs_polygon_shape.cpp#L130), because the extra triangle is being written to an array that does not have enough memory allocated, or even [here](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/shapes/egs_polygon_shape/egs_polygon_shape.cpp#L133)) and other (seemingly random) crashes.

On my system, the following polygon shape produces segfaults, in a non-consistent manner (but definitely produces 3 triangles instead of 2):

```
:start shape:
   library = egs_polygon_shape
   points = -0.1047 0.01232 0.1047 0.01232 0.0965 -0.01232 -0.0965 -0.01232
:stop shape:
```

But this one does not:

```    
:start shape:
   library = egs_polygon_shape
   points = -0.104701 0.012321 0.104701 0.012321 0.096501 -0.012321 -0.096501 -0.012321
:stop shape:
```

which is why I suspect floating point errors to be the underlying cause here.

This issue may also be related to issue #106.

I've included a tutor7pp input file.

[polygon_shape.txt](https://github.com/nrc-cnrc/EGSnrc/files/339345/polygon_shape.txt)

**Comment by ftessier** [comment]
Fixed in 9ef97f1.
