### ISSUE TITLE
Can you use egsnrc to calculate stopping power ratios for spherical geometries

### ISSUE THREAD

**Issue by karenrex1023** [nrc-cnrc/EGSnrc#1153]
Hello,
I am trying to calculate the spencer attix stopping power ratio for a spherical Exradin A3 ionization chamber in Co-60. I was wondering if I could still use SPRRZ for this purpose although it uses cylinders and slabs, or if there was another egsnrc code I should use?

Thank You!

**Comment by rtownson** [comment]
Followed up in discussion here: https://github.com/nrc-cnrc/EGSnrc/discussions/1154
