### ISSUE TITLE
A compilation error on egs++

### ISSUE THREAD

**Issue by CQUswl** [nrc-cnrc/EGSnrc#1159]
I wrote "myapp" according to the "getting start" document. When I compiled with" mingw32 ", I encountered some errors. I don't know whether it is a bug or some other reason, so please help me solve it.

![image](https://github.com/user-attachments/assets/c09119c6-d61d-4f87-8600-986080207b5b)

**Comment by CQUswl** [comment]
> I wrote "myapp" according to the "getting start" document. When I compiled with" mingw32 ", I encountered some errors. I don't know whether it is a bug or some other reason, so please help me solve it.
> 
> ![image](https://private-user-images.githubusercontent.com/114200268/348118892-c09119c6-d61d-4f87-8600-986080207b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTYyOTcsIm5iZiI6MTcyMDc1NTk5NywicGF0aCI6Ii8xMTQyMDAyNjgvMzQ4MTE4ODkyLWMwOTExOWM2LWQ2MWQtNGY4Ny04NjAwLTk4NjA4MDIwN2I1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwMzQ2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzg1NjY5OTI0MzlkMzFjMTgyMzc3ZjE4YjUyNjdiYWJhZWNjOTM2N2UyY2ZjZTIwMjhjMGQ2NWRiYzEzOGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zSqyji_MhcSYbH45h1wS8k4Sz5Pl3xSguhWeM9NZn2Y)
When the run is complete, the folder contains the following files:

![image](https://github.com/user-attachments/assets/f8df2dbd-87bf-4a26-87f4-92344f5714ef)

**Comment by rtownson** [comment]
This might be due to the non-latin characters in the `-DCOMPILE_TIME=` definition. Could you provide the installation log, found in HEN_HOUSE/log, so that I can see if the installation worked OK?

**Comment by CQUswl** [comment]
> This might be due to the non-latin characters in the `-DCOMPILE_TIME=` definition. Could you provide the installation log, found in HEN_HOUSE/log, so that I can see if the installation worked OK?

I also wondered if it was because I didn't fully install it, so I tried to re-download and install it several times. Finally, I found a file called "EGSnrc-guis-windows" in the release interface, and I found that the EGSnrc I installed did not have the contents of the file, so I put the contents of the file in the place where they should be, and finally successfully compiled egs++.

**Comment by rtownson** [comment]
The `EGSnrc-guis-windows` are not necessary to install and run EGSnrc. They just provide the GUIs, which are also available using [EGSnrc-configure-windows.exe](https://github.com/nrc-cnrc/EGSnrc/releases/download/v2023/EGSnrc-configure-windows.exe) if you click the checkbox on the installer to place the GUIs on the desktop. So I imagine that it was something else you did that fixed the installation. In any case, I'm glad it's solved!
