### ISSUE TITLE
Unsequenced modification and access warning in egs_spectra

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#116]
[Line 766](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/egs%2B%2B/egs_spectra.cpp#L766) of egs_spectra.cpp produces a warning about "unsequenced modification and access to `ibin`" with my compiler. Looking at the line, it obfuscates the intent of the developer and may yield unexpected results. I'd suggest an alternative, but to prove my case, I don't know what was the intent here.

**Comment by ftessier** [comment]
The compiler is warning you here that `ibin++` might be evaluated before `ibin` is used on the left side of the assignment. Using `ibin++` in this way is undefined in regards to the optimizer. This code is "wrong" in the sense that it will likely behave differently with different compilers, optimization level or language version. It should be replaced with:
```
 x[ibin] = eners[ibin];
ibin++;
```

**Comment by ftessier** [comment]
Fixed on the `feature-style` branch (f79ebdc) which will be merged before the next release.
