### ISSUE TITLE
egs_view 

### ISSUE THREAD

**Issue by huyngoc1123** [nrc-cnrc/EGSnrc#1178]
**Describe the bug**
egs_view appears for about 2 seconds and then auto shutdown
**To Reproduce**
A precise description of the steps to reproduce the behavior:
I ran make myapp.egsinp successfully. I also succeeded in compiling that file, but when I opened the egs_view, it only appeared for 2s and then turned off.

**Operating system**
- [x] Windows 11
**EGSnrc version**
 2023

**Comment by rtownson** [comment]
This can happen if the geometry in the .egsinp file is invalid. Does `egs_app/slab.egsinp` work? You can post your .egsinp file here.

**Comment by huyngoc1123** [comment]
> This can happen if the geometry in the .egsinp file is invalid. Does `egs_app/slab.egsinp` work? You can post your .egsinp file her
