### ISSUE TITLE
Lack of sync between the MU index in DOSXYZnrc source 20

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#125]
A DOSXYZnrc source 20 simulation with IAEA phsp as source (linac beam through static treatment head components) and shared library beam simulation (through patient/plan-specific components) imposed on a CT-based phantom provides unexpected dose distributions, when compared to identical simulation with the 2013 release (with required modifications to several files in HEN_HOUSE and EGS_home). Somehow it seems that there is something wrong in the sync between the MU index-based shared library simulation and DOSXYZnrc.

**Comment by blakewalters** [comment]
Are you seeing this problem with source 21 as well?

**Comment by ojalaj** [comment]
I haven't tested this with source 21 yet (actually I haven't used source 21 at all so far). It takes some time until I get this tested, but I will report how it goes (if no one else does that before me).

**Comment by blakewalters** [comment]
Go into $EGS_HOME/dosxyznrc/srcxyznrc.mortran and delete the macro:

$INIT_PHSP_COUNTERS

from the beginning of subroutine srcinit, recompile DOSXYZnrc and try it.

**Comment by ojalaj** [comment]
I downloaded the updated $EGS_HOME/dosxyznrc/srcxyznrc.mortran file and recompiled and run a simulation, but still something is wrong. All the sub-fields of a VMAT plan seem to be irradiated from the same, initial beam angle/(aperture also?) (the direction of the first control point / MU index range). This was also independently confirmed by a colleague of mine prior to the commit fddb316.

**Comment by blakewalters** [comment]
Please confirm that the macro $INIT_PHSP_COUNTERS does not appear at the beginning of subroutine srcinit in $EGS_HOME/dosxyznrc/srcxyznrc.mortran.

**Comment by ojalaj** [comment]
I confirm that the macro $INIT_PHSP_COUNTERS does not appear at the beginning of subroutine srcinit in $EGS_HOME/dosxyznrc/srcxyznrc.mortran.

**Comment by blakewalters** [comment]
Hmmm.  Would it be possible to attach your dosxyznrc_*.F file (or just send it to me via email)?  Also, I'd like to take a look at your .egsinp file.

Thanks!

**Comment by ojalaj** [comment]
I've just sent you the files via email.

**Comment by ftessier** [comment]
Fixed in cf8b24d.
