### ISSUE TITLE
Bug with fat photon rejection when using directional brem splitting with isource = 21 in dosxyznrc

### ISSUE THREAD

**Issue by marenaud** [nrc-cnrc/EGSnrc#13]
Hi all,

If you compare the fat photon rejection line [from source 21](https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran#L4035)

```
        ELSEIF(i_dbs=1 & iqin=0 & iphatsrc=1) [
           nsrjct=ndbsrjct+1;
           goto :retry_sample_beam_vcu_source:;
        ]
```

to the one from [from source 10](https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran#L3706)

```
        ELSEIF(i_dbs=1 & iqin=0 & iphatsrc>1) [
           nsrjct=ndbsrjct+1;
           goto :retry_sample_beamsource:;
        ]
```

you'll notice that in one case it checks for **iphatsrc=1** and in the other it checks for **iphatsrc>1**, not sure if that's intended, but I'm getting basically garbage doses when running source 21 and DBS, whereas I get what I expect in source 10, so I expect it was intended to be iphatsrc > 1 in source 21? (I also get what I expect when I manually set it to > 1 and recompile)

**Comment by ftessier** [comment]
Fixed in 6fa05d3
