### ISSUE TITLE
Photon splitting max 2000

### ISSUE THREAD

**Issue by gwu-reflexionmedical** [nrc-cnrc/EGSnrc#133]
I used BEAMnrc with DBS to run several simulations, and I noticed the maximum photon splitting number is hard coded to be 2000 (from the egslst output file and the size of the phsp file). I checked the manual but I could not find it anywhere (The manual actually suggests use 5000 photon splitting). Is there a way to remove the limit for photon splitting number?

I used Ubuntu 15.10 and the latest EGSnrc for the simulation

**Comment by ftessier** [comment]
Closing this issue because it is not related to a bug in the code. Issues are reserved for actual bugs, not technical support questions.

**Comment by gwu-reflexionmedical** [comment]
Sorry for the mess, I thought it was a bug since the number in the input file does not match the number that is actually used during the simulation.
