### ISSUE TITLE
Add labels feature to existing applications and documentation

### ISSUE THREAD

**Issue by jw3126** [nrc-cnrc/EGSnrc#139]
First of all it is great to have a free and powerful MC tool like EGSnrc. Thanks a lot to everybody involved in creating it! One pain point about EGSnrc is with the leaky abstraction of geometry. What I mean is that one is forced very often to reference pieces of the geometry by integers even if they have string names.

For example assume we want to to score dose deposition in a detector. In order to do this, one would create an input file for egs_chamber. In the input file one builds up the geometry from basic pieces like `egs_box`, `egs_gunion`, ... and each of these items is assigned a hopefully descriptive name by the user. 

But when it comes to specifying areas for variance reductions or scoring, all these descriptive names are worth little and one has to play around with `egs_view` to find out region numbers and put them into the input file (BTW I like `egs_view`, it produces amazing visualization!). This is time consuming and error prone, it would be cool if the computer could do it for us. 

1) Are there any plans is this direction? 

In a perfect world, we would have a function, 

`getRegionByName(name)`

which takes a name and returns its region number. Unfortunatelly pieces in the input file are not 1:1 with region numbers, so this can not quite work. For example a single `EGS_ZCylinders` might have many "anonymous" subregions, while an `EGS_transformed` does not increase the region count at all. However each geometry class could have a method

`getRegionByName(name, i)`

which calculates the region number of the ith piece of the subregion called `name`. So for instance if the simulation geometry is a `gunion` of `boxy` the `EGS_Box` and `cyly` the 5 layered `EGS_ZCylinders`, invoking `getRegionByName(cyly, 3)` on the simulation geometry would give the region number of layer 3 of our cylinder. 

2) Do you think that is would be a reasonable approach?
3) To me it seems one could implement this function roughly like `isWhere`, but passing `name,i` instead of a point around. Do I see this correctly or are there hidden traps?

**Comment by ftessier** [comment]
Thank you for your suggestion. In fact, this functionality has already been implemented via region "labels", however this feature has not yet been documented yet, or been added to the applications distributed with the software. Labels allow you can assign a string to region(s) in a geometry in the input file, using the local region indices, e.g.,
```
set label = mylabel 12 17
```
Once defined, you can obtain a list of global region numbers from the label string at any point in the application, e.g.,
```
 vector<int> regions;
g->getLabelRegions(mylabel, label_regions);
```

**Comment by jw3126** [comment]
Thanks, that sounds great! Can you point me at the C++ code, where these are implemented?

**Comment by ftessier** [comment]
Look for the `setLabels()` and `getLabelRegions()` methods in the geometry classes.

**Comment by randlet** [comment]
The labels feature sounds nice but I think there is room for improvement on how egs++ makes its region information available to apps.  Getting the global region numbers assigned to a geometry in an automatic fashion was one thing that was a fairly big hurdle for me when creating a custom egs++ code.  

Having a couple of types/functions similar to this:

```
typedef pair<int, int> RegionRangeT;
typedef pair<EGS_BaseGeometry*, int> geomRegionT;

RegionRangeT getGeomRegionBounds(string geomName); // return first and last global region numbers for a geometry
geomRegionT globalRegNumToLocalRegNum(int ir); // take global region number and return pointer to the geometry it is part of plus the local region number
int localRegNumToGlobalRegNum(geomRegionT geomReg);  // take a geometry/region pair and return the global region number
```

would be very helpful.

Something like this would be nice too:

```
struct GeomRegionInfo {
    EGS_BaseGeometry* geom;
    int nreg; /*!< total number of regions in this geometry */
    int start; /*!< global start region number */
    int end; /*!< global end region number */
};

GeomRegionInfo getRegionInfo(string geomName);
```

For what its worth I ended up creating something similar to the above by re-parsing the geometry block from the input file and building up a tree of geometry objects and their children and then calculating all the global to local region number conversions from that tree.  It feels like a big hack and it would be nice if egs++ could track more region number information during geometry initialization and make it available to apps.

**Comment by ftessier** [comment]
Thank you @randlet for the suggestion!

**Comment by rtownson** [comment]
Fixed in release-2017.
