### ISSUE TITLE
Missing details in PIRS-898 for isotropic source definition

### ISSUE THREAD

**Issue by mainegra** [nrc-cnrc/EGSnrc#140]
**Missing information:** Arbitrary `isotropic sources` can be defined combining a shape and a geometry. The user has control over which geometry regions are part of the source.

**Comment by MartinMartinov** [comment]
I also found out about this not long ago, here are the 3 not documented inputs

		geometry           = Final_Geom
		region selection = IncludeSelected 
                # above options are: IncludeAll || ExcludeAll || IncludeSelected || ExcludeSelected
		selected regions = 0
                # needed if include or exclude selected is used

I tested it out on some simple cases and it seems to work well.

**Comment by mainegra** [comment]
@MartinMartinov we use these features all the time to model extended radioactive sources! It is even taught at all EGSnrc courses!!! But it has eluded the documentation so far! ;-P

**Comment by rtownson** [comment]
Fixed in release-2017.
