### ISSUE TITLE
IAEA phase-space file library needs separate re-compilation

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#144]
With a pristine clone of current 'develop' branch I encounter following issues, when trying to run the egs_chamber code with IAEA phsp file as source. With some previous release I managed to get this working by re-compiling in different directories under `HEN_HOUSE`, but even that doesn't work now.

For some reason `libiaea_phsp_source.so` is not created under `HEN_HOUSE/egs++/dso/myconfig`. Another issue is the first output about `config.guess`: I don't know why it happens:

```
The canonical system as returned by config.guess (x86_64-unknown-linux-gnu) is not the
same as the one found in the configuration file (linux64).
I hope you know what you are doing.

In EGS_Application::initSimulation()
```

```
EGS_Library::load(): failed to load library /home/mc/EGSnrc/HEN_HOUSE/egs++/dso/160727/libiaea_phsp_source.so
  error was: /home/mc/EGSnrc/HEN_HOUSE/egs++/dso/160727/libiaea_phsp_source.so: cannot open shared object file: No such file or directory
EGS_ObjectFactory::createObject(): failed to load the library iaea_phsp_source from /home/mc/EGSnrc/HEN_HOUSE/egs++/dso/160727
EGS_ObjectFactory::createObjects(): 1 errors occured while creating objects
EGS_ObjectFactory::createObjects(): an object with the name BEAM_myAccel does not exist


EGS_Application::initSimulation(): source initialization failed
EGS_RandomGenerator::createRNG: no 'RNG definition' input
EGS_Application::initRNG(): using default RNG
```

**Comment by ojalaj** [comment]
Problem solved by re-compiling under HEN_HOUSE/egs++/sources/iaea_phsp_source. Maybe this could be done already when compiling under HEN_HOUSE/egs++?

**Comment by rtownson** [comment]
Confirmed, you need to compile under HEN_HOUSE/egs++/sources/iaea_phsp_source.

Doing "make clean; make" in HEN_HOUSE/egs++ did not delete libiaea_phsp_source.so for me.

**Comment by rtownson** [comment]
Fixed in release-2017.
