### ISSUE TITLE
Question on compiling egs_view

### ISSUE THREAD

**Issue by yangguang222** [nrc-cnrc/EGSnrc#149]
Please: My egs_view can't open the example of egs++,  for example :cones.geom.    Who can solv this problem？  Thank you very much.

**Comment by rtownson** [comment]
This is probably an installation mistake not a bug. In the future, unless you're sure it's a bug try asking in the [google group for EGSnrc](https://plus.google.com/communities/106437507294474212197), there are lots of helpful people there!

Having said that - what error do you see? Are you on linux or windows? Have you installed QT4? Check [this link on building the GUIs](https://github.com/nrc-cnrc/EGSnrc/wiki/Building-GUIs-on-Linux).

**Comment by yangguang222** [comment]
It  displays nothing .I am on linux , I had installed QT4.

**Comment by rtownson** [comment]
When you run egs_view without any arguments, does the application open? Does anything print in the terminal?

When you compiled (step 3 in the link I sent you), did it give any errors? Did you set QTDIR in your .bashrc file and start a new terminal?

**Comment by yangguang222** [comment]
Do you mean set QIDIR in my .bashrc or qt4?

**Comment by yangguang222** [comment]
what is the meaning of set QTDIR in my .bashrc file?    is it the command 'QIDIR=/USR/include/qr4(my path)?

**Comment by rtownson** [comment]
Assuming you are using a bash shell, then putting the line "export QTDIR=/usr/lib64/qt4" in your ~/.bashrc file will set QTDIR as an environment variable, the next time you start a new shell. This also assumes that qt4 was installed to the directory /usr/lib64/qt4 (check that it exists).

**Comment by yangguang222** [comment]
problem solved. thank you very much
