### ISSUE TITLE
PreviewRZ does not work on macOS

### ISSUE THREAD

**Issue by Abdullah-Abuhaimed** [nrc-cnrc/EGSnrc#150]
Hi there, 

I use a mac machine with (el capitan) system. I am not able to get prviewrz working in RZ egs user codes using their gui. Both egs_view and preview accelerator of beamnrc work with no issue. Is there any way to fix this issue?

Thanks,
Abdullah

**Comment by ftessier** [comment]
Migrated to #704.

**Comment by ftessier** [comment]
Please consult the updated [macOS installation instructions](https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS), which are known to work on macOS 11 (Big Sur), including the egsinprz preview. Please report any further issue in #704.
