### ISSUE TITLE
Feature request: command line installer 

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#153]
I've been doing a bunch of installs with the command line installer and I have a bit of a nit to pick. When I change the compiler flags from default I would like to see a confirmation of my changes so that I can correct any type-os. Is this something that could be done in the future?

**Comment by ftessier** [comment]
I have a "new and improved" version of the configure script, which is a bit more friendly. I will keep your comment in mind while working on it, but I don't think I will add what you request. Instead I use an `expect` script which contain my configuration options and drives the configure script automatically! Give that a try, it works great! (More simply, you can also feed a file via stdin to the configure script, with one answer per line).
