### ISSUE TITLE
Radiative Compton corrections for egs++ codes

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#154]
According to PIRS 898 Radiative Compton corrections could be just turned on with egs++ codes, but this generates:
**************\* Warning:
You are trying to use radiative Compton corrections
without having included rad_compton1.mortran
Turning radiative Compton corrections OFF ...

and I could not find instructions where to include line with rad_compton1.mortran with these codes.

**Comment by mainegra** [comment]
@ojalaj this information is sadly still missing in the documentation. We will update the documentation with the required information soon via a pull request. Meanwhile here is the skinny on how to include `rad_compton1.mortran` for all kinds of EGSnrc applications:

To turn ON radiative Compton corrections `rad_compton1.mortran` must be first added to the list of MORTRAN sources to be built:

- For  all C++ applications one must edit the file `$HEN_HOUSE/specs/egspp1.spec` and add
`$(EGS_SOURCEDIR)rad_compton1.mortran` just before `$(EGS_SOURCEDIR)get_inputs.mortran`
in the definition of the C_ADVANCED_SOURCES variable if the application is derived from the EGS_AdvancedApplication class or the C_SIMPLE_SOURCES variable for any application derived from the EGS_SimpleApplication.

- For a specific C++ application one could define the variable CPP_SOURCES in the application's Makefile in the same manner as the C_ADVANCED_SOURCES in the file `$HEN_HOUSE/specs/egspp1.spec` and add `$(EGS_SOURCEDIR)rad_compton1.mortran` just before `$(EGS_SOURCEDIR)get_inputs.mortran`.

- For a MORTRAN application named for instance `app` one must edit the corresponding file `app.make` located in the application's folder `$EGS_HOME/app` and add `$(EGS_SOURCEDIR)rad_compton1.mortran` just before `$(EGS_SOURCEDIR)get_inputs.mortran` in the definition of the SOURCES variable.

- For a BEAMnrc application one must edit the file `sources.make` and add
`$(EGS_SOURCEDIR)rad_compton1.mortran` just before `$(EGS_SOURCEDIR)get_inputs.mortran`
in the definition of the SOURCES variable or the LIB_SOURCES variable if this BEAMnrc application will be used as a particle source for another application.

Hope this helps!

**Comment by ojalaj** [comment]
Thank you mainegra - the first two bullets were something I couldn't figure out by myself, whereas the last two are clear to me (to be more exact - the third bullet is already well-documented, while the fourth one is not, but yet quite intuitive).

**Comment by ojalaj** [comment]
One addition for the comment on the second bullet is that e.g. for egs_chamber in the Makefile there is no $(EGS_SOURCEDIR)get_inputs.mortran above which the user could add  $(EGS_SOURCEDIR)rad_compton1.mortran so that was the primary reason I couldn't figure the correct file/line by myself.

**Comment by mainegra** [comment]
@ojalaj the second bullet refers to basically defining `CPP_SOURCES` in  the application's `Makefile` in the same manner as it is done for `C_ADVANCED_SOURCES` in the file `$HEN_HOUSE/specs/egspp1.spec`. Note that `CPP_SOURCES` takes the value from `C_ADVANCED_SOURCES`. This is useful in the case you want to allow radiative Compton corrections ONLY for that particular EGSnrc application.

**Comment by ojalaj** [comment]
Thank you for the clarification.
