### ISSUE TITLE
IAEA phsp source: illegal attempt to set simulation chunk

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#157]
When using IAEA phsp as a source with egs_chamber, I get this kind of output to `.egslog` files of each batch run. Is everything functioning as expected? I apologize, if this means nothing, but I just always want to check, whenever I get errors/warnings/other negative output that I'm not familiar with. Simulation results seem to be OK. Are the uncertainty estimates incorrect as indicated?:

```
      9             1847.68    5.38005e-18           0.67
     10             1910.29    5.37711e-18           0.66
IAEA_PhspSource::setSimulationChunk(): illegal attempt to set the simulation chunk between 99999901 and 100555455 ignored

Running 555555 histories
    combined result from this and other parallel runs: 5.31964e-18 +/-   0.104%

  Batch             CPU time        Result   Uncertainty(%)
 ==========================================================
      1IAEA_PhspSource::getNextParticle(): reached the end of the phase space file chunk (8333325)
  will start from the beginning of the chunk (7777771) but this implies that uncertainty estimates will be inaccurate
             1974.76    5.38098e-18           0.65
      2             2038.45    5.38335e-18           0.64
      3             2103.54      5.387e-18           0.63
```

**Comment by blakewalters** [comment]
Hi Jarkko:

Both of these messages indicate a parallel run that is using up all of the phase space data and so the run is "rewinding" back to the beginning of the file.  As the second message says: uncertainties will be underestimated--significantly if you're seeing this message a lot during a run.  If this message is coming up many times (>3) within a run (or chunk of a run in the case of parallel jobs), I would encourage you to use the inputs:

reuse photons = Nrcycl
reuse electrons = Nrcycl

inputs within the source delimiters, where Nrcycl, the number of times to recycle each particle before moving on to the next one, is equal to the no. of times you get the "reached the end of the phase space file chunk..." message within a single run chunk.
