### ISSUE TITLE
egs_chamber

### ISSUE THREAD

**Issue by yangguang222** [nrc-cnrc/EGSnrc#173]
When I get the following warning when running the egs_chamber example codes. Can you help me?
:
EGS_Liabrary : : load (): failed to load liabrary
/home/EGSnrc/egs_home/bin/linux64/libBEAM_Elekta_nrc.so : cannot open shared object file :No such file
or directory

**Comment by rtownson** [comment]
Hi @yangguang222, as I mentioned last time, please post questions like this to our [google+ community](https://plus.google.com/communities/106437507294474212197).

You probably need to make the shared library for the accelerator (in the accelerator directory, use 'make library', after you have already done beam_build and make).
