### ISSUE TITLE
NaN with -ffast-math

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#174]
NaN (still) shows up when using -ffast-math with the Fortran compiler. This happens with gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC).

Sample input file for `tutor7pp` below.

With -ffast-math flag:

`Medium            1  sige =   1.00000000362749373E-015                       NaN  monotone =  T T`

`Medium            2  sige =   1.00000000362749373E-015                       NaN  monotone =  T T`

Without -ffast-math:

`Medium            1  sige =   0.43671621424277174       0.43386623396694124       monotone =  T T`

 `Medium            2  sige =   0.24630246820211257       0.24325696800012028       monotone =  T T`

As far as I know, this does not produce any significant differences in the results of `tutor7pp` (or any other code), but I'm not entirely sure.

[material.txt](https://github.com/nrc-cnrc/EGSnrc/files/457483/material.txt)
[media_bug.txt](https://github.com/nrc-cnrc/EGSnrc/files/457484/media_bug.txt)

**Comment by crcrewso** [comment]
May I ask, which input file were you using? Test1?

**Comment by mchamberland** [comment]
The input file attached to the report: "media_bug.txt"

GitHub does not allow .egsinp extensions.

**Comment by crcrewso** [comment]
Ahhh sorry it threw me not being an egsinp.

**Comment by rtownson** [comment]
Is this still a problem on the current develop branch? I could not reproduce on centos. Thanks!

**Comment by crcrewso** [comment]
Which gcc did you test with? I thought this was a 4.4 series issue.

**Comment by rtownson** [comment]
Good point - I was on gcc 4.8.5.

**Comment by Kawrakow** [comment]
Suggestion: discard the -ffast-math flag. Better (i.e., faster and less dangerous) outcomes with modern gcc versions are achieved using -march=native -mtune=native

**Comment by ftessier** [comment]
Will do, thanks for the info!
