### ISSUE TITLE
Beamdp and addphsp floating point exception for large IAEA phase space files 

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#186]
I thought that we had all the IAEA beamdp stuff nailed but I'm running into a problem, though it may be with more than just IAEA phsps's. It started when I took all the Varian source files and added them together. I wanted to get a handle on what the whole data set looked like. 
- I looked through past issues and pulls trying to find something, there was some similar issues but nothing that helped. 
- I did remake beamdp, which did note the addition of the IAEA files in the compile process. 
- The data set was added using addphsp and the IAEA options for the Varian TB 10FFF 10MV and 15MV provided files
- I was able to get successful results previously from Egsnrc phsps generated from a smaller set of these IAEA phsps 
- I've tried with options 3 and 4, both planar and estimated real fluences.
- Both radial and x, y bounded
- My first thought is that since the source files are so large, something might be overloading

Here's the agr that goes along with the example run below. [10fff.txt](https://github.com/nrc-cnrc/EGSnrc/files/496462/10fff.txt) I would attach the source phsp but it's a bit big (even my little test one is 3GB, the rest are 70+). If you have an ftp you'd like me to send it to I'd be happy to for troubleshooting. 

```
crcrewso@SPARROW:~/EGSnrc/egs_home/TB_at_26_7cm$ beamdp


 Running BEAMDP, Version v 1.9
 -----------------------------------------------------------
 Type ? at any prompt for help

 BEAMDP (BEAM Data Processor) creates a source parameter file
 for beam characterization models with information obtained
 from the user and derived from a full phase-space data file
 created by BEAM

 This programme can be used to derive planar fluence, spectrum,
 mean energy and angle distribution, etc., from a phase-space
 file created by BEAM.

 Ifyou are not familiar with this programme, you can get an
 explanation before any input request. Otherwise, the prompts
 will be terse.

 However, you can get help by typing a ? to any prompt.

 Do you wish more detailed information about the file created
 by the program?   (y/n[Default])=> n

 Input a number for the operation required:
 ********************************************

 (0) - Process data for beam characterization models
 (1) - Derive fluence vs position from ph-sp data
 (2) - Derive energy fluence vs position from ph-sp data
 (3) - Derive spectral distribution from ph-sp data
 (4) - Derive energy fluence distribution from ph-sp data
 (5) - Derive mean energy distribution from ph-sp data
 (6) - Derive angular distribution from ph-sp data
 (7) - Derive ZLAST distribution from ph-sp data
 (8) - Derive distribution of particle weights from ph-spdata
 (9) - Derive X-Y scatter plot of particles from ph-sp data
 (10) - Combine two ph-sp files into one
 (11) - List parameters for a number of ph-sp particles
 (12) - Output (x,y,z) coordinates to file (IAEA only)
 (13) - Quit
 3
Selected option   3

 IQ(-1,0,1,2,3),Xmin,Xmax,Ymin,Ymax(or Rmin,Rmax)
 2, 0, 15
   2    0.0000   15.0000    0.0000    0.0000

 Annular region: Rmin,Rmax=     0.000    15.000

 Nbin, Emin, Emax (in MeV, kinetic only) for the distribution =
 200, 0, 15
   200      0.0000     15.0000

 Input three integer variables on one line: I_IN_EX, Nbit1,Nbit2
 I_IN_EX (0-incl/excl bits, 1-excl bits, 2-incl regions, 3-excl regions),
 Nbit1   (# bits or regions to incl (if I_IN_EX=0 or 2) or excl (I_IN_EX=1 or 3),
 Nbit2   (# bits to excl (I_IN_EX=0 only)--all on one line :

     0     0     0

 Name of file containing phase space data (with ext., < A100):
 TrueBeam_v2_10fff.IAEAphsp
 File name input is:TrueBeam_v2_10fff.IAEAphsp

 Data is in IAEA format.


            Total number of particles in file:    137586664
                     Total number of photons:    136281534
The rest are electrons/positrons.

      Maximum kinetic energy of the particles:       10.400 MeV
 # of incident particles from original source:    972000000
                       Z at which phsp scored:       26.700 cm

 Name of file to save data for graph plotting:
 10fff.agr
 File name input is:10fff.agr

 INPUT GRAPH TYPE (0: normal, 1: histogram)

 0

 Plot planar fluence (1) or estimate of real fluence (0--default)

 1
 Begin writing graph data into file...

 Create another set of spectral data using the same ph-sp file?
 (1: yes, 0: no - quit)
 0
       0

 Plot the data just created using xmgrace before quiting?
 (1: yes, 0: no - quit)
 1
Plot the data

 BYE!


 If running gui, this window will close before next run!

sh: 1: Note: The following floating-point exceptions are signalling:xmgrace_script: not found IEEE_INVALID_FLAG
 IEEE_DIVIDE_BY_ZERO
```

**Comment by blakewalters** [comment]
Hi @crcrewso:

Try using the attached version of beamdp.txt (copy it to $OMEGA_HOME/progs/beamdp/beamdp.mortran and type "make").  This redefines a couple of variables (NHSTRY, NHSTRY_LAST) as INTEGER*8 and also uses REAL*8 instead of REAL*4.  Do you still get the same issue?

If so, I'm wondering if it has to do with problems using addphsp to concatenate the phase space files.

[beamdp.txt](https://github.com/nrc-cnrc/EGSnrc/files/804886/beamdp.txt)

**Comment by crcrewso** [comment]
@blakewalters Sure, I can do that testing within the next couple of days. 

I didn't suspect addphsp since I've simulated beam over the entire data set and beamdp does show the number of particles within the phase space file, .

**Comment by crcrewso** [comment]
@blakewalters first check, it worked! Will do a bit more testing shortly. My solution was to change a lot more variables to Int8 and Real8 which of course produced prodigious errors with library functions. 

Thank you! 

What testing would you like to see before submitting this upstream?

**Comment by blakewalters** [comment]
Excellent to hear it worked @crcrewso!  Let me know when you've had a chance to test it on other files.  If you have no problems, then I'll go ahead and push the change to the repository.

Thanks!

**Comment by crcrewso** [comment]
I've tested on a couple of files with both options 3 and 4. It seems to work as I need it to.

**Comment by ftessier** [comment]
Reopening this issue: it should only be closed once the solution proposed by @blakewalters has been integrated into merged into the develop branch.
