### ISSUE TITLE
Addphsp not adding new data to existing IAEA phsp file

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#201]
I'm trying to add particle data to existing IAEA phsp file (XXXX.1.IAEAphsp). I have re-run the accelerator simulation and having the previously concatenated IAEA phsp file (XXXX.1.IAEAphsp) and header (XXXX.1.IAEAheader) in the same directory, I ran addphsp, but a completely new file was generated instead of adding data to existing file. The file name I used for output phsp with addphsp is exactly the same as previously (of course without the extension as required). The following is printed among other information:

 First time writing to this file.
 No header data to display.

So addphsp does not recognize the existing IAEA header. Is this something that I should expect to happen?

**Comment by ojalaj** [comment]
The issue has been solved. Thank you blakewalters!

**Comment by rtownson** [comment]
Fixed in release-2017.
