### ISSUE TITLE
Bug with bremsstrahlung splitting in egs_chamber

### ISSUE THREAD

**Issue by pgfwatso** [nrc-cnrc/EGSnrc#205]
There is a problem with the current implementation of brem splitting in egs_chamber.cpp
The variable for number of split radiative photons is read from the .egsinp file (line 938 of egs_chamber.cpp):

        //
        // ******** radiative event splitting
        //
         int csplit=1;
         if( !vr->getInput("radiative splitting", csplit) && csplit > 1) {
            egsInformation("\n => initScoring: splitting radiative events %d times ...\n", csplit);
           the_egsvr->nbr_split = csplit;
}

However, this variable is overwritten when the radiative event comes from an electron which has survived RR (line 1974):

    // split up fat electrons' radiative events
    // i.e. electrons that survived range-rejection RR
    if( (the_stack->latch[np] != 0) &&
        (iarg == BeforeBrems || iarg == BeforeAnnihFlight || iarg == BeforeAnnihRest) ) {
        the_egsvr->nbr_split = the_stack->latch[np];	// split photons up
        return 0;
}

After RR has been handled, the brem splitting number is set back to 1 (line 1998):
 the_egsvr->nbr_split = 1; 

As I understand it, this means that after the first photon interaction with cross-section enhancement occurs, bremsstrahlung splitting is effectively turned off.

A colleague (Marc-Andre Renaud) and I were able to fix this by declaring a private EGS_ChamberApplication class variable, which is then set to the value of csplit. After the RR, the brem splitting number is set back to this class variable instead of 1.

**Comment by rtownson** [comment]
Yes, we were aware of this issue! If you have a good solution feel free to submit it as a pull request, I don't believe anyone had planned a fix yet.

**Comment by rtownson** [comment]
Hi Pete, let me know if PR #284 is equivalent to your solution.

**Comment by pgfwatso** [comment]
Hi Reid,
Yes, you've captured the spirit of our solution :)
Thanks!
-Pete
