### ISSUE TITLE
Allow skipping of dosxyznrc isource 20 "calibration run"?

### ISSUE THREAD

**Issue by marenaud** [nrc-cnrc/EGSnrc#209]
DOSXYZnrc source 20 (phsp source) runs a calibration run of 1mil particles when passing through a shared library to refine the estimate of NRCYCL needed. If I have a gigantic phase space file and know for sure that I won't need to recycle particles, I would like to skip that calibration run as it adds unnecessary overhead. Would you guys consider allowing a flag in the input file to skip the calibration run? If so, I may be able to look into it to see how easily it could be done.

**Comment by rtownson** [comment]
I don't see a problem with having an option to disable the calibration run for source 20, does anyone else?

As a sidenote, if you re-use a large phase-space often (and have lots of RAM) consider putting it is /dev/shm to load it into RAM semi-permanently (/dev/shm is cleared on reboot). I've seen great speed-ups from that.

**Comment by crcrewso** [comment]
I'd need a lot of ram for my 74 GB TB phase spaces.
