### ISSUE TITLE
beamdp overflow issues with large phase spaces

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#213]
This one is esoteric but if someone has a hint at where to start in the code I would greatly appreciate it. 

I've been trying to run some energy spectra analysis using beamdp on the overly large 75 GB full TB phase space files for a specific project. My 13 GB sample files seem to run beamdp options 3 and 4 without issue but the larger files give me all infinities in the resulting grace file. I would guess something in the code doesn't like adding that many particles but before I dive into fortran replacing all the floats with doubles does anyone have any experience with this problem? 

If I do get it fixed would the fix be worth pushing back here since its a small edge case, the fix for which does have some performance and memory disadvantages to smaller data sets?

**Comment by rtownson** [comment]
The changes will probably just involve some counting variables, and that should have minimal performance impact. My guess is that the variables counting particles like `N_ph_sp_e` are overflowed by the large number, and instead should be of the type `$LONG_INT`. Support for TB phase-spaces would be useful if it is a reasonably straight-forward fix!

**Comment by crcrewso** [comment]
please see Issue #186, I didn't realize that I had double posted the same issue. Thank you @blakewalters for posting a solution.
