### ISSUE TITLE
Incorrect description of i_survived_rr in egs_interface2.h

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#215]
The description of the `i_survived_rr` variable in [egs_interface2.h](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/interface/egs_interface2.h#L585-L589) is incorrect. It should read:

`    /*! If Russian Roulette of electrons created in photon interactions is
      on (#i_play_RR is 1), i_survived_RR is set to the number of electrons
      **killed** in the RR game.
    */`

This can be confirmed by looking at the comments in [egsnrc.macros](https://github.com/nrc-cnrc/EGSnrc/blob/e18770cbc7052670938c1e3e6714f77e73cc8577/HEN_HOUSE/src/egsnrc.macros#L3362-L3363) or in [egsnrc.mortran](https://github.com/nrc-cnrc/EGSnrc/blob/e18770cbc7052670938c1e3e6714f77e73cc8577/HEN_HOUSE/src/egsnrc.mortran#L4482).

**Comment by rtownson** [comment]
This has been fixed in the feature-style branch.
