### ISSUE TITLE
Cannot resize windows - dosxyznrc_gui

### ISSUE THREAD

**Issue by aguadopd** [nrc-cnrc/EGSnrc#236]
I'm using v2016 for Windows, in Windows 10. When I use dosxyznrc_gui in my laptop, the _input_ window is not resizable (and probably others) and then I cannot complete the process. Is there any workaround?
Thanks in advance.

**Comment by ftessier** [comment]
The only immediate solution is to install a **third-party utility** which allows you to drag and resize a window by clicking with modifier key, for example: winxmove, altdrag, easymove, and problably many others. Please let us know if you find a good one for Windows 10.

**Comment by aguadopd** [comment]
Thanks a lot. Meanwhile I moved to Ubuntu, but will try later.

**Comment by ftessier** [comment]
That is an even better solution! :+1:
