### ISSUE TITLE
EGSnrc-configure-linux  executable not found on the EGSnrc web page

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#239]
On https://github.com/nrc-cnrc/EGSnrc/wiki/install-EGSnrc-on-linux the user is instructed to "1.Download the  EGSnrc-configure-linux  executable from the EGSnrc web page".

However, at least I'm not able to find it opening the link. Only the documentation is there.

**Comment by rtownson** [comment]
Thanks for reporting this! I've updated the wiki to point to the release page. Note that it points to the *latest* release, which currently is still the 2016 release (that will change soon).
