### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by magedm22** [nrc-cnrc/EGSnrc#243]
I am tired of the many attempts to no avail
The same error appears upon installation
all the step of installation were applied 
I hope to get your help

/usr/bin/sh: line 0: cd: geometryegs_planes: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_pyramid: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_gstack: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_vhp_geometry: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_smart_envelope: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_conez: No such file or directory
/usr/bin/sh: line 0: cd: sourcesegs_collimated_source: No such file or directory

/usr/bin/sh: line 0: cd: sourcesegs_isotropic_source: No such file or directory
/usr/bin/sh: line 0: cd: sourcesegs_source_collection: No such file or directory
/usr/bin/sh: line 0: cd: sourcesegs_transformed_source: No such file or directory
/usr/bin/sh: line 0: cd: sourcesegs_angular_spread: No such file or directory
Makefile:176: recipe for target 'egs_pyramid' failed

mingw32-make: *** [egs_pyramid] Error 1

mingw32-make: *** Waiting for unfinished jobs....

Makefile:176: recipe for target 'egs_smart_envelope' failed

mingw32-make: *** [egs_smart_envelope] Error 1

Makefile:181: recipe for target 'egs_collimated_source' failed

mingw32-make: *** [egs_collimated_source] Error 1

Makefile:181: recipe for target 'egs_source_collection' failed

mingw32-make: *** [egs_source_collection] Error 1

/usr/bin/sh: line 0: cd: sourcesiaea_phsp_source: No such file or directory
/usr/bin/sh: line 0: cd: shapesegs_extended_shape: No such file or directory
/usr/bin/sh: line 0: cd: shapesegs_gaussian_shape: No such file or directory
Makefile:181: recipe for target 'egs_angular_spread' failed

mingw32-make: *** [egs_angular_spread] Error 1

Makefile:176: recipe for target 'egs_planes' failed

mingw32-make: *** [egs_planes] Error 1

Makefile:186: recipe for target 'egs_extended_shape' failed

mingw32-make: *** [egs_extended_shape] Error 1

/usr/bin/sh: line 0: cd: geometryegs_space: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_box: No such file or directory
/usr/bin/sh: line 0: cd: sourcesegs_parallel_beam: No such file or directory
Makefile:181: recipe for target 'egs_isotropic_source' failed

mingw32-make: *** [egs_isotropic_source] Error 1

Makefile:176: recipe for target 'egs_box' failed

mingw32-make: *** [egs_box] Error 1

Makefile:176: recipe for target 'egs_gstack' failed

mingw32-make: *** [egs_gstack] Error 1

Makefile:176: recipe for target 'egs_space' failed

mingw32-make: *** [egs_space] Error 1

Makefile:176: recipe for target 'egs_vhp_geometry' failed

mingw32-make: *** [egs_vhp_geometry] Error 1

Makefile:181: recipe for target 'egs_parallel_beam' failed

mingw32-make: *** [egs_parallel_beam] Error 1

Makefile:181: recipe for target 'egs_transformed_source' failed

mingw32-make: *** [egs_transformed_source] Error 1

Makefile:186: recipe for target 'egs_gaussian_shape' failed

mingw32-make: *** [egs_gaussian_shape] Error 1

Makefile:176: recipe for target 'egs_conez' failed

mingw32-make: *** [egs_conez] Error 1

Makefile:181: recipe for target 'iaea_phsp_source' failed

mingw32-make: *** [iaea_phsp_source] Error 1

/usr/bin/sh: line 0: cd: sourcesegs_beam_source: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_iplanes: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_cd_geometry: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_roundrect_cylinders: No such file or directory
Makefile:181: recipe for target 'egs_beam_source' failed

mingw32-make: *** [egs_beam_source] Error 1

Makefile:176: recipe for target 'egs_cd_geometry' failed

mingw32-make: *** [egs_cd_geometry] Error 1

Makefile:176: recipe for target 'egs_iplanes' failed

mingw32-make: *** [egs_iplanes] Error 1

/usr/bin/sh: line 0: cd: geometryegs_elliptic_cylinders: No such file or directory
/usr/bin/sh: line 0: cd: sourcesegs_phsp_source: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_union: No such file or directory
/usr/bin/sh: line 0: cd: sourcesegs_point_source: No such file or directory
/usr/bin/sh: line 0: cd: shapesegs_line_shape: No such file or directory
/usr/bin/sh: line 0: cd: shapesegs_ellipse: No such file or directory
Makefile:176: recipe for target 'egs_roundrect_cylinders' failed

mingw32-make: *** [egs_roundrect_cylinders] Error 1

Makefile:176: recipe for target 'egs_elliptic_cylinders' failed

mingw32-make: *** [egs_elliptic_cylinders] Error 1

/usr/bin/sh: line 0: cd: geometryegs_gtransformed: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_cylinders: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_prism: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_genvelope: No such file or directory
/usr/bin/sh: line 0: cd: shapesegs_circle: No such file or directory
Makefile:176: recipe for target 'egs_union' failed

mingw32-make: *** [egs_union] Error 1

Makefile:181: recipe for target 'egs_phsp_source' failed

mingw32-make: *** [egs_phsp_source] Error 1

/usr/bin/sh: line 0: cd: geometryegs_octree: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_cones: No such file or directory
Makefile:181: recipe for target 'egs_point_source' failed

mingw32-make: *** [egs_point_source] Error 1

/usr/bin/sh: line 0: cd: geometryegs_spheres: No such file or directory
/usr/bin/sh: line 0: cd: geometryegs_nd_geometry: No such file or directory
Makefile:186: recipe for target 'egs_line_shape' failed

mingw32-make: *** [egs_line_shape] Error 1

Makefile:176: recipe for target 'egs_gtransformed' failed

mingw32-make: *** [egs_gtransformed] Error 1

Makefile:176: recipe for target 'egs_cylinders' failed

mingw32-make: *** [egs_cylinders] Error 1

Makefile:176: recipe for target 'egs_prism' failed

mingw32-make: *** [egs_prism] Error 1

Makefile:186: recipe for target 'egs_ellipse' failed

mingw32-make: *** [egs_ellipse] Error 1

Makefile:176: recipe for target 'egs_genvelope' failed

mingw32-make: *** [egs_genvelope] Error 1

Makefile:186: recipe for target 'egs_circle' failed

mingw32-make: *** [egs_circle] Error 1

Makefile:176: recipe for target 'egs_spheres' failed

mingw32-make: *** [egs_spheres] Error 1

Makefile:176: recipe for target 'egs_octree' failed

mingw32-make: *** [egs_octree] Error 1

Makefile:176: recipe for target 'egs_nd_geometry' failed

mingw32-make: *** [egs_nd_geometry] Error 1

Makefile:176: recipe for target 'egs_cones' failed

mingw32-make: *** [egs_cones] Error 1

Compilation failed!

**Comment by mainegra** [comment]
Sorry to hear you are having problems installing! Please note that issues here are **proven** flaws in the system which could be caused by bugs or compiler compatibility. 
You need to provide more information. It is confusing that you are using `mingw` and `bash` together. `MinGW` is the GNU compiler suite for Windows, while `bash` is a Unix shell commonly used on Linux systems. 
- Can you describe exactly what you are doing?
- Can you send us the config log file to any of [our contact emails](http://www.nrc-cnrc.gc.ca/eng/solutions/advisory/egsnrc_index.html)? This file will be located inside the HEN_HOUSE/log folder.

In the future, for technical support and questions, please consider the [EGSnrc Google+ community](https://plus.google.com/communities/106437507294474212197), or [contact NRC](http://www.nrc-cnrc.gc.ca/eng/solutions/advisory/egsnrc_index.html).
