### ISSUE TITLE
egs_view fails to launch from bash command line

### ISSUE THREAD

**Issue by jw3126** [nrc-cnrc/EGSnrc#264]
The following syntax worked before, but does not work anymore:
```
$ egs_view example1.egsinp 
bash: syntax error near unexpected token `example1.egsinp'
```
I can still use `egs_view`, but have to select the file by hand. This is a problem when using `egs_view` as part of a script.

**Comment by jw3126** [comment]
If I spell out the path of `egs_view` I get a different error message:
```Bash
admin@vm-ubuntu1404x64:~/EGSnrc/EGS_HOME/cavity$ /home/admin/EGSnrc/HEN_HOUSE/bin/linux64/egs_view example1.egsinp 
Object::connect: No such signal QLineEdit::lostFocus()
Object::connect:  (sender name:   'fileName')
Object::connect:  (receiver name: 'save image')
/home/admin/EGSnrc/HEN_HOUSE/bin/linux64/egs_view: symbol lookup error: /home/admin/EGSnrc/HEN_HOUSE/bin/linux64/egs_view: undefined symbol: _ZN9EGS_Input13takeInputItemERKSsb
```

**Comment by ftessier** [comment]
Thank for reporting this @jw3126. As a quick solution, perhaps you can compile egs_view yourself as per these instructions: https://github.com/nrc-cnrc/EGSnrc/wiki/Building-GUIs-on-Linux

**Comment by jw3126** [comment]
Thanks for looking into this issue. As you suggested I compiled `egs_view` myself. Now I still get
```Bash
$ egs_view example1.egsinp 
bash: syntax error near unexpected token `example1.egsinp'
```
while 
```Bash
$ `which egs_view` example1.egsinp 
```
works. For my needs this is a sufficient workaround. Thanks again!

**Comment by ftessier** [comment]
This is rather strange behavior. What does `type egs_view` report on your system?

**Comment by jw3126** [comment]
Yes I was using master from summer 2016 on this system without issues. Its an Ubuntu 16.04. But I had some qt issues and it might be, that qt version or path changed between the two installations. Maybe that is related to the above undefined symbol error.

```
admin@vm-ubuntu1404x64:~/EGSnrc/HEN_HOUSE/egs++$ type egs_view
egs_view is aliased to `(LD_LIBRARY_PATH=${HEN_HOUSE}egs++/dso/linux-static/ ${HEN_HOUSE}pieces/linux/egs_view_64)'
```
and 
```
admin@vm-ubuntu1404x64:~/EGSnrc/HEN_HOUSE/egs++$ which egs_view
/home/admin/EGSnrc/HEN_HOUSE/bin/linux64/egs_view
```

**Comment by ftessier** [comment]
Ok, the current egs_view alias is meant to simplify the use of pre-compiled binaries... Just unalias egs_view and it should work as expected, using your own compiled egs++ shared library objects. You definitely want bash to launch the one you compiled:  `/home/admin/EGSnrc/HEN_HOUSE/bin/linux64/egs_view`. 

I will close this issue, don't hesitate to re-open if needed.
