### ISSUE TITLE
Failure to find point inside cone stack

### ISSUE THREAD

**Issue by jw3126** [nrc-cnrc/EGSnrc#268]
Sometimes `egs_view` cannot find point inside `EGS_ConeStack`:
```
:start geometry definition:
    :start geometry:
        library = egs_cones
        type = EGS_ConeStack
        name = my_conestack
        axis = -1 0 0 1 0 0
        :start layer:
            thickness = 0.0417
            top radii = 0.
            bottom radii = 0.0858
            media = water
        :stop layer:
    :stop geometry:

    simulation geometry = my_conestack

:stop geometry definition:
```
If I change the origin part of axis, `egs_view` then everything is fine:
```
:start geometry definition:
    :start geometry:
        library = egs_cones
        type = EGS_ConeStack
        name = my_conestack
        axis = 0 0 0 1 0 0
        :start layer:
            thickness = 0.0417
            top radii = 0.
            bottom radii = 0.0858
            media = water
        :stop layer:
    :stop geometry:

    simulation geometry = my_conestack

:stop geometry definition:
```

**Comment by ftessier** [comment]
@jw3126 this is a known limitation of `egs_view`: if the geometry does not span the origin, egs_view often fails to find a point in the geometry. The viewer attempts to find the geometry by sampling a limited number of points around the origin on a fairly coarse grid. What would be needed instead is for every geometry object to be able to report it's bounding box in space; this is not implemented yet. 

In the mean time, you can define a bounding box in the input file to specify where the geometry is located. In the specific case you reportes, the following will solve the problem:
```
:start view control:
    xmin = -1
    xmax =  1
    ymin = -1
    ymax =  1
    zmin = -1
    zmax =  1
:stop view control:
```

**Comment by jw3126** [comment]
Thanks!
