### ISSUE TITLE
Error in compiling egs_view on Ubuntu 16.04

### ISSUE THREAD

**Issue by inamoto85** [nrc-cnrc/EGSnrc#273]
Hello EGSnrc developers,

I was configuring EGSnrc on a fresh install of Ubuntu 16.04, and the installation of the GUI programs worked smoothly till the `egs_view` compilation. Issuing command `make` in the `egs++/view` directory gives the following error:
```
   g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.. -I../../lib -I.moc -I.ui -o .obj/main.o main.cpp
In file included from ../egs_functions.h:35:0,
                 from ../egs_vector.h:41,
                 from .ui/ui_viewcontrol.h:63,
                 from viewcontrol.h:36,
                 from main.cpp:37:
../egs_libconfig.h:54:25: fatal error: egs_config1.h: No such file or directory
compilation terminated.
Makefile:264: recipe for target '.obj/main.o' failed
make: *** [.obj/main.o] Error 1

```
My compile tool versions are listed as follows:
```
make - GNU Make 4.1 built for x86_64-pc-linux-gnu
built-in gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
built-in g++ same as gcc
gfortran same as gcc
QMake version 2.01a Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
```
any help and suggestion is appreciated.

Thanks for your time!

**Comment by rtownson** [comment]
@mainegra might have some ideas?

Until then try using the pre-compiled GUIs distributed on the [release page](https://github.com/nrc-cnrc/EGSnrc/releases).

**Comment by crcrewso** [comment]
@rtownson I ran into the same errors, for QT4 when doing the QT5 migration work ( #263 ). I never did trace it, but I don't remember seeing it after defining QTDIR and QT_SELECT in bashrc.

**Comment by mainegra** [comment]
It seems the path to egs_config1.h is not known. This can only happen if EGSnrc was not properly configured. Proper configuration includes modifying the .bashrc resource file to setup the $EGS_CONFIG environment variable which points to the config file where $my_machine is defined. egs_config1.h is expected to be in $HEN_HOUSE/lib/$my_machine.
@inamoto85 maybe you tried to build the GUIs from the same shell console where you ran the configuration script (or GUI) and the .bashrc was either not updated or the update had not taken effect?
Can you confirm any of this?

**Comment by inamoto85** [comment]
@mainegra sorry for the delay, my output of the concerned environment is as follows:
```
inamoto@localhost:~/$ echo $my_machine
linux
inamoto@localhost:~/$ echo $HEN_HOUSE
/home/rwang/EGSnrc/HEN_HOUSE/
inamoto@localhost:~/$ echo $EGS_CONFIG
/home/rwang/EGSnrc/HEN_HOUSE/specs/linux.conf
```
the GUIs have been built given these environment variables and the `make` in egsview still gives the same error. Does this confirm your doubts? Plus I do not have problems in building other user codes with the `egs_libconfig.h` file dependency.

**Comment by katerinachytra** [comment]
Hi, I have the same problem on my ubuntu 16.04. It is not possible to use egs_view. The error is: `egs_view tracks1.egsinp
bash: syntax error near unexpected token `tracks1.egsinp'`

 The `make` command does not work in the  `~/EGSnrc/HEN_HOUSE/egs++/view$`
What should I do?

**Comment by mchamberland** [comment]
Can you post the output when you type make in the egs++/view directory? Also, can you post the content of the Makefile (just 'Makefile', not 'Makefile_${my_machine}').

**Comment by katerinachytra** [comment]
The output after typing make in the egs++/view directory:
`/bin/qmake my_machine=linux64 MAKEFILE=Makefile_linux64 hhouse=/home/katerina.chytra/EGSnrc/HEN_HOUSE/
make: /bin/qmake: Command not found
Makefile:40: recipe for target 'Makefile_linux64' failed
make: *** [Makefile_linux64] Error 127`

Makefile content:
include $(EGS_CONFIG)

all: Makefile_$(my_machine)
	$(gui_make) -f Makefile_$(my_machine) my_machine=$(my_machine) hhouse=$(HEN_HOUSE)

static: Makefile_static_$(my_machine)
	$(gui_make) -f Makefile_static_$(my_machine) my_machine=$(my_machine)

Makefile_$(my_machine): view.pro
	$(QTDIR)/bin/qmake my_machine=$(my_machine) MAKEFILE=Makefile_$(my_machine) hhouse=$(HEN_HOUSE)

Makefile_static_$(my_machine): view.pro
	$(QTDIR)/bin/qmake my_machine=$(my_machine) my_build=static MAKEFILE=Makefile_static_$(my_machine)  hhouse=$(HEN_HOUSE)

clean: Makefile_$(my_machine)
	$(gui_make) -f Makefile_$(my_machine) my_machine=$(my_machine) clean hhouse=$(HEN_HOUSE)

realclean: clean
	rm Makefile_*$(my_machine)

.PHONY: all clean

**Comment by katerinachytra** [comment]
The output after typing make in the egs++/view directory:
`/bin/qmake my_machine=linux64 MAKEFILE=Makefile_linux64 hhouse=/home/katerina.chytra/EGSnrc/HEN_HOUSE/
make: /bin/qmake: Command not found
Makefile:40: recipe for target 'Makefile_linux64' failed
make: *** [Makefile_linux64] Error 127`

Makefile content:
```
include $(EGS_CONFIG)

all: Makefile_$(my_machine)
	$(gui_make) -f Makefile_$(my_machine) my_machine=$(my_machine) hhouse=$(HEN_HOUSE)

static: Makefile_static_$(my_machine)
	$(gui_make) -f Makefile_static_$(my_machine) my_machine=$(my_machine)

Makefile_$(my_machine): view.pro
	$(QTDIR)/bin/qmake my_machine=$(my_machine) MAKEFILE=Makefile_$(my_machine) hhouse=$(HEN_HOUSE)

Makefile_static_$(my_machine): view.pro
	$(QTDIR)/bin/qmake my_machine=$(my_machine) my_build=static MAKEFILE=Makefile_static_$(my_machine)  hhouse=$(HEN_HOUSE)

clean: Makefile_$(my_machine)
	$(gui_make) -f Makefile_$(my_machine) my_machine=$(my_machine) clean hhouse=$(HEN_HOUSE)

realclean: clean
	rm Makefile_*$(my_machine)

.PHONY: all clean
```

**Comment by ftessier** [comment]
@katerinachytra's initial problem is due to the egs_view alias running the command in a sub-shell, therefore not allowing command-line arguments! This will be resolved imminently on the `develop` branch, once #370 is merged in. In the mean time, remove the parentheses in the egs_view alias definition in `$HEN_HOUSE/scripts/egsnrc_bashrc_additions`, as per f63733bbca55227f193d7a19d012cc8c0168fc17

**Comment by nkosie18** [comment]
Hello guys, I am having this problem when I try to run the make command in $HEN_HOUSE/egs++/view.

../egs_libconfig.h:54:10: fatal error: 'egs_config1.h' file not found
#include "egs_config1.h"
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [.obj/main.o] Error 1

here is my egsnrc_bashrc_additions..

 alias egs_view='LD_LIBRARY_PATH=${HEN_HOUSE}egs++/dso/linux-static/ ${HEN_HOUSE}pieces/linux/egs_view_64'
fi
# OS X specific settings
canonical_system=$( cat $EGS_CONFIG | grep "canonical_system =" | sed 's/canonical_system = //' )
is_darwin=$(echo $canonical_system | grep -i darwin)
if test ! "x$is_darwin" = x; then
    export DYLD_LIBRARY_PATH="${HEN_HOUSE}egs++/dso/$my_machine:${DYLD_LIBRARY_PATH}"
    launchctl setenv EGS_HOME $EGS_HOME
    launchctl setenv EGS_CONFIG $EGS_CONFIG
    alias egsgui='open -a egs_gui'
    alias egsinprz='open -a egs_inprz'

**Comment by rtownson** [comment]
@nkosie18 let me know if you did not solve this issue - I think Ernesto's comment from April 5th is revelant. I'm closing this issue since #370 has been merged.

**Comment by nkosie18** [comment]
hello everyone, I am trying to run the **make**  statement in the egs_gui directory but I am getting the following error.
f Makefile_ my_machine=
make: f: No such file or directory
