### ISSUE TITLE
How to run BEAMnrc in histories 30billions

### ISSUE THREAD

**Issue by kenjiyasue** [nrc-cnrc/EGSnrc#297]
I can't run BEAMnrc in histories 30 billion.
Could you teach me how to do that ?

**Comment by rtownson** [comment]
This is a question for the [google+ page](https://plus.google.com/communities/106437507294474212197).

The easiest way is to do many separate (e.g. parallel) runs, and combine the results. This avoids hitting system limits.

**Comment by crcrewso** [comment]
Does it work for 1.8 Billion? if so please see Issue #187
