### ISSUE TITLE
CD geometry errors when composed of cone stack and inscribed in cylindrical geometry

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#31]
I believe this may be related to issue #28: build a CD geometry whose base is planes and composed of a cone stack (two layers, different radii). Then, inscribe the CD geometry in a cylindrical phantom. Watch the geometry errors accumulate!

Attached below is a simple input file to run with `tutor7pp` and `tutor_data` PEGS file.

[cd_geom_errors.txt](https://github.com/nrc-cnrc/EGSnrc/files/92143/cd_geom_errors.txt)

**Comment by ftessier** [comment]
Indeed this issue is related to #28, and can be handled in the same way: remove numerical coincidence between surfaces (for example use `radii = 1.0001 5` for the phantom cylinder radii), and pad the cone stack radially to avoid kinks as seen from the outside.
