### ISSUE TITLE
Atomic relaxation method should be an input option

### ISSUE THREAD

**Issue by rtownson** [nrc-cnrc/EGSnrc#310]
The method and data to use for atomic relaxations should be an input option, rather than a macro in `egsnrc.macros`. This would allow for faster simulations without bound Compton in cases where is not relevant. Currently EADL relaxations are on by default, which requires bound Compton to be on.

**Comment by mainegra** [comment]
Making EADL relaxation an input option is the next obvious step. Meanwhile, one can use Klein-Nishina (KN) even when the EADL relaxation macro is on by setting the input key 'atomic relaxations' to OFF. This is what happens anyway when $EADL_RELAX is set to .false. and KN is used with 'atomic relaxations' set to ON. It doesn't make sense to want atomic relaxations with KN.

**Comment by mainegra** [comment]
Making EADL relaxation an input option is the next obvious step. 
Meanwhile, one can use Klein-Nishina (KN) even when the EADL relaxation macro is on by setting the input key 'atomic relaxations' to OFF. This is what happens anyway when `$EADL_RELAX` is set to `.false. `and KN is used with `'atomic relaxations' `set to ON. Although one still gets atomic relaxations from photoeffect and EII but not from Compton which is something in-between.
Physically, it doesn't make sense to want atomic relaxations with KN, the same way it doesn't make sense to have Rayleigh scattering with KN Compton.

**Comment by mainegra** [comment]
PR #322 addresses this issue.
