### ISSUE TITLE
Segfault with radionuclide source when region selection input is missing

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#313]
Trying out the radionuclide source example shown [here](http://nrc-cnrc.github.io/EGSnrc/doc/pirs898/classEGS__RadionuclideSource.html), I get a segmentation fault with `tutor7pp`. I haven't tried debugging it yet, but can someone try reproducing this? Attached is the input file.

[radionuclide.txt](https://github.com/nrc-cnrc/EGSnrc/files/1151512/radionuclide.txt)

**Comment by rtownson** [comment]
The seg fault is due to missing the `run control` block in your input file. Add run control with `ncase` and it works fine. Apparently the check I used for its existence didn't work.

However, `ncase` was used in the source for something that has since been removed, so this dependence/problem will disappear in the next iteration.

**Comment by mchamberland** [comment]
Oh wow! I blame the jet lag! -_-'

**Comment by mchamberland** [comment]
@rtownson I tried again (with a run control block this time!). Photons work, but requesting electrons or anything else segfaults. Am I missing something else?

[test1.txt](https://github.com/nrc-cnrc/EGSnrc/files/1153328/test1.txt)

**Comment by rtownson** [comment]
If you use region selection then it works. I'll look into fixing it so that it works without...

```
        geometry            = box
        region selection    = IncludeSelected
        selected regions    = 0
```

**Comment by rtownson** [comment]
Around `line 309` in `egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp`, you can fix this bug easily. I'll include this fix in the next iteration.

```
    if (edep > 0) {
        app->setEdep(edep);
        int ireg = geom->isWhere(x);
        app->userScoring(3, ireg);
    }
```

becomes
```
    if (edep > 0) {
        app->setEdep(edep);
        int ireg;
        if(geom) {
            ireg = geom->isWhere(x);
        } else {
            ireg = app->isWhere(x);
        }
        app->userScoring(3, ireg);
    }
```
