### ISSUE TITLE
Controversial information whether to use total or kinetic energies in BEAMDP

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#315]
When running BEAMDP on command line and requesting (3) (Derive spectral distribution from ph-sp data), at the point where number of energy bins and emin and emax are given, it says: "Emin should be the same as ECUT used in the simulation with BEAM"

but on the next line it says:
"Emin, Emax (in MeV, kinetic only)"

To my understanding ECUT should be total energy, but on the line below BEAMDP asks kinetic only. Which one is correct?

The same confusion (kinetic vs. total) applies also to documentation. I don't know about the GUI.

**Comment by ojalaj** [comment]
Actually now I'm quite confused. Please correct me, if I'm wrong, but isn't particle total energy used in many places with EGSnrc-based codes (e.g. E in normal phsp file, ECUT and energy values for various VRT techniques in input files), but kinetic energies are also used in many places (e.g. E of monoenergetic beam used as source, energy spectra (?), E in IAEA phsp file). The question is that what does BEAMDP actually print out, when I derive energy spectrum from an IAEA phsp file? Total or kinetic energy?

**Comment by rtownson** [comment]
After reviewing the code here is my understanding:

Yes, total energy is used for `E` in `.egsphsp` files and `ECUT`. Yes, kinetic is used in IAEA phase-spaces. However, in EGSnrc (and BEAMDP) when we read in an IAEA phase-space we add the rest mass to convert it to total energy.

In BEAMDP, it does correctly ask for the kinetic energy and treat the energy as such! After reading in a phsp electron, it subtracts the rest mass to get the kinetic energy. **_But you're right, BEAMDP should not tell you to use `ECUT` as your Emin_** - this appears to be a mistake.

So you should input the kinetic energy range you desire, and the output energy spectrum will also be in kinetic energy.
