### ISSUE TITLE
egs_view window greys out on OS X until you interact with it

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#32]
This affects the version of `egs_view` on the develop branch, on OS X (10.11.2).

The window where the geometry is rendered greys out when it gets focus or when the focus moves to the UI window. The geometry becomes visible if you interact with it by dragging, zooming, or if you use the reload button. I've uploaded a [screencast](https://dl.dropboxusercontent.com/u/21325205/egs_view_glitch_osx.mov) of the bug on my Dropbox account.

I'm using Qt 4.8.7.1

If you can't access the screencast, I've also uploaded it to [YouTube](https://youtu.be/YB1FZmNmMeE).

**Comment by ftessier** [comment]
I confirm this problem on Yosemite 10.10.5 as well. @mstoeckl, any chance you are able to pinpoint quickly the missing rerender trap on OS X?

**Comment by mstoeckl** [comment]
It might be that OS X handles repainting/buffering differently, and so needs full repaints, even if they do waste CPU. Does changing:

         bool wasRerenderRequested = rerenderRequested;

in `image_window.cpp` to

         bool wasRerenderRequested = true;

fix the issue?

**Comment by ftessier** [comment]
Indeed setting `bool wasRerenderRequested = true;` in `image_window.cpp` solves the problem in OS X, thank you, I will implement the fix.
