### ISSUE TITLE
Issue compiling egs_view on macOS Sierra

### ISSUE THREAD

**Issue by mb860** [nrc-cnrc/EGSnrc#325]
Hi EGSnrc Developers,

Hope this is the right place to post as Im a still a beginner to coding and Monte Carlo. I've had no issues with compiling and running both egs_gui and egs_inprz. However egs_view gives the following error when compiling:

`clang++ -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64 -o ../../bin/egs_view.app/Contents/MacOS/egs_view .obj/main.o .obj/egs_visualizer.o .obj/egs_track_view.o .obj/saveimage.o .obj/clippingplanes.o .obj/viewcontrol.o .obj/renderworker.o .obj/image_window.o .obj/moc_image_window.o .obj/moc_clippingplanes.o .obj/moc_viewcontrol.o .obj/moc_saveimage.o .obj/moc_renderworker.o   -F/usr/local/lib -L/usr/local/lib -L../dso/ -legspp -framework QtGui -L/usr/local/opt/openssl/lib -L/usr/local/Cellar/qt@4/4.8.7_2/lib -F/usr/local/Cellar/qt@4/4.8.7_2/lib -framework QtCore 
ld: library not found for -legspp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../../bin/egs_view.app/Contents/MacOS/egs_view] Error 1`

I have followed the installation wiki at each step where I have confirmed all prerequisites have been downloaded and installed successfully. These include:

make `GNU Make 3.81 built for i386-apple-darwin11.3.0`
gfortran `GNU Fortran (Homebrew GCC 7.1.0) 7.1.0`
gcc `Apple LLVM version 8.1.0 (clang-802.0.42)`
g++ `Apple LLVM version 8.1.0 (clang-802.0.42)`

After configuration of EGSnrc I ensured that my shell profile contained the following:

`export EGS_HOME=/Users/myusername/Desktop/EGSnrc/egs_home/`
`export EGS_CONFIG=/Users/myusername/Desktop/EGSnrc/HEN_HOUSE/specs/osx.conf`
`source /Users/myusername/Desktop/EGSnrc/HEN_HOUSE/scripts/egsnrc_bashrc_additions`

I have read through issues #254 and #255 and believe this is something similar. Being a novice I have tried to follow the suggested solutions as best as possible and I really hope I'm not beating a dead horse here! 

Prior to this error I had one similarl to #273 where the `egs_libconfig.h` was not being found but resolved this by placing a copy of the file into the directory `/Users/myusername/Desktop/EGSnrc/HEN_HOUSE/egs++/view` Perhaps this is causing my problem? 

Going back to the original error `ld: library not found for -legspp` I have been looking through files everywhere and going crazy looking for this and seeing if any pathways don't add up. In the file:
`/Users/myusername/Desktop/EGSnrc/HEN_HOUSE/egs++/view/view.pro ` 

there is the following lines of code: 

`LIBS += -L../dso/$$my_machine -Wl,-rpath,$$hhouse/egs++/dso/$$my_machine -legspp # Fixes path to library`
`#LIBS += -L$$hhouse/egs++/dso/$$my_machine -legspp   # Relies on LD_LIBRARY_PATH`

Being a novice I have trial and error'd many combinations of these codes and others I have randomly come across and quickly realised it is beyond me. All I can think is compiler is looking in the wrong place for the library but I dont know how to fix this. Perhaps it is an issue with the latest qt@4/4.8.7_2/ which was upgraded from the qt4 used prior?

I am now sitting on a clean version of EGSnrc again with none of my adjustments and have followed the installation wiki again perfectly. 

Any help in overcoming the `ld: library not found for -legspp` error would be greatly appreciated!

Thank you for your time!

ps. Probably worth mentioning also that trying the latest precompiled egs_view just gives

`dyld: Library not loaded: /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui Referenced from: /Users/myusername/Desktop/EGSnrc/HEN_HOUSE/egs++/view/egs_view Reason: image not found`

**Comment by mb860** [comment]
Probably worth mentioning also that trying the latest precompiled egs_view just gives 

`dyld: Library not loaded: /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui
  Referenced from: /Users/myusername/Desktop/EGSnrc/HEN_HOUSE/egs++/view/egs_view
  Reason: image not found`

**Comment by mchamberland** [comment]
The [Google+ community](https://plus.google.com/u/0/communities/106437507294474212197) would be better for this question I think, but since we're here: did you set the DYLD_LIBRARY_PATH environment variable to point to your `egs++/dso/your_machine` directory?

**Comment by mb860** [comment]
I believe so.

There's code within `egsnrc_bashrc_additions` (which is being sourced in the shell environment) which should point the `DYLD_LIBRARY_PATH` to `egs++/dso/your_machine` directory automatically.

Have tried doing manually too before compiling and still have same error.

Will head on over to google+ if this appears to be error on my part.

Thanks for prompt reply!

**Comment by mchamberland** [comment]
I guess this one is kinda obvious, but just to be sure: do you have a libegspp.dylib (or some other extension) file in your `egs++/dso/whatever` folder?

**Comment by mb860** [comment]
Valid question as I'm new to this!! 

That file is in there. I actually temporarily copied it across to the referenced qt lib directory and then  managed to compile with no errors.

However when opening egs_view it simply closes itself again straight away. Figured this was happening because i'm probably not supposed to compile it with the  libegspp.dylib in my qt lib directory. 

Thanks again :)

**Comment by mchamberland** [comment]
The NRC developers will probably close this tomorrow since egs_view definitely compiles on macOS Sierra: I compiled it last month! ;)    So post on the Google+ EGSnrc community and we'll pick up from there.

**Comment by mb860** [comment]
Alrighty Cheers! Thanks again so much for your time mchamberland!

**Comment by crcrewso** [comment]
I'm reading the original post. It looks like you're compiling egs_view with clang++ not g++. As I've been doing a lot of compiler testing recently I'd like to know how it came to be that your make file injected clang++ as the CXX variable. 

As a sidenote, clang without flang is a guaranteed fail, and since flang is extremely new I'd suggest no one go down the clang road just yet.

**Comment by mb860** [comment]
Hi Crcrewso!!

Thanks for taking the time to read and get back to me. 

To be honest i'm not sure how to make it compile with g++ instead. I *think* its related to the version of QT that i'm using,

where it seems to target `/usr/local/Cellar/qt@4/4.8.7_2/etc/qt4/mkspecs/unsupported/macx-clang-libc++/qmake.conf when running qmake. ` 

The makefile uses $QTDIR which we set to whichever copy of QT is installed.

At least this is to the best of my understanding. If it were a simple fix, would you have any suggestions? 

I apologise for raising this here, its just that in the wiki it gives to run the command `brew install cartr/qt4/qt` which for me gives the qt@4/4.8.7_2/. 

If you believe this should not be causing this issue and its more to do with my setup and lack of knowledge, I understand if this is just simply closed. Also I apologise for taking up your time if this is the case.

**Comment by ftessier** [comment]
Hi @mb860, thank you for reporting this issue. The Qt4 package has indeed been upgraded in homebrew, so there is room for some problems. On a standard macOS install, g++ indeed uses clang++ under the hood (type `g++` in the Terminal); so this is not the problem as long as you selected `g++` during the EGSnrc configuration. I tried just now to compile egs_view on a fresh EGSnrc clone on macOS Sierra 10.12.4 and it fails but for another reason `QMAKESPEC has not been set`. I am looking into it.

**Comment by ftessier** [comment]
@mb860 can you try installing `brew install cartr/qt4/qt-legacy-formula` and `export QTDIR=/usr/local/Cellar/qt-legacy-formula/4.8.7_3/` before compiling egs_view from a freshly cloned and configured EGSnrc? I was able to compile it this way; something is not quite right when using `qt@4` (although the problem it seems unrelated to your original issue) to generate the Qt Makefile. At any rate, let us know what happens with `qt-legacy-formula`.

**Comment by mb860** [comment]
Hi @ftessier, thank you for looking into this! 

I definitely selected g++ during configuration and has 'YES' and 'OK' for all tests that it does. Seemed to configure ok. Also did notice that qt@4 had issues with the $QMAKESPEC and wasn't sure what to do. Tried manually setting this to macx-g++ but ran into new errors. 

Unfortunately I haven't installed any previous versions of qt4 and from what I can tell brew now just uses a placeholder for the qt-legacy-formula (previously just called 'qt') in which the 4.8.7_3 is *not* there for me. Running `brew install cartr/qt4/qt-legacy-formula` seems to just install qt@4 and the `qt-webkit@2.3`. I think maybe they now just focus on qt5. Although a `qt-legacy-formula` directory is created it contains just an empty placeholder. 

I should probably mention I can no longer repeat my original issue and I think it was related to using homebrew to install gcc, gfortran etc. I think the symlinks caused issues finding libraries but i'm not sure. At this point i'm just stuck getting it to compile and generate qt make file with qt@4.

Thanks again! :)

**Comment by ftessier** [comment]
@mb860, if I understand correctly, as far as you know, your original linking problem is no longer an issue (or you don't know because you can't even compile egs_view)? I will leave this issue open because of the qt@4 `QMAKESPEC` undefined bug.

**Comment by ftessier** [comment]
I was finally able to compile egs_view as expected with qt@4 by removing earlier qt kegs:
```
brew uninstall qt
brew uninstall qt-legacy-formula
brew link qt@4
```
However the `open -a egs_view` does not work anymore, one has to launch the executable using the full path `$HEN_HOUSE/bin/macos/egs_view.app/Contents/MacOS/egs_view`.

**Comment by mb860** [comment]
Thanks for your help! 

It compiles successfully now. As you say by removing the legacy formula.

As a side note, many of my errors occurred from installing gcc related things on brew in the past. There turned out to be some conflicting files. Not exactly sure why but cleaning up worked. 

Just want to apologise for taking up your time on this one. I should've been more certain of a bug before commenting here.

**Comment by ftessier** [comment]
No worries, glad you got it working. Thank you for taking the time to report and investigate the problem, it is very useful to know when things don't work as expected, and why!

**Comment by nkosie18** [comment]
Failing to run the make command in the egs_gui,
 I am getting the error: f Makefile_ my_machine=
make: f: No such file or directory.

**Comment by hukui4860** [comment]
> I was finally able to compile egs_view as expected with qt@4 by removing earlier qt kegs:
> 
> ```
> brew uninstall qt
> brew uninstall qt-legacy-formula
> brew link qt@4
> ```
> 
> However the `open -a egs_view` does not work anymore, one has to launch the executable using the full path `$HEN_HOUSE/bin/macos/egs_view.app/Contents/MacOS/egs_view`. Leaving the issue open to remind myself to update the wiki.

You means that it can't works for egs_view compilation if I brew cart/qt4/qt,  because of mac automatically install qt-legacy-formula?  As you said, if I have performed brew cart/qt4/qt,  and I unistall qt and qt-legacy-formula,  then brew link qt@4,  I will make egs_view. app successfully?

**Comment by hukui4860** [comment]
[brew link qt@4.pdf](https://github.com/nrc-cnrc/EGSnrc/files/5430365/brew.link.qt%404.pdf)
I have do as what you said :
brew uninstall qt
brew uninstall qt-legacy-formula
brew link qt@4
Then I follow the wiki to compile the egs_gui successfully, but there is  error during compiling egs_inprz: src/inputRZImpl.cpp:473:59: error: ordered comparison between pointer and zero
      ('const void *' and 'int')
  if ( wish.count() > 0 && wish.contains((QString)"wish") > 0 )
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
1 error generated.

**Comment by hukui4860** [comment]
And then I uninstall qt, and  remove all qt files:
caiqian890307@hk ~ % rm -rf /usr/local/Cellar/qt@4 
caiqian890307@hk ~ % cd /usr/local/Cellar 
caiqian890307@hk Cellar % ls
openssl@1.0 qt-webkit@2.3
caiqian890307@hk Cellar % rm -rf /usr/local/Cellar/qt-webkit@2.3 
caiqian890307@hk Cellar % ls
openssl@1.0
caiqian890307@hk Cellar % cd
caiqian890307@hk ~ % brew install qt

Then brew install qt for qt-5.15.1.catalina.bottle.tar.gz
Then I follow the wiki to compile the egs_gui successfully, but there still is an error during compiling egs_inprz: 
include/ui_inputRZ.h:46:10: fatal error: 'QtGui/QAction' file not found
#include <QtGui/QAction>
^~~~~~~~~~~~~~~
include/ui_inputRZ.h:46:10: note: did not find header 'QAction' in framework 'QtGui' (loaded from '/usr/local/Cellar/qt/5.15.1/lib')
1 error generated.
[brew install qt.pdf](https://github.com/nrc-cnrc/EGSnrc/files/5430426/brew.install.qt.pdf)

**Comment by hukui4860** [comment]
Finally, I failed to compile the gui. Sincerely, I need your suggestion about my stuck in install EGSnrc. Looking forward your messages!

**Comment by ftessier** [comment]
Migrated to #704.

**Comment by ftessier** [comment]
Please consult the updated [macOS installation instructions](https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS), which are known to work on macOS 11 (Big Sur), and report any outstanding or further issue in #704.
