### ISSUE TITLE
Cannot open .egsdat file for writing if using .egsinp on command line argument

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#330]
This is a side effect from commit f93aa70effd3abae98ad6133e91445d5322f23fa.

If one leaves the `.egsinp` extension on the command line argument, then `outputData()` tries to open a `.egsdat` file with the double extension `.egsinp.egsdat`.

From `tutor7pp` with the example `test1.egsinp` file:

```
>tutor7pp -i test1.egsinp
(...)
EGS_Application::outputData: failed to open /Users/Marc/clrp/egs_home/tutor7pp/egsrun_10038_test1.egsinp_Moridin.local/test1.egsinp.egsdat for writing
```

**Comment by ftessier** [comment]
Indeed, we have to strip the `.egsinp` extension on the egs++ side as well! We'll fix this as soon as possible. Thanks.
