### ISSUE TITLE
EGSnrc not installing

### ISSUE THREAD

**Issue by nk-1848** [nrc-cnrc/EGSnrc#335]
Tried to install the EGSnrc from the zip, when starting the installation via EGSnrc-configure-Windows, keep getting  EGSnrc installation FAILED, see log file for details

The first error that appears is:

===> Creating C Utilities for EGSnrc...

Building the utilities object file ... 

Could egs_c_utils.c be compiled? .......................... no 
Could load_beamlib.c be compiled? ......................... no 
Could load_vculib.c be compiled? .......................... no 
Could read_write_pardose.c be compiled? ................... no 

Failed to compile egs_c_utils.c. This may be due to a variety of reasons
(e.g. non-standard include files, unsupported file lock operations, etc.
Will disable now the availability of a C compiler. 

And after that it all snowballs from there. Just to double check, I tried to call up all of the compilers (gfortran, g++, gcc) on cmd, works just fine, wingw32-make also gives me the installed version when prompted in cmd. I downloaded the EGSnrc-configure-windows.exe from the 2017 release, go through the "Typical" installation process, and once I hit the "Install" button, it finishes in 5 seconds with the FAIL message. I am attaching the full error message, as well as the config log, in case it might be any help. 
[full error message.txt](https://github.com/nrc-cnrc/EGSnrc/files/1264364/full.error.message.txt)
[config flie from logs.txt](https://github.com/nrc-cnrc/EGSnrc/files/1264368/config.flie.from.logs.txt)

**Comment by crcrewso** [comment]
First thing I'd try is to rename 'New Folder' to something without a space. I have a sneaking suspicion that the issue has to do with mingw and space handling.

**Comment by nk-1848** [comment]
Surprisingly enough, deleting the space actually worked. Thanks, **crcrewso**, saved me tons of trouble and combing through code.

**Comment by crcrewso** [comment]
@nk-1848 in the future there is a google group for this kind of question. 

@ftessier I think we can mark this one closed due to mingw being an incomplete compiler (again)
