### ISSUE TITLE
Fuzzy boundaries

### ISSUE THREAD

**Issue by Kawrakow** [nrc-cnrc/EGSnrc#345]
Not having fuzzy boundaries was a primary design goal of the egs++ geometry package. I see fuzzy boundaries are now "baked-in". There was no other way? 1e-5 (the single precision fuzziness) is larger than the range of low energy electrons in high density materials. Even 1e-7 (the double precision fuzziness) can be too large under specific circumstances.

**Comment by ftessier** [comment]
@Kawrakow, the primary design goal has not changed a bit. Boundary tolerances (fuzzy boundaries) were not added systematically, but only in cases where the existing geometry were plagued by a large number of geometry errors. This is a mitigation measure until the original goal can be recovered algorithmically.

An `epsilon` value of 1e-10 was added to curb floating point comparison errors, and by default the `boundaryTolerance` threshold is set equal to `epsilon`, and can be configured by input.
