### ISSUE TITLE
EGSnrc guis "Go" button fails when make_prog variable includes arguments

### ISSUE THREAD

**Issue by ftessier** [nrc-cnrc/EGSnrc#346]
When the `.conf` configuration file `make_prog` variable contains extra flags (or spaces), these don't get parsed properly by the `ironIt` method in `egs_config_reader.cpp`. This causes compilation to hang when hitting the `Go` button in the guis to compile applications. This is an issue because the current configuration script sets `make_prog = make -j12`. Perhaps replace the legacy `ironIt` method with functionalities of `QDir` or `QString`?

**Comment by rtownson** [comment]
This was fixed in PR #440.
