### ISSUE TITLE
Incorrect density for RW-1 water substitute in density corrections file

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#347]
In HEN_HOUSE/pegs4/density_corrections/compounds/rw-1watersubstitute_polyethenebased.density the density of the material is 9.6999998. Should it be 0.96999998?

**Comment by ftessier** [comment]
Most probably, of course!! Can anybody provide a reference on this particular material? It would be nice to confirm the numerical value as well.

**Comment by ftessier** [comment]
We have to check the actual density correction values of course, not just the density value in the header.

**Comment by ojalaj** [comment]
I went through the density correction files trying to find one suitable for RMI SW and came across this one. Unfortunately I don't have further experience using it or information about it, but after some Google search, in http://iopscience.iop.org/0031-9155/60/24/9403 and in the reference therein there is some supporting information.

**Comment by ftessier** [comment]
The density effect correction values in the `rw-1watersubstitute_polyethenebased.density` themselves do correspond to the (wrong) density of 9.6999998 instead of 0.96999998. I am preparing a new file with the correct data.
