### ISSUE TITLE
DOSXYZnrc Source 20 simulations in pegsless mode do not work

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#349]
I've started using pegsless mode. Simulations with traditional PEGS files work OK, i.e. I get:
```
About to initialise BEAM code..
 In beamlib_init!
 i_par =            0
hen_house = /home/EGS2017d/HEN_HOUSE/
egs_home  = /home/BEAM2017/
beam_code = MY_CODE
inputfile = MY_INPUT_FILE
pegs file = /home/EGS2017d/HEN_HOUSE/pegs4/data/521icru.pegs4dat
```

But in pegsless mode I get:
```
About to initialise BEAM code..
 In beamlib_init!
 i_par =            0
hen_house = /home/EGS2017d/HEN_HOUSE/
egs_home  = /home/BEAM2017/
beam_code = MY_CODE
inputfile = MY_INPUT_FILE
pegs file =

***************** Error:
 could not find pegs4 file named

***************** Quiting now.
```

The BEAM code input file that is used as shared library has the required lines (as does the DOSXYZ input file), i.e.,
```
:start media definition:
    ae = 0.521
    ue = 50.511
    ap = 0.01
    up = 50

material data file=/home/EGS2017d/HEN_HOUSE/pegs4/data/material.dat

:stop media definition:
```

**Comment by ftessier** [comment]
We were just wondering today about pegsless mode for BEAMnrc loaded as a shared library. @blakewalters is this implemented yet?

**Comment by blakewalters** [comment]
Try inputting "pegsless" as the name of the pegs file for the simulation source...

**Comment by ojalaj** [comment]
Hmm, I'm not sure what you mean - I try to run the simulation with command "ex dosxyznrc MY_INPUT_FILE pegsless" and both input files (dosxyz input and beam input that is used as shared library contain those lines mentioned in my original post).

**Comment by blakewalters** [comment]
Ah, okay.  Are you using source 20 with a BEAM shared library geometry?  In this case, I can see a bug where the pegsless status of your dosxyznrc run isn't passed on correctly to the shared library...

**Comment by ojalaj** [comment]
Yes, that is the case.

**Comment by blakewalters** [comment]
Fix on the way...
