### ISSUE TITLE
Infinite looping when using beam source in egs_chamber

### ISSUE THREAD

**Issue by pgfwatso** [nrc-cnrc/EGSnrc#351]
I found that while running a BEAM shared library source in egs_chamber, I was getting an infinite loop (simulation would never finish, even with only 1 history).

After some sleuthing, my colleage Marc-Andre Renaud and I found that in egs_beam_source.cpp, there is a sanity check where the particle energy must be less than Emax:
       `  if (te > Emax) {
          ok = false;
      } //egsInformation("Emax rejection\n"); }`

We determined that if te equals Emax,  it can still fail the inequality te > Emax because of some funny business in comparing floating point numbers. This would occur for any particles in your beam model which have Emax and do not interact (i.e. their energy remains Emax).

Our workaround for this was to change the if statement to if (te > 1.01*Emax), but the more elegant solution would be to implement a robust, float rounding error proof comparison such as the epsilon constant.

**Comment by rtownson** [comment]
Please confirm that PR #351 fixes this. Thanks for reporting it!

**Comment by vahx129** [comment]
Nice find! This likely explains the behavior I reported in a separate thread: 
https://github.com/nrc-cnrc/EGSnrc/issues/108

Of course I didn't do the requisite sleuthing to figure out why the simulation was hanging. Unfortunately I still do run into an issue where initializing 30 BEAM sources with parent phase spaces still crashes in egs_chamber as reported here: 
https://github.com/nrc-cnrc/EGSnrc/issues/311

Either way thanks for investigating this issue! I'm excited to see progress being made.
