### ISSUE TITLE
"wrong/missing 'nuclide' input" when attempting to use EGS_RadionuclideSource.

### ISSUE THREAD

**Issue by ztparsons** [nrc-cnrc/EGSnrc#361]
I was originally attempting to use the EGS_RadionuclideSource in the `egs_brachy` for a beta plaque source which resulted in the following error dialog:

```
EGS_BaseSpectrum::createSpectrum: Initializing radionuclide spectrum...
EGS_BaseSpectrum::createSpectrum: wrong/missing 'nuclide' input
EGS_RadionuclideSource: Error: No spectrum was defined
```

I then attempted to use the example found in the EGSnrc C++ class library [here](http://nrc-cnrc.github.io/EGSnrc/doc/pirs898/classEGS__RadionuclideSource.html) in `tutor7pp` and proceeded to get the same error as I did in `egs_brachy`. 

I noticed in the */spectra/lnhb/ensdf/ that the isotopes were in .txt format instead of .ensdf as the documentation for [EGS_RadionuclideSpectrum](http://nrc-cnrc.github.io/EGSnrc/doc/pirs898/classEGS__RadionuclideSpectrum.html) suggests they should be. I tried changing the format, but still get the same error.

**Comment by mchamberland** [comment]
That's because the documentation is out of date. You should replace the `isotope` key value in the `spectrum` input block by `nuclide` instead.

**Comment by rtownson** [comment]
The online documentation is up to date with the `master` branch. If you are using the `develop` branch, then you need to build the documentation yourself. If you have doxygen installed, you can do this in `$HEN_HOUSE/doc/src` by typing `make pirs898-egs++`
