### ISSUE TITLE
Uncertainty calculation in Dosxyznrc and definition of shower

### ISSUE THREAD

**Issue by ShiqinSu** [nrc-cnrc/EGSnrc#371]
I am trying to manually calculate the uncertainty (endep2) for 3ddose and follow the exact same code as dosxyznrc.mortran: 
```
IF(nhist_last = endep_last(ir(np)-1))[
       "same shower that deposited energy last time in this region"
       endep_tmp(ir(np)-1) = endep_tmp(ir(np)-1) + edep*wt(np);
  ] 
  ELSE["we have the next shower depositing energy into region ir(np)"
         " => put endep_tmp into  the scoring arrays and set endep_last"
       endep(ir(np)-1)=endep(ir(np)-1)+endep_tmp(ir(np)-1);
       endep2(ir(np)-1)=endep2(ir(np)-1) +
                         endep_tmp(ir(np)-1)*endep_tmp(ir(np)-1);
       endep_tmp(ir(np)-1) = edep*wt(np);
       endep_last(ir(np)-1)=nhist_last;
  ]
```
The above code suggests that endep2 is only summed up for distinctive shower. However, I end up with different endep2 values compared to what the code gives me. Anyone has done such calculation before or has any idea about this will be appreciated. Furthermore, anyone knows about how is the term 'shower' defined?

**Comment by ftessier** [comment]
This part of the code relates to the "history-by-history" technique for estimating statistical uncertainty. Refer to the [DOSXYZnrc user manual](http://nrc-cnrc.github.io/EGSnrc/doc/pirs794-dosxyznrc.pdf) Section 2.3,or the [original paper](http://onlinelibrary.wiley.com/doi/10.1118/1.1517611/full) for a detailed explanation. Please consider posting such questions on the [Google+ community](https://plus.google.com/communities/106437507294474212197) and reserve this space for demonstrated issues with the EGSnrc code.
