### ISSUE TITLE
Application "g" does not output mass energy absorption coefficients for large numbers of histories

### ISSUE THREAD

**Issue by Lotte1990** [nrc-cnrc/EGSnrc#373]
When I increase the number of particles from 10M to 500M, the mass energy absorption coefficient disappears from the G output. See attached comparison of the outputs.
![screenshot at 2017-09-28 19 36 14](https://user-images.githubusercontent.com/26183319/32487107-0244a054-c3a9-11e7-8a47-00cdf414b5bb.png)

**Comment by rtownson** [comment]
Let me know if PR #374 fixes this for you!
