### ISSUE TITLE
g missing pegsless includes in makefile

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#380]
When I try running `g` in pegsless mode, I get the following message:

```
  PEGSLESS INPUT.  CALCULATING ELECTRON CROSS-SECTIONS.

***************** Error:
 Code cannot be run in pegsless mode.
 Compile with required files and try again.
```

It appears `pegs4_macros.mortran`, `pegs4_routines.mortran`, and `get_media_inputs.mortran` are not included at compile. Should be an easy fix?

**Comment by mchamberland** [comment]
Thanks for the quick fix!

**Comment by NoureenR** [comment]
I am trying to g_template input file by EGSnrc GUI, I am getting this error message
At line 1022 of file g_win6432.f (unit = 9)
Fortran runtime error: Cannot open file '$HEN_HOUSE/spectra/co60.spectrum': No such file or directory
Also, I want to know how can I change source input to monoenergetic source with 1 MEV.
In egs_kerma code, a file emuen_icru90_1.5MeV is created by using g code, can somebody help me with the input file to recreate this data.
I am starter for this code. I appreciate if somebody can help me fix this.  
Thanks

**Comment by NoureenR** [comment]
Correction to the above comment:
I need some help with the user code g, I am using EGSnrcGUI to execute the input file g_template and getting the error message:
At line 1022 of file g_win6432.f (unit = 9)
Fortran runtime error: Cannot open file '$HEN_HOUSE/spectra/co60.spectrum': No such file or directory
