### ISSUE TITLE
INDEX(I) for synchronized CMs and DOSXYZ s20&s21 muIndex(i)

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#390]
This could have been sent to Google+ too, but in case the code works as expected, the documentation could be improved. So the case is that I'm simulating a 'step&shoot' treatment plan and I'm wondering what is the correct way to do it (since I got weird results). I've a script that converts the jaws and MLC plan data to the sequence format required by EGS. PIRS509 says that INDEX(I)>INDEX(I-1) i.e. the index should be increasing. Anyhow, the code doesn't warn at all or produce an error, if the previous condition is not fulfilled - should it give a warning/error? I've used sequence file in following format (without any errors or warnings), e.g. for jaws:
0.00000
27.66762, 35.46494, 5.53352, 7.09299, -0.00000, -0.00000,
36.05647, 43.90804, 3.64170, 4.43471, -1.22592, -1.49287,
0.1307 (THIS IS THE FIRST OPENING, BETWEEN 0.00000 and 0.1307 )
27.66762, 35.46494, 5.53352, 7.09299, -0.00000, -0.00000,
36.05647, 43.90804, 3.64170, 4.43471, -1.22592, -1.49287,
0.1307
27.69589, 35.50117, 5.23452, 6.70972, -0.00000, -0.00000,
36.05647, 43.90816, 1.18986, 1.44897, -3.64170, -4.43472,
0.2764 (THIS IS THE SECOND OPENING, BETWEEN 0.1307 and 0.2764 )
27.69589, 35.50117, 5.23452, 6.70972, -0.00000, -0.00000,
36.05647, 43.90816, 1.18986, 1.44897, -3.64170, -4.43472,
0.2764
27.89330, 35.75421, -0.00000, -0.00000, -2.25936, -2.89609,
36.05647, 43.90185, 2.88452, 3.51215, -3.24508, -3.95117,
0.3869 (THIS IS THE THIRD OPENING, BETWEEN 0.2764 and 0.3869)
27.89330, 35.75421, -0.00000, -0.00000, -2.25936, -2.89609,
36.05647, 43.90185, 2.88452, 3.51215, -3.24508, -3.95117,
....

However PIRS794 says that muIndex(i) ≥ muIndex(i-1), i.e. successive indeces don't need to increase. 

9.643, 4.100, 13.900, 90, 214.10, 270, 100.0, 0.0000
9.643, 4.100, 13.900, 90, 214.10, 270, 100.0, 0.1307
9.643, 4.100, 13.900, 90, 238.10, 270, 100.0, 0.1307
9.643, 4.100, 13.900, 90, 238.10, 270, 100.0, 0.2764
9.643, 4.100, 13.900, 90, 37.10, 270, 100.0, 0.2764
9.643, 4.100, 13.900, 90, 37.10, 270, 100.0, 0.3869
...

So the actual question is that how does the code work with sequences described above. i.e., if the INDEX is not increasing? E.g. for the jaws if RND is 0.1306, which coordinates from above are chosen? I assume that the coordinates for the 'first opening'? And correspondingly, if RND is e.g. 0.25, the coordinates for the 'second' opening? The reason I've used sequence files like this is that in this way I can always use 'dynamic' mode for the jaws and MLC - in the case of 'step&shoot' plans the 'openings' correspond to fields and 'dynamic' plans to control points.

**Comment by rtownson** [comment]
You are using it correctly to create static fields: muIndex(i) ≥ muIndex(i-1). The PIRS-509 documentation should be updated!

**Comment by marenaud** [comment]
The code for SYNCJAWS field selection is [here](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/omega/beamnrc/CMs/SYNCJAWS_macros.mortran#L208)

For fun, I just did a little python script where I reproduced the syncjaws binary search to play around and confirm that it works as intended.

```
def binary_search(rnd, indices):
    """
    Binary search as implemented by SYNCJAWS, with 0 indexed arrays instead.
    """

    if rnd < indices[0]:
        bimax = 0
    else:
        bimin = 0
        bimax = len(indices) - 1

        while bimin < bimax - 1:
            bimid = bimin + (bimax - bimin) / 2
            if indices[bimid] >= rnd:
                bimax = bimid
            else:
                bimin = bimid

    return bimax

def test_syncjaws():
    indices = [0.0, 0.1307, 0.1307, 0.2764, 0.2764, 0.3869]

    # rnd of 0.0 should return index 1 for proper interpolation
    assert(binary_search(0.0, indices) == 1)

    assert(binary_search(0.1, indices) == 1)
    assert(binary_search(0.1307, indices) == 1)

    assert(binary_search(0.2, indices) == 3)
    assert(binary_search(0.2764, indices) == 3)

    assert(binary_search(0.3, indices) == 5)
    assert(binary_search(0.3869, indices) == 5)

if __name__ == "__main__":
    test_syncjaws()
```

**Comment by ojalaj** [comment]
@rtownson & @marenaud - thank you for your confirmation. With this info I can now search for the reason(s) for the dose discrepancies from elsewhere.
