### ISSUE TITLE
Wrong check on input dimension of quarter iso leaves for SYNCHDMLC?

### ISSUE THREAD

**Issue by marenaud** [nrc-cnrc/EGSnrc#393]
It seems to me like [this line](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran#L1784) should be
``
IF(ZGROOVE_$SYNCHDMLC(5)<ZTONGUE_$SYNCHDMLC(5))[
``
instead of the current
``
IF(ZGROOVE_$SYNCHDMLC(5)>ZTONGUE_$SYNCHDMLC(5))[
``

If quarter leaves are treated identically to half leaves. The error message for the failed check also indicates that ZGROOVE < ZTONGUE is the intended check instead of ZGROOVE > ZTONGUE.

See [this line](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran#L1554) for the dimension check of half iso leaves

**Comment by marenaud** [comment]
Upon reviewing some dimensions, it may not be a bug. The quarter leaves do seem to be slightly different from half leaves. Now I'm wondering if the check is even needed?

**Comment by marenaud** [comment]
There's a possibility that the quarter leaves are in fact different than the half leaves, but from what I can see in the code, half iso leaves are treated exactly the same way as quarter iso leaves, so maybe the check isn't even needed?

**Comment by blakewalters** [comment]
Hi @marenaud:

For the quarter isocentre leaves, ZGROOVE is actually < ZTONGUE, as originally coded and in accordance with any documentation for the HD120 that I can find online.   So, yes, I'll need to change the error output to reflect what's actually being checked.  Also, the figure in the BEAMnrc Manual is wrong!  Thanks for spotting this.

**Comment by marenaud** [comment]
Hi @blakewalters 

Looking at the documentation offered by Varian for the HD120, it seems like there could be a mistake specifically in the quarter iso leaves (the picture hints that they might have mixed up ZGROOVE and ZTONGUE). Do you have an email address where I can send a screenshot illustrating what I think is the mistake? I'd rather not attach it to this issue since it comes from their proprietary data package.
