### ISSUE TITLE
EGSnrc configuration asks to select compiler and then install crashes

### ISSUE THREAD

**Issue by TadyZ** [nrc-cnrc/EGSnrc#408]
Hi,

The egsnrc-configure-windows.exe asks to select compiler. It seems that this option didn't exist in previuos versions, at least in the one that is in Installation guide.  I pick compilers from C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin. **gcc.exe** for C, **g++.exe** for C++, **gfortran.exe** for fortran and **mingw32-make.exe** for make. Install crashes at 52%. Log:

 

> Using xml test file E:\MedFiz\EGSnrc\HEN_HOUSE\pieces\tests_win.xml
> 
>  ===>   Checking for availability of system dependent functions 
> 
> 
> Can the compiler produce object files? .................... no 
> Can the compiler produce executables? ..................... no 
> Does "exit" or "exit_" work properly? ..................... no 
> Does "stop" function work properly? ....................... no 
>  Compiling "egs_exit.c" since "exit" and "stop" failed ?... no 
> Does "egs_exit" function work properly? ................... no 
> Does the "system" function return an exit status ? ........ no 
> Does the "system" subroutine return an exit status ? ...... no 
> Is "flush" or "flush_" available? ......................... no 
> Is the "date_and_time" subroutine available ? ............. no 
> Is "fdate" or "fdate_" subroutine available? .............. no 
> Is "secnds" or "secnds_" function available? .............. no 
> Is "date" or "date_" subroutine available? ................ no 
> Is "time" or "time_" subroutine available? ................ no 
> Is "etime" or "etime_" function available? ................ no 
> Is function "lnblnk" available? ........................... no 
> Does "hostnm" or "hostnm_" work properly? ................. no 
> Is "lstat" available and does it work properly? ........... no 
> Does "inquire" work properly? ............................. no 
>  Compiling a C program to find out the file size ?......... no 
> Is record length known? ................................... no 
> Is "integer*8" available? ................................. no 
> Is "integer*2" available? ................................. no 
> Can endianess of machine be determined?.................... no 
>  Compiling a C program to find out the name mangling scheme ? no 
> Is the name mangling scheme known ?........................ no 
> 
> ************              Tests concluded !          *******
> 
> 
> ===> Creating C Utilities for EGSnrc...
> 
> 
> WARNING:
> ========
> No C compiler passed to the configuration process.
> C utilities for parallel runs and BEAM source engine
> will not be available for this configuration!!!
> 
> 
> 
> ===> Creating configuration file ...
> 
> 
> 
> ===> Creating machine.macros ...
> 
> 
> 
>  *** System file E:\MedFiz\EGSnrc\HEN_HOUSE\lib\win6432\machine.macros successfully created ***
> 
> 
> 
> ===> Creating machine.f ...
> 
> 
> Error copying egs_fdate_v3.f
> 
> ===> Creating machine.mortran ...
> 
> 
> 
>  *** System file E:\MedFiz\EGSnrc\HEN_HOUSE\lib\win6432\machine.mortran successfully created ***
> 
> 
> ===> Creating dosxyznrc_win6432.spec ...
>  failed 
> 
> Failed creating dosxyz_win6432.spec
> file. You will not be able to use 
> DOSXYZnrc for in-phantom dose calculations.
> 
> ===> Appending VCU library to dosxyznrc_win6432.spec ...
> 
> ===> Compiling Mortran3 ...
> 
> 
> Error executing makeEGS_CONFIG=E:\MedFiz\EGSnrc\HEN_HOUSE\specs\win6432.conf

Did i pick wrong compilers?

**Comment by CuteCurry** [comment]
Hi, I have the exactly same crash, did you solve it?

**Comment by CuteCurry** [comment]
I have solved it, run the configuration as administrator

**Comment by TadyZ** [comment]
Hi,

I was selecting wrong folder in system variables, that's why installer
asked to select compilers.

Also pay attention when naming your folders, EGSnrc doesn't like spaces in
folder names.

**Comment by rtownson** [comment]
Glad you solved this. In the future this is a question ideal for the [google+ community](https://plus.google.com/communities/106437507294474212197)!
