### ISSUE TITLE
Installation problem with egs_cbct: entry point not found

### ISSUE THREAD

**Issue by povolann** [nrc-cnrc/EGSnrc#410]
Hi,

when I try to run code: `egs_cbct -i blank_head.engsinp -p fax06` it gives me error: 

> The procedure entry point _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcjj could not be located in the dynamic link library C:\EGSnrc\EGS_HOME\bin\Anya_win64\egs_cbct.exe

I guess the problem is with my mingw64, but I don't know what it is. Can you help me with this problem?

**Comment by rtownson** [comment]
This problem is likely better suited to the [google+ community](https://plus.google.com/communities/106437507294474212197).

Did you figure it out?

**Comment by povolann** [comment]
I googled this error, asked some people and I tried something what they suggested to me, but it didn't help. So I installed Ubuntu on my notebook and I use EGSnrc without problems on Ubuntu :-)

**Comment by gkmgkm007** [comment]
Hi, 

I do have the similar problem. But I can not get rid of Window system now. I am wondering if any one have alternative solution for  me ?
