### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by CuteCurry** [nrc-cnrc/EGSnrc#411]
Dear author,
I am trying to install EGSncr on Windows 10, however, when I install the EGSnrc-configure-windows.exe, it ask me the select the make utility, c compiler, C++ compiler and fortran complier. I don't where are they, are they in the folder mingw\bin? There are many applications in this folder, I don't know which are.

**Comment by rtownson** [comment]
I saw on a different post that you solved this. In the future, you will likely get a quicker response on the [google+ community](https://plus.google.com/communities/106437507294474212197)!
