### ISSUE TITLE
IAUSFL not initialized correctly in DOSRZnrc with new version

### ISSUE THREAD

**Issue by dworogers** [nrc-cnrc/EGSnrc#419]
At [line 2556 in DOSRZnrc](https://github.com/nrc-cnrc/EGSnrc/blob/45e3945bad79cef063e12a0b2a1096c21727b0fa/HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran#L2556) on the develop branch, `IAUSFL` is initialized `j=6,33`. It should be `6,35`
with the new iarg calls. Should have no effect on results but just not logical.
```
DO J=1,5[IAUSFL(J)=1;]DO J=6,33[IAUSFL(J)=0;] "NORMAL EXECUTION"
```

**Comment by ftessier** [comment]
Should this be updated in the other applications as well? We currently have:
```
cavrznrc/cavrznrc.mortran:   DO J=6,21[IAUSFL(J)=0;]
cavrznrc/cavrznrc.mortran:   DO J=6,25[IAUSFL(J)=0;]
cavsphnrc/cavsphnrc.mortran: DO J=6,21[IAUSFL(J)=0;]
cavsphnrc/cavsphnrc.mortran: DO J=6,25[IAUSFL(J)=0;]
dosrznrc/dosrznrc.mortran:   DO J=6,33[IAUSFL(J)=0;]
sprrznrc/sprrznrc.mortran:   DO J=6,25[IAUSFL(J)=0;]
```
