### ISSUE TITLE
Position sampling bug in egs_shape_collection

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#42]
When defining an `egs_shape_collection` composed of cylinder shapes with midpoints away from the origin, the midpoint translation is not applied.

Here is a simple `egs_chamber` input file which reproduces the problem. Remove the `.txt` extension, run `egs_chamber -i shape_collection_midpoint` and view tracks with egs_view to reveal the problem.

[shape_collection_midpoint.egsinp.txt](https://github.com/nrc-cnrc/EGSnrc/files/147013/shape_collection_midpoint.egsinp.txt)

This is the behaviour that fooled me into reporting a bug with the cylinder shape. My apologies for the trouble!

**Comment by ftessier** [comment]
No worries, I did not realize myself at the time that the midpoint was already taken into account by an affine transformation. The underlying issue with the shape collection is that it calls the function `getPoint` for each shape in the collection, where it should call `getRandomPoint` which properly applies the affine transformation of the shape after sampling the point.
