### ISSUE TITLE
Make clean is not defined for IAEA phase space library

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#424]
It would be very convenient to have a 'make clean' option for the IAEA phase space library. I would have opened a PR, but I know nothing about Makefiles so I'm not sure if my solution is the most appropriate:

```
clean:
	$(REMOVE) $(DSO2)iaea_phsp.$(obje) $(DSO2)$(libpre)iaea_phsp$(libext) $(DSO2)$(libpre)iaea_phsp$(libext_bundle)
```

**Comment by hdclark** [comment]
Your suggestion appears to work as intended on a fresh install, so I made a patch out of it.
