### ISSUE TITLE
Particles stuck in DOSXYZnrc following modification to ELECTR for magnetic fields

### ISSUE THREAD

**Issue by snaqvi69** [nrc-cnrc/EGSnrc#425]
I tried the latest version of EGSnrc. But every dosxyznrc simulation seems to be getting stuck after a few histories. Even the examples such as _air_bone_interface_example.egsinp_.
I am wondering if anyone has experienced this issue. Thanks.

**Comment by mchamberland** [comment]
@ftessier I think that dosxyznrc gets stuck in some of the electron transport routine and the only commit related to electron transport that I could think of is 677bbe534cf3aec3640932e2415a633b05a1df78. So I reverted to the commit before that (de1717cc15280f140754ad325503fe81b667673a) and sure enough, dosxyznrc runs properly.

**Comment by snaqvi69** [comment]
Thanks Frederic. I am still having the same issue after downloading from https://github.com/nrc-cnrc/EGSnrc.git today. Where can I get the correct version from? Thanks.

**Comment by rtownson** [comment]
For now if you replace line `1391` in `$HEN_HOUSE/src/egsnrc.mortran`:

`IF(irnew ~= irold) [ $electron_region_change; ];`

with:

`$electron_region_change;`

this will fix the bug and the transport will be correct. After that change, recompile any apps you are using. As @mchamberland points out this was a recently introduced bug while working on magnetic fields in vacuum; we'll push a proper fix to the release asap.

**Comment by ftessier** [comment]
Thanks @snaqvi69 and @mchamberland for reporting on this rather critical bug! Will advise shortly.
