### ISSUE TITLE
Bug in *.io files of MORTRAN user codes

### ISSUE THREAD

**Issue by mainegra** [nrc-cnrc/EGSnrc#43]
When EGSnrc reads the `*.io` files looking for pairs `unit extension` per line, it also checks for comments by checking whether the first character of a line starts with `#`. This very simple check will fail if there is a blank line which is the case now in the first line of all `*.io` files.

The affected files in `$EGS_HOME` and `$HEN_HOUSE/user_codes` are:
```
./cavrznrc/cavrznrc.io
./cavsphnrc/cavsphnrc.io
./dosrznrc/dosrznrc.io
./dosxyznrc/dosxyznrc.io
./dosxyznrc_old/dosxyznrc.io
./edknrc/edknrc.io
./examin/examin.io
./flurznrc/flurznrc.io
./g/g.io
./sprrznrc/sprrznrc.io
./tutor4/tutor4.io
./tutor7/tutor7.io
```
and the default io file for BEAM user codes:
```
$HEN_HOUSE/omega/beamnrc/default_beam.io
```
Solution: The blank line should be removed.

**Comment by ftessier** [comment]
Fixed in c89f8ff
