### ISSUE TITLE
Z position of particle is overwritten by shared library MLC code

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#437]
[Line 3995 in srcxyznrc.mortran](https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran#L3995) should be passing the dummy variable `zsrcdum ` to the VCU particleDMLC code and not the actual `zsrc`. From my understanding, particleDMLC always returns z=0. I can confirm from testing that the current version gives erroneous results and replacing `zsrc `by `zsrcdum `on line 3995 fixes the issue.

**Comment by ftessier** [comment]
Fixed in pull request #450
