### ISSUE TITLE
The level of START for SYNCHDMLC?

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#443]
If I've understood correctly, the horizontal leaf dimensions are defined at the level of ZMIN of the CM, right? How about START? For VARMLC/DYNVMLC CM the manual text says ZMIN as well, but when I'm using SYNCHDMLC, in my ...._wX.egslog file there is a line with 'Input the starting X (ORIENT_MLC=0) or Y (ORIENT_MLC=1) position at z = XXX', where z > ZMIN, not z=ZMIN, as expected.

**Comment by blakewalters** [comment]
Hi @ojalaj:
Yes, START is defined at the ZMIN of SYNCHDMLC.  Is it possible that ZMIN is being automatically reset because of overlap with the previous CM?
Blake

**Comment by ojalaj** [comment]
Hi @blakewalters and thank you for getting back to this.

I double-checked that there is no overlap with previous CM. Is it possible that in the .egslog file in the aforementioned line the z position is rounded to closest integer? In the beginning of the block providing information on SYNCHDMLC CM there is a line saying "Z position of top of Varian MLC (>=0) :     XX.XXXX", which is the value provided by me in the .egsinp file as ZMIN and also the uppermost coordinate of one leaf type.

**Comment by rtownson** [comment]
This was just a display bug - @ojalaj you are correct that the value of zmin was being truncated in the output. Fixed in PR #484.
