### ISSUE TITLE
egs_cbct - Segmentation fault

### ISSUE THREAD

**Issue by povolann** [nrc-cnrc/EGSnrc#448]
Just a few days ago I have installed the new EGSnrc on my notebook and today I ran my own egsinp file with egs_cbct (after the make command in egs_cbct file) and I got this error: Segmentation fault (core dumped [obraz paměti uložen]).

I had EGSnrc (older version) on my notebook before, I also have it on different notebook (older version), where this file runs normally. I don't know what to do with this, becuase I have never got this error... I guess that there are some issues with the memory, but I'm not really sure what should I be looking for.

**Comment by rtownson** [comment]
I'm closing this issue because it was resolved on the g+ pages. Switching from Fedora 28 to Ubuntu 16 seemed to fix the issue, for unknown reasons.
