### ISSUE TITLE
egs_view compilation does not respect choice of compilers

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#458]
When building egs_view, it does not respect the compiler choices in the currently active configuration. When qmake creates the Makefile_(my_machine) file, it seems like it simply defaults to gcc and g++ (not sure how it picks those up), instead of the compilers in (my_machine).conf. I guess qmake has no way of knowing...?

**Comment by crcrewso** [comment]
I think this is a qmake issue, not a EGSnrc one

https://stackoverflow.com/questions/6609117/changing-compiler-in-qt

Are you suggesting that the finalize for egsuser script should set this up explicitly in the user's profile?

**Comment by mchamberland** [comment]
Thanks. It wasn't immediately obvious to me that typing `make` in the `egs_view` folder wouldn't pass my compiler choices to `qmake`.

I would suggest simply making a note in the wiki that when building the Qt GUIs, `qmake` uses its own configuration stored in `$QTDIR/mkspecs`.

**Comment by rtownson** [comment]
I've updated the wiki to reflect this.
