### ISSUE TITLE
SYNCHDMLC CM crashes when full leaves are not defined

### ISSUE THREAD

**Issue by rtownson** [nrc-cnrc/EGSnrc#459]
BEAMnrc crashes with the synchdmlc CM when not all leaf types are defined, even if they are not used. The `full` leaf type should be optional, but if the cross sections are not defined (in a valid way) this causes a crash, even if the `full` type is not selected for use.

@blakewalters I see that you removed the 'define only if necessary' lines in PR #455, so maybe that is intentional?

Reported on google+ by Derya Yücel:

https://plus.google.com/108156691265193140021/posts/bJdnYLgrpXe

**Comment by blakewalters** [comment]
@rtownson and that's right.  Currently you have to specify FULL leaf cross sections whether you use them or not and so the GUI implying this was optional was confusing.  I see, though, that it would be useful to have an option not to specify this cross section.

**Comment by blakewalters** [comment]
See PR #455.  I've included in this pull request the option to use only one or two different leaf types, provided, of course that HALF and QUARTER leaves are used in TARGET/ISOCENTER pairs.

**Comment by ftessier** [comment]
Is this resolved then?

**Comment by rtownson** [comment]
Yes PR #455 fixed this.
