### ISSUE TITLE
QT5 documentation

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#464]
The wiki should be updated to reflect the new QT5 setup rules. 

For Ububtu and WSL with the qt5-default and qt5-qmake packages installed the following bash variables should be defined, preferably in bashrc

`export QTDIR=/usr`

`export QT_SELECT=qt5`

**Comment by rtownson** [comment]
I have updated the wiki, thanks.

**Comment by crcrewso** [comment]
@rtownson 

Great update, and very quick, thank you! one question though. There's a make file in the gui directory. Is there any reason why we aren't suggesting that the users use that instead of making each app downstream individually?

**Comment by rtownson** [comment]
I expanded the wiki a bit more to include this option.
