### ISSUE TITLE
Instructions for creating density correction files in the wiki

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#466]
It would be nice to have instructions / guidance on how to create density correction files for new compounds on the wiki. I know ESTAR can be used to get the density effect parameter 'delta', but what is the format of the .density file and how many / which energies should be requested? Are the values in the .density file simply the delta parameter?

**Comment by mchamberland** [comment]
Also, if you anyone can provide scripts that automate the process of creating .density files, that would be great. ;)

**Comment by rtownson** [comment]
Added a page on the wiki: https://github.com/nrc-cnrc/EGSnrc/wiki/Generating-density-correction-files

**Comment by mchamberland** [comment]
Thanks a lot!
