### ISSUE TITLE
DOSXYZnrc segfaults when ECUT is 0 in the input file

### ISSUE THREAD

**Issue by ftessier** [nrc-cnrc/EGSnrc#474]
Following up on #469, DOSXYZnrc still segfaults when `ECUT=0` in the input file. I have reinstated the corresponding branch ` fix-gui_ecut_pcut_defs`

**Comment by blakewalters** [comment]
Hi @ftessier: Can you send me the problem .egsinp file (and maybe even the .F file for the dosxyznrc code)?  I can't replicate this.

**Comment by ftessier** [comment]
Seems fine. I must have been using an outdated branch or executable!
