### ISSUE TITLE
EGSnrc GUI medium composition

### ISSUE THREAD

**Issue by serkdo** [nrc-cnrc/EGSnrc#477]
Hi Everyone! I am trying to model a target that is composite at the EGSnrc and having trouble to do it. I am using EGSnrc GUI to the medium composition. My target is 52.5% Bi, 32% Pb and 15.5% Sn. How should I enter it in the medium composition? I am attaching the screenshot.
![egsnrc](https://user-images.githubusercontent.com/43421450/45776439-7c924d80-bc18-11e8-823d-f6ddb514909f.PNG)

**Comment by rtownson** [comment]
Hi @serkdo, I see you posted this question to the google+ group also and I gave an answer there - that's the correct place for this question! We try to keep the issues page here reserved for bug reports and feature requests.
