### ISSUE TITLE
material data file and egspp medium sterncid parser inconsistent

### ISSUE THREAD

**Issue by MartinMartinov** [nrc-cnrc/EGSnrc#478]
I believe that the reader for material data files sees the character '.' as a terminator, where as the egspp parser (at least in egs_view and egs_chamber) can include the character '.'.  I encountered this error when I had the following two media sterncids in my material data file,
```
TISSUE_AU14.00MG
TISSUE_AU14.47G
```
Upon execution I get the following in my egslog file:
```
   Medium: TISSUE_AU14.47G
 Sterncid: TISSUE_AU14.47G
     rho:    1.01326E+00 g/cm^3
 Elements: H   C   N   O   AU
    rhoz:    9.96055E-02   1.09467E-01   2.56410E-02   7.51479E-01   1.38067E-02
      pz:    9.88179E-02   9.11378E-03   1.83062E-03   4.69692E-02   7.00894E-05
  iunrst:     0
  iaprim:     1
    gasp:    0.00000E+00 atm.
```
which is the composition of TISSUE_AU14.00MG, not TISSUE_AU14.47G.  What I should get (which I did get once I removed TISSUE_AU14.00MG from my material data file) is:
```
   Medium: TISSUE_AU14.47G
 Sterncid: TISSUE_AU14.47G
     rho:    8.84166E+00 g/cm^3
 Elements: H   C   N   O   AU
    rhoz:    6.52824E-03   7.17460E-03   1.68054E-03   4.92526E-02   9.35364E-01
      pz:    6.47662E-03   5.97328E-04   1.19981E-04   3.07840E-03   4.74835E-03
  iunrst:     0
  iaprim:     1
    gasp:    0.00000E+00 atm.
```

**Comment by blakewalters** [comment]
Hi @MartinMartinov: If it's not a problem, could you send me the .egsinp file and material.dat file causing the problem?  Thanks.

**Comment by MartinMartinov** [comment]
Hi @blakewalters,

    Sadly, the original file uses a lot of custom dependencies I've added in my egspp geometries and in my egs_chamber simulation itself.  I did come up with a basic simulation that still has the same issue for me though, where I just define 4 spheres with 4 different materials defined in a material.dat file (.dat, .egsinp and .egslog made with egs_chamber attached).  And the issue still shows up when I define my first three media as:

TISSUE_AU5.00MG
TISSUE_AU5.00MG_TIMESTEN
TISSUE_AU5.00WATER

all three media definitions (density/composition) match the definition of TISSUE_AU5.00MG.  What's interesting though is that the 4th medium:

TISSUE_AU5.WATER

actually retrieved the correct definition of water I put in in the material.dat file.  Maybe the issue stems from following the period with a number which causes the parser to terminate early and/or give a positive result when comparing?

    I hope the .egsinp file runs for you, I think I kept it to standard libraries and functions, if not I'll give it another go.

[Material_parsing_test.zip](https://github.com/nrc-cnrc/EGSnrc/files/2687063/Material_parsing_test.zip)

**Comment by blakewalters** [comment]
Thanks @MartinMartinov:  See PR #503.  The blank spaces in your lines containing the "medium"
key in the material.dat file were causing the problem.  I've increased the length of the search delimiters
used in this file from 40 to 80 chars.  This should fix it.

**Comment by MartinMartinov** [comment]
Perfect, thank you for the fix.
