### ISSUE TITLE
Simulation with SYNCHDMLC FULL leaves not possible

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#489]
If one tries to use the SYNCHDMLC FULL leaf model to simulate Varian HDMLC, the following problem arises. 5 leaf groups has to be defined - 1 FULL leaf, 13 HALF leaves, 32 QUARTER leaves, 13 HALF leaves and 1 FULL leaf. However, for HALF leaf groups following problems is output:
```
 ***ERROR IN CM   5 (MLC)
 Leaf group   2 consists of TARGET/ISOCENTER pairs but
 does not have an even number of leaves.

 ***ERROR IN CM   5 (MLC)
 Leaf group   4 consists of TARGET/ISOCENTER pairs but
 does not have an even number of leaves.
```
This could be solved by having model for OUTBOARD/FULL leaf #1 and #60 separately and if they would together with HALF leaf groups form even number of leaves on both sides of QUARTER leaves. Or if this is not possible, then just allowing odd number of HALF leaves.

**Comment by blakewalters** [comment]
Yes, I see what you mean, @ojalaj.  I'll see what's involved in relaxing the restriction of having an even number of half and quarter leaves.

**Comment by blakewalters** [comment]
Hi @ojalaj:  Please give PR#514 a try and let me know if this allows you to model the HD 120 more realistically.

**Comment by ojalaj** [comment]
Hi @blakewalters! Thanks for the contribution. I'm out-of-office (and actually running a long queue of simulations) for another two weeks. Are you planning to merge this to 2019 release, i.e. how soon you wish me to test this?

**Comment by blakewalters** [comment]
Thanks @ojalaj.  It would be nice to get this into the 2019 release, maybe @ftessier can give us an idea of the timeline.
