### ISSUE TITLE
"FAILED TO FIND A POINT THAT IS INSIDE THE GEOMETRY" WITH EGS_VIEW

### ISSUE THREAD

**Issue by giuliorossimic** [nrc-cnrc/EGSnrc#490]
In egs_view I get the warning "failed to find a point that is inside the geometry" even if I set the viewing boundaries in different ways. Here below is a simple code showing the problem

########################################################################
#
# A SIMPLE EXAMPLE IN WHICH SETTING THE VIEWING BOUNDARIES
# DOES NOT WORK TO AVOID THE WARNING "FAILED TO FIND A POINT THAT IS
# INSIDE THE GEOMETRY"
#
########################################################################

:start geometry definition: 

  :start geometry: 
     name = cylinder
     library = egs_cylinders
     type = EGS_YCylinders
     radii = 0.05
     :start media input:
       media = copper 
     :stop media input: 
  :stop geometry:

  :start geometry:
    name = translated_cylinder
    library = egs_gtransformed
    my geometry = cylinder
    :start transformation:
      translation = 0.5 0 0
    :stop transformation:
  :stop geometry:   

 :start geometry: 
   name = cd_planes
   library = egs_planes
   type = EGS_Yplanes
   positions = -1 1
 :stop geometry:

 :start geometry:
  name = cut_cylinder
  library = egs_cdgeometry
  base geometry = cd_planes
  set geometry = 0 translated_cylinder
 :stop geometry:
 
 :start view control:
    xmin = -0.05
    xmax = 0.05
    ymin = -0.05
    ymax = 0.05
    zmin = -0.05
    zmax = 0.05
 :stop view control:

  simulation geometry = cut_cylinder

:stop geometry definition:

**Comment by rtownson** [comment]
The `view control` block must be outside the `geometry definition` block.  E.g.

```
simulation geometry = cut_cylinder

:stop geometry definition:

:start view control:
xmin = -0.05
xmax = 0.05
ymin = -0.05
ymax = 0.05
zmin = -0.05
zmax = 0.05
:stop view control:
```
