### ISSUE TITLE
Subroutine egs_shellwise_photo wants to convert photon to an electron

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#495]
As reported in https://plus.google.com/117012414775310191025/posts/AJAj8sMBHs4, we are running an egs_chamber simulation on our cluster with 'develop' branch from September 25th (sorry, git log -1 returned fatal: Not a git repository (or any parent up to mount point /home) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)). It is a batch run simulating a dose profile with a realistic 'moving' detector. We get this kind of warning/error, which is new for us:
```
IAEA_PhspSource::setSimulationChunk(): illegal attempt to set the simulation chunk between 400000001 and 600000000 ignored

Running 200000000 histories

Batch CPU time Result Uncertainty(%)

1 Subroutine egs_shellwise_photo called with E = 1.0000000253235597E-003 which is below the current min. energy of 1.00000005E-03 keV!
Converting now this photon to an electron,
but you should check your code!
24836.59 2.78508e-22 5.00
2 Subroutine egs_shellwise_photo called with E = 1.0000000464604173E-003 which is below the current min. energy of 1.00000005E-03 keV!
Converting now this photon to an electron,
but you should check your code!
```

When generating our iaea_phsp_source, we used ECUT=ae=0.521 and PCUT=ap=0.01 and for this run we are using ECUT=0.521=ae and PCUT=ap=0.001, with:
```
 Global ECUT= 0.521
 Global PCUT= 0.001
 Global SMAX= 1e10
 ESTEPE= 0.25
 XImax= 0.5
 Skin depth for BCA= 3
 Boundary crossing algorithm= EXACT
 Electron-step algorithm= PRESTA-II
 Spin effects= on
 Brems angular sampling= KM
 Brems cross sections= NRC
 Photon cross sections= mcdf-xcom
 Electron Impact Ionization= On
 Triplet production= On
 Radiative Compton corrections= On
 Bound Compton scattering= On
 Pair angular sampling= KM
 Pair cross sections= NRC
 Photoelectron angular sampling= On
 Rayleigh scattering= On
 Atomic relaxations= On
 Photonuclear attenuation= On
 Compton cross sections = default
 Photonuclear cross sections = default
```
Have you any tips, where to start trying to find the reason/solution for this?

**Comment by mainegra** [comment]
@ojalaj  try this quick fix: In line 773 of egsnrc.macros set $RELAX-CUTOFF to 0.001D0 to make it a double precision constant. Let me know if it works!

**Comment by ojalaj** [comment]
@mainegra - We will have to wait until the simulation finishes. We will try it for the next one and let you know. Thanks!

**Comment by ojalaj** [comment]
@mainegra For me on line 770 (not 773) there was:
REPLACE {$RELAX-CUTOFF} WITH {0.001"threshold energy for outer shells"}
that I changed to
REPLACE {$RELAX-CUTOFF} WITH {0.001D0"threshold energy for outer shells"}

I'll let you know did it have an effect.

**Comment by ojalaj** [comment]
@mainegra At least I have not experienced this issue after applying the suggested quick fix (although I did not go through each and every _wX.egslog file, just several of them randomly).

**Comment by ftessier** [comment]
@mainegra should this `0.001D0` quick fix be implemented for good on `develop`?

**Comment by mainegra** [comment]
Yep @ftessier !

**Comment by mainegra** [comment]
@ftessier and @rtownson is this still an issue?

**Comment by rtownson** [comment]
@mainegra Yes, we never ended up applying this change.

**Comment by ojalaj** [comment]
@mainegra @ftessier @rtownson  I can confirm that using this fix we haven't had any similar issues.

**Comment by ojalaj** [comment]
@mainegra @ftessier @rtownson Using EGSnrc2020 develop branch I got the error, i.e., I still need to apply the change suggested by @mainegra . Maybe applying this change could be added to the roadmap?

**Comment by ojalaj** [comment]
@mainegra Any plans to apply this change & merge (to develop)?

**Comment by ftessier** [comment]
As far as I can understand, #666 (😈 ) resolved this problem. Don't hesitate to reopen if it remains an issue!
