### ISSUE TITLE
Incorrect geometry check in SYNCVMLC

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#497]
According to Varian TB information for Millennium MLC, `WBS < WG + WTIP`. Similarly than in #442 for SYNCHDMLC, code check `W_(bottom of support rail) >= W_groove + W_tip` should be `W_(bottom of support rail) < W_groove + W_tip`.

I.e. in SYNCVMLC_cm.mortran should line 1298 be:
`IF(WRAILBOT_$SYNCVMLC(2)>WGROOVE_$SYNCVMLC(2)+WTIP_$SYNCVMLC(2))[`
and then change lines 1301-1302 accordingly?

Now I get:
```
 ***ERROR IN CM   5 (MLC) in TARGET leaf definition:
 WRAILBOT_MLC(2)<WGROOVE_MLC(2)+WTIP_MLC(2).
 Lower rail too narrow.
```

**Comment by blakewalters** [comment]
@ojalaj, this would also mean the geometry of target leaves in DYNVMLC is incorrect.  I'm not all that familiar with the Millennium MLCs, but I think DYNVMLC and SYNCVMLC were intended to model the 80-leaf Millennium, while SYNCHDMLC, in which W_railbot < W_tip + W_groove, is intended to model both the 120-leaf Millennium and the HD MLCs.  @marenaud, do you have some experience with the 80-leaf Millennia?

**Comment by ojalaj** [comment]
Hi @blakewalters & @marenaud. I have not modelled 80-leaf Millennium at all, so I don't have any experience on the possible problems with DYNVMLC/SYNCVMLC related to 80-leaf Millennium. What I do know, however, is that 80-leaf model has OUTBOARD leaves #1 and #40 and then 38 FULL leaves in between (correct me if I'm wrong). For years I've used SYNCVMLC for modelling 120-leaf Millennium and  for couple of years I've used SYNCHDMLC for HD120 MLC. I have not even thought that SYNCHDMLC could/should be used for 120-leaf Millennium (maybe just because there is "HD" in the CM name and in Varian terminology "HD" is used only HD120 MLC). Do you have any thoughts on this @marenaud ?

**Comment by blakewalters** [comment]
Thanks for the input, @marenaud, and the information (reminder?) that DYNVMLC and, thus, SYNCVMLC, were coded with the 120-leaf collimator in mind.  In this case, then, it does, indeed seem like the restriction on W_railbot is wrong.  If you happen to have any of your old SYNCVMLC/DYNVMLC inputs lying around, @marenaud, I'd certainly be interested in seeing them!

**Comment by ojalaj** [comment]
Thanks for the contribution @marenaud. I should have remembered the paper @marenaud referenced to and only 120-leaf Millennium contains HALF leaves. For DYNVMLC PIRS-509 also mentions Millennium MLC and that there are usually 120 leaves.

Anyhow, now that I see that there is no restriction to change from SYNCVMLC to SYNCHDMLC for 120-leaf Millennium, I may make the change as well. Another limitation both CMs still share is the accurate model for OUTBOARD leaves #1 and #60, but that is another story then.
