### ISSUE TITLE
QT GUI compilation fails on macOS

### ISSUE THREAD

**Issue by binggnid** [nrc-cnrc/EGSnrc#498]
When I finished the installation of EGSnrc, I try to install GUI in my MACOS. I followed the steps, and I got fatal error when I compling:

`/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++11  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/local/Cellar/qt/5.11.2_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.2_1/lib/QtCore.framework/Headers -I.moc/osx -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.11.2_1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.2_1/lib -o .obj/osx/moc_egs_run_page.o .moc/osx/moc_egs_run_page.cpp
In file included from In file included from .moc/osx/moc_main_widget.cppegs_gui_widget.cpp:In file included from :.moc/osx/moc_egs_compile_page.cpp:9:
In file included from 32.moc/osx/../../egs_compile_page.h:
:35:
In file included from egs_run_page.cpp:In file included from pegs_runoutput.cpp:9:
.moc/osx/../../main_widget.h:35:10: fatal error: ./egs_gui_widget.h:35:10: 32./egs_gui_widget.h:
:fatal error35: :10:./egs_run_page.h :35'qwidget.h':fatal error 10: file:  not foundfatal error'qwidget.h': 
`

Then, I checked the file 'qwidget.h' and it is exist in:
`/usr/local/Cellar/qt/5.11.2_1/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h`.

I copy this file to the directory where I am compling. The problem still there.
Can you give me some advise for this problem?

**Comment by binggnid** [comment]
New issues: `egs_view` can not working. I notice this problem when I finished the EGS installation (before the `QT GUI` installation).

**Comment by crcrewso** [comment]
I just noticed, it looks like you tried to compile the qt libs with Clang. I am not sure that the version of QT and the code base works with clang yet. As of now Flang isn't mainstream so I haven't been considering testing of clang only or clang + gfortran as a real priority. 

@ftessier This is a bigger issue, with gcc on mac being left out in the cold, and non-homebrew tooling growing increasingly out of date on the platform at what point is the project going to be forced to consider dropping Mac support?

**Comment by ftessier** [comment]
@crcrewso, I did not know we ever had macOS support :worried:. More of a courtesy thing, trying to figure out how best to make it work. I have a new macOS system to try it out; I hope to be able to update instructions to get EGSnrc working on it! Otherwise we might indeed just drop it, and advise users to install EGSnrc in a linux VirtualBox (we talked about distributing it that way, what do you think?).

**Comment by crcrewso** [comment]
If I had more time I'd suggest creating a full docker image with gridengine or slurm. I've seen a couple other projects show reasonable success with porting to docker but I don't know how it would work for us. 

Distributing VirtualBox images might be a good idea in principle, but I've had better experience with getting VMware images into the store and people actually finding them later.

**Comment by ftessier** [comment]
I tried docker, but I can't figure out how to build and distribute a full GUI desktop. I can add the required components in the docker recipe, but how does the user then load up a full GUI linux at their end?

As for the VB images we would distribute them ourselves, as an .ovf appliance, so *finding* it would not be an issue.

**Comment by mchamberland** [comment]
I installed EGSnrc and the guis (including egs_view) on a brand new Mac in October and everything worked flawlessly with the default instructions. ¯\_(ツ)_/¯

**Comment by ftessier** [comment]
Super! Thanks for the update @mchamberland! @binggnid, can you provide more details on your machine and OS version, and the specific error you encounter? Did you try to compile egs_view yourself? Let us know how we can improve the instructions otherwise.

**Comment by binggnid** [comment]
> I installed EGSnrc and the guis (including egs_view) on a brand new Mac in October and everything worked flawlessly with the default instructions. ¯_(ツ)_/¯

Thanks for your reply. I try my best to figure out those problems. But, it still a mess. If you can record those steps as a vedio and upload to youtube.com. I (or others) am so gratitude to your vedio instruction. If you are busy, just ignore this. Thanks again!

**Comment by binggnid** [comment]
> I just noticed, it looks like you tried to compile the qt libs with Clang. I am not sure that the version of QT and the code base works with clang yet. As of now Flang isn't mainstream so I haven't been considering testing of clang only or clang + gfortran as a real priority.
> 
> @ftessier This is a bigger issue, with gcc on mac being left out in the cold, and non-homebrew tooling growing increasingly out of date on the platform at what point is the project going to be forced to consider dropping Mac support?

@

> I just noticed, it looks like you tried to compile the qt libs with Clang. I am not sure that the version of QT and the code base works with clang yet. As of now Flang isn't mainstream so I haven't been considering testing of clang only or clang + gfortran as a real priority.
> 
> @ftessier This is a bigger issue, with gcc on mac being left out in the cold, and non-homebrew tooling growing increasingly out of date on the platform at what point is the project going to be forced to consider dropping Mac support?

@crcrewso Thanks! I will try it by using gcc. I am going to figure out how to change the default compiler on macos (Mojave version 10.14.1).

**Comment by binggnid** [comment]
@ftessier @crcrewso @rtownson Thanks guys! 
I already fix my problem. I rechecked the issue #325, which gives me a hint. 
Here is the real problem: the compling error of `egs_view`, `egs_gui`, `egs_ingz`. 
The basic reason is from multiple version `QT`. 

Fix method:
(Here lists my laptop information: Macos Mojave Version 10.14.1)
I followed the instruction: [https://github.com/nrc-cnrc/EGSnrc/wiki/Building-GUIs-on-macOS](url). Firstly, I downloaded the `QT5` by `brew install qt`. Then I go into the `$HEN_HOUSE/gui/egs_gui`, and type `make`. An fatal error was occur, `qwidget.h not found` (see the top 1#). I did not fix this error. 
Second, I uninstalled `QT5` and installed `QT4` (`brew install cartr/qt4/qt`). Three components  were installed. I just keep one `qt@4/4.8.7_5`, the others were uninstall. Following the residual steps, the compiling were successful.  Only flaw is that `egs_view` is not executable.  You can `export` the related directory, like `export PATH="$HEN_HOUSE/bin/osx/egs_view.app/Contents/MacOS/:$PATH"`.
After that, it is working flawlessly.

Thanks again.
Bing
Jan 4, 2019
`

**Comment by hukui4860** [comment]
> I installed EGSnrc and the guis (including egs_view) on a brand new Mac in October and everything worked flawlessly with the default instructions. ¯_(ツ)_/¯
Did you brew install qt or brew install cart/qt4/qt?
