### ISSUE TITLE
Phase-space  and other file locations cannot be specified with a relative path

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#50]
It would be great if the file locations of phase spaces and other files could be linked relatively or at least through the `$EGS_HOME` and `$HEN_HOUSE` variables. It would make switching between a prototype and production system much easier. This could be flagged as a product improvement request.

**Comment by ftessier** [comment]
@crcrewso do you mean the ability to specify file locations with relative paths in input files?

**Comment by crcrewso** [comment]
@ftessier I'm pretty sure that's what I meant, yes. I have quite a few different installs and modifying each one when they're moved from a test to a workhorse system is frustrating.

**Comment by ftessier** [comment]
In what applications do you need this the most? I can see this as relatively easy for egs++ applications. For Mortran apps it might be more work to implement. @blakewalters can you comment on this?

**Comment by crcrewso** [comment]
@ftessier dosxyznrc would be the most useful for my office mates. BEAM would be my first hope though.

**Comment by blakewalters** [comment]
Currently, you can specify HEN_HOUSE and EGS_CONFIG on the command line for all codes.  Why not the output directory as well?

**Comment by ftessier** [comment]
I think what @crcrewso is looking for is the ability to specify relative or at least `$EGS_HOME` and `$HEN_HOUSE` env variables in the input file itself.

**Comment by crcrewso** [comment]
I really should be clearer, let me know if this makes more sense. 

When dealing with input files that rely on phase spaces I would like to be able to set the phase space location by 
`$EGS_HOME\TB\tb.egsphsp1 `
instead of 
`\home\user\EGSnrc\egs_home\TB\tb.egsphsp1`

Since EGS_HOME should be set in the bashrc file I would like to see the parser for the input file first replace EGS_HOME with its definition, then pass the full file path down the chain. 

or at the very least 
`~\EGSnrc\egs_home\TB\tb.egsphsp1`
would be an improvement over what we have now.

**Comment by blakewalters** [comment]
Yes, this makes sense.  I agree that this would save a lot of headache for users.  This is a simple fix, given the getenv function in Fortran.  I'll make these changes...
