### ISSUE TITLE
how can get Detector response 

### ISSUE THREAD

**Issue by elgoub** [nrc-cnrc/EGSnrc#505]
hey how can get Detector response in egsnrc ??

**Comment by rtownson** [comment]
Hi @elgoub, questions like this will get better (and faster) answers if you post them on our [google+](https://plus.google.com/communities/106437507294474212197) or [reddit community](https://www.reddit.com/r/EGSnrc)! We use the issues here mostly for bug reports and feature requests.

Could you repost on one of those sites with more information, like the type of detector you would like to model? Small detectors like ionization chambers are best modelled with the egs_chamber application. 

Please see the [getting-started manual](http://nrc-cnrc.github.io/EGSnrc/), maybe it will help to answer your questions.
