### ISSUE TITLE
Bug in CD geometry

### ISSUE THREAD

**Issue by hbouchard** [nrc-cnrc/EGSnrc#506]
I apologize if I didn't have time to investigate this in more detail. I came so far as the conclusion that when using CD geometry with cylinders in each of its "dimension", it doesn't cope with unmatched outer radii, leading to negative steps. I have created this very simple example to show the effect. Try ncase = 2000 and it will crash. 

<img width="853" alt="screen shot 2019-01-21 at 10 26 07 pm" src="https://user-images.githubusercontent.com/17842624/51510598-b6907d80-1dcb-11e9-8a23-ae57cfc69f17.png">

############################################################################
########################## Define the simulation geometry:
:start geometry definition:
########################## Define cylinder #1
:start geometry:
    library = egs_cylinders
    type    = EGS_XCylinders
    name    = CYL1
    radii   = 1.0
    :start media input:
        media = H2O521ICRU
         set medium = 0 0
    :stop media input:
:stop geometry:
########################## Define cylinder #2
:start geometry:
    library = egs_cylinders
    type    = EGS_XCylinders
    name    = CYL2
    radii   = 0.5
    :start media input:
        media = H2O521ICRU
         set medium = 0 0
    :stop media input:
:stop geometry:
########################## Define planes for cylinders
:start geometry:
    library = egs_planes
    type    = EGS_Xplanes
    name    = PLANES
    positions = -1 0 1
:stop geometry:
########################## Define CD geom
:start geometry:
    library  = egs_cdgeometry
    name     = CYLS
    base geometry = PLANES
    set geometry = 0 CYL1
    set geometry = 1 CYL2
:stop geometry:
########################## Define cube of air 
:start geometry:
    name        = BOX
    library     = egs_box
    box size    = 3
    :start media input:
        media = AIR521ICRU
    :stop media input:
:stop geometry:
########################## Define simulation geometry
:start geometry:
    name    = GEOM
    library = egs_gunion
    geometries = CYLS BOX
:stop geometry:
simulation geometry = GEOM
:stop geometry definition:
############################ Beam input
:start source definition:
    :start source:
        library = egs_collimated_source
        name = the_source
        :start source shape:
            type = point
            position = 0 0 1.5
        :stop source shape:
        :start target shape:
            library   = egs_circle
            radius = 0.5
        :stop target shape:
        distance = 2
        charge = 0
        :start spectrum:
            type = monoenergetic
            energy = 1
        :stop spectrum:
    :stop source:
    simulation source = the_source
:stop source definition:
##################################### Run control
:start run control:
    ncase = 2000
    nbatch = 10
    statistical accuracy sought = 0.1
    max cpu hours allowed = 88
    calculation = first
:stop run control:
##################################### Seeds
:start rng definition:
    initial seeds = 13 22
:stop rng definition:
##################################### Scoring options
:start scoring options:
    calculation type = dose
    :start calculation geometry:
        geometry name = GEOM
        cavity regions = 0 1 
        cavity mass = 1
    :stop calculation geometry:
:stop scoring options:
####################################### variance reduction
:start variance reduction:
	ELECTRON RANGE REJECTION= off
	ESAVEIN= 2.0
	RUSSIAN ROULETTE DEPTH= 0.0000
	RUSSIAN ROULETTE FRACTION= 0.0000
	EXPONENTIAL TRANSFORM C= 0.0000
	PHOTON FORCING= on
	START FORCING= 0
	STOP FORCING AFTER= 0
	CS ENHANCEMENT FACTOR= 1
	PHOTON SPLITTING= 1
:stop variance reduction:
###################################### Transport parameters
:start MC transport parameter:
	Global ECUT= 0.521
	Global PCUT= 0.01
	Global SMAX= 1e10
	ESTEPE= 0.25
	XImax= 0.5
	Skin depth for BCA= 3
	Boundary crossing algorithm= EXACT
	Electron-step algorithm= PRESTA-II
	Spin effects= on
	Brems angular sampling= KM
	Brems cross sections= BH
	Bound Compton scattering= On
	Pair angular sampling= Simple
	Photoelectron angular sampling= On
	Rayleigh scattering= On
	Atomic relaxations= On
	Photon cross sections= xcom
	Electron Impact Ionization= On
:stop MC transport parameter:
######################### Tracks
:start ausgab object definition:
    :start ausgab object:
        name    = tracks          
        library = egs_track_scoring
        score photons   = yes
        score electrons = yes
        score positrons = yes
        start scoring = 0 
        stop scoring = 128 
        buffer size = 128 
   :stop ausgab object:
:stop ausgab object definition:
############################################################################

**Comment by rtownson** [comment]
Hi @hbouchard, I believe PR #462 fixes this issue! Let me know.

**Comment by hbouchard** [comment]
Hi @rtownson, sorry about this! I updates the 8 files and recompiled egs++. It works now. Nice one :)
