### ISSUE TITLE
Parallel BEAM simulations end with failed job when outputting IAEA phase space files

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#51]
With the  `develop`  branch of EGSnrc2016 from April 1st (and actually with BEAMnrc 2013 as well) when I run a parallel BEAM simulation outputting IAEA phase space files, all the other jobs finish OK, but the last one running always fails with segmentation fault (.io file) (EXIT CODE 139). However the last job is almost finished i.e. phase space file is produced, `.egslog` and `.egslst` files are written (at least to some extent), but somehow the finalization of the whole simulation fails. Also `fort.17` and `core.XXXXX` are created. Thus I always need to re-run the simulation with `IRESTART=4`. This does not happen when outputting normal phase space files (although even then `fort.17` is created).

The distribution is installed on a Linux cluster (Scientific Linux 6.7) as per the GitHub Wiki instructions with `gfortran/gcc/g++/make` using the shell script with default options (I'm more than happy to send the configuration log files, if requested). The only modifications that have been made after the installation are in  `MAXFIELD`  and  `MAX_POINT`  parameter values of several CMs and increasing  `IMAX/JMAX/KMAX/CTKMAX/MXMED`  values for  `ctcreate`  and  `dosxyznrc`  user codes. Otherwise the code is unchanged. I have encountered the problem with every test simulation that I have run, even with the `EX16MVp` example code. Otherwise the simulations themselves run fine.

**Comment by rtownson** [comment]
Fixed in release-2017.
