### ISSUE TITLE
Add memory request option to exb and other queue suggestions

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#52]
When submitting jobs from multiple users with multiple purposes we sometimes need to explicitly declare the memory required per job. This has been done by editing the `batch_options.pbs` file before running `exb`. I've read a few issues leading me to think that some major batch configuration work is in the near future, and as such i'd like to add this as a feature request. 

As I am not a developer on this project I can only propose my vision for this but my first pass would be some flag similar to the `-p=<n> flag`, maybe `-mem=<n><unit>` 

Additionally, the batch queue is the default queue when torque is installed. Could we add each default queue name for each of the supported batch submission systems?

This is a lot of work, I know. As such I'd offer to test any fixes that you need help with.

**Comment by ftessier** [comment]
Thank you for your suggestions @crcrewso. Indeed it is high time to overhaul the job submission scripts. I personally use a python script which in addition can loop over input file parameters etc., which proves extremely useful. The current script is very dated, any one is welcome to propose a modern and more flexible implementation!
