### ISSUE TITLE
How to read phase space file using C++

### ISSUE THREAD

**Issue by Khalidhussain264** [nrc-cnrc/EGSnrc#523]
Hi
EGSnrc Team!
I am a student of MS (PHY) from COMSATS, Pakistan.
I have ".egsphsp1" file generated using BEAMnrc and I want to read its bits 0, 24-28 using C++. But I have no idea, how to extract bit's data or read .egsphsp1 file. I have little bit knowledge about programming. 

Thanks in advance.

**Comment by rtownson** [comment]
Hi Khalid,

Could you ask this question over on our reddit page instead? That's where you'll get the best support and comments from the community.

https://www.reddit.com/r/EGSnrc

Also, it sounds like you want to read bits from the LATCH variable, which is one of the variables assigned to particles in the phase-space. When you ask the question again, specify why you want this - is it for use in an egs++ application you're modifying, or a new code you're writing that will analyze the phase-space data?
