### ISSUE TITLE
dosxyznrc

### ISSUE THREAD

**Issue by zhangbin10198** [nrc-cnrc/EGSnrc#527]
hi teachers:

recently ,i have using dosxyznrc and want to get some PDD curve,but when i run it ,it show me ,"the job has failed" ,so i want to know how to solve this question .
and i will show my step
if you find any error ,please tell me ,thank you.

step:
first，i "load a previous input file" ,choose an example "16mv,h20,phantom,phisp"
secondly, i type in the command in the file "16mv" "make library"
and next, i save the input ,compile and run ,but when i run it show me  it fail

and my system  ubuntu 18, thank you reply
 
![Screenshot from 2019-04-10 20-38-48](https://user-images.githubusercontent.com/42270422/55879244-bc2e8000-5bd0-11e9-98da-5e2ff8d14b57.png)

**Comment by rtownson** [comment]
Hi @zhangbin10198, this is a question better suited for the [reddit community](https://www.reddit.com/r/EGSnrc). Please make an account there for future support, you'll get fast answers from a wider range of EGSperts!

The example you're using depends on a phase-space file, does it exist? Replace the `$EGS_HOME` in the example with your actual path. Also, you have to actually run the BEAMnrc accelerator simulation to create the phase-space first. Did you run the BEAMnrc simulation successfully?

I'm going to close this issue, and if you have more questions please post them to the reddit.

**Comment by zhangbin10198** [comment]
ok ,thank you answer,and this afternoon ,i have solve this  problem，the way is that copy the example to the upper folder,so i this the reason is  that example name plus my path to long ,i remember the path string is limited 80.so.....

and ,i m a china student,so may be my english is not good,please tolerance。hhhhh
