### ISSUE TITLE
egs++ user codes fail to run because of ".exe" in name on Windows

### ISSUE THREAD

**Issue by vahx129** [nrc-cnrc/EGSnrc#528]
On a fresh installation of EGS_2019, I noticed an issue that's persisted on Windows for at least the last few major releases where egs++ user codes including tutor7pp which I usually use to test EGS on new installs will initially fail with the following message: 

the input file: ...\EGSnrc\egs_home\tutor7pp.exe\tracks1.egsinp does not exist or is not readable

Obviously, the issue is that the directory of the egs++ user code has an extra .exe appended to it when it shouldn't. This is true of all egs++ user codes. 

I was given the workaround at the time of my personal installation but I thought I'd mention it as a bug so that other users wouldn't have this issue. It's also a pretty easy fix so I'll just reiterate what I was told here: 

1. Navigate to ...\EGSnrc\HEN_HOUSE\egs++\egs_application.cpp and open in a text editor

2. Wherever the variable "app_name" gets set, add the following line right below to correct the extra ".exe" characters from appearing (no quotes): 

"app_name = app_name.substr(0,app_name.find_last_of(".exe")-3);"

Then, simply recompile the egs++ directory in HEN_HOUSE and this should be fixed.

**Comment by rtownson** [comment]
Is this for Windows 7? I haven't seen it on Windows 10.

**Comment by vahx129** [comment]
This happened to me on Windows 10 64-bit running on a Surface Pro (2017) while following the installation instructions provided on the website. I believe it's also happened to me on my desktop which was also running Windows 10 64-bit. Maybe there's something systematic I'm doing which causes this issue. 

I'm actually in the process of trying to install EGSnrc 2019 on a Windows 7 laptop for a younger student so I'll see if I can reproduce the issue there as well.

**Comment by rtownson** [comment]
Ah this is a PowerShell issue - it doesn't happen in the CMD prompt or egs_gui. Thanks for the solution I'll post it as a PR.

**Comment by vahx129** [comment]
Just confirmed that it was, in fact, a PowerShell issue as well. Thanks for the quick response!

**Comment by rtownson** [comment]
This was fixed by PR #532, which has now been merged in so I'm closing this issue.
