### ISSUE TITLE
SYNCHDMLC component module not synchronizing motion unless SYNCJAWS also present

### ISSUE THREAD

**Issue by vahx129** [nrc-cnrc/EGSnrc#533]
In part of a TrueBeam BEAMnrc model, I originally included the JAWS component module and the SYNCHDMLC component module for simulating treatment plans. In all the plans I investigated, the jaws never involved any kind of synchronized motion so I didn't think I needed to include the SYNCJAWS component module. I noticed, however, that when running BEAMnrc simulations using that model that fractional MU was not being stored in the output IAEA phase space even though a synchronized CM (SYNCHDMLC) was present. When I changed my JAWS CM to SYNCJAWS instead, this seemed to fix the issue. Perhaps SYNCHDMLC by itself is not being recognized as a synchronized component module somewhere in the code?

It's a minor bug at best since I don't see any downside to just using SYNCJAWS but I thought I'd mention it in case anyone else can reproduce it. The discussion detailing the issue can be found at this Reddit link:
 https://www.reddit.com/r/EGSnrc/comments/bfrmkl/question_regarding_fractional_mu_storage_from/

**Comment by blakewalters** [comment]
@rtownson, @ftessier: Can I go ahead and close this issue?  It was resolved with:
https://github.com/nrc-cnrc/EGSnrc/pull/539
