### ISSUE TITLE
Simulation hangs when COSTHE < -1 in subroutine ANNIH

### ISSUE THREAD

**Issue by dfrei** [nrc-cnrc/EGSnrc#535]
Line 149 of egsnrc.mortran (v2019) is

    COSTHE=MIN(1.0,(ESG1-RM)*POT/ESG1);

Sometimes (very rarely) COSTHE can become less -1, say -1.00000000002. Then the next line sets SINTHE to NaN and the simulation may get caught in an endless loop.
I suggest to change line 149 to something like
 
    COSTHE=MAX(-1.0,MIN(1.0,(ESG1-RM)*POT/ESG1));

**Comment by rtownson** [comment]
Thanks for hunting down the source of the issue and suggesting a solution! I see how this could happen and the solution looks good.

You're welcome to submit the fix as a pull request, if you want the contribution credit. If not I'll do it.

**Comment by dfrei** [comment]
Please go ahead and submit the fix.
Best regards, Daniel

**Comment by rtownson** [comment]
This was fixed in PR #536, which is now merged in so I'm closing this issue.
