### ISSUE TITLE
EGS.nrc egs_gui make: f: No such file

### ISSUE THREAD

**Issue by nkosie18** [nrc-cnrc/EGSnrc#541]
hello, when running the make statement in the egs_gui directory, I get the error: f Makefile_ my_machine=
make: f: No such file or directory
make: [all] Error 1 (ignored)

**Comment by rtownson** [comment]
Have you followed the instructions in the wiki? What OS? Why are you rebuilding egs_gui?

https://github.com/nrc-cnrc/EGSnrc/wiki/Building-GUIs-on-Linux

**Comment by nkosie18** [comment]
I am using macOS mojave, yes I was following the instruction on the wiki page on Building GUIs on macOS. I created a ".bash_profile" file which I edited. when building the GUI's that is where I encountered a problem. I downloaded Qt using the command "brew  install qt", tried to look for the path using "brew info qt | grep Cellar" but nothing came up so I located it manually and found it path to be "usr/local/cellar/qt@4/4.8.7_5" so I ran the following line in terminal: "export QTDIR=usr/local/cellar/qt@4/4.8.7_5" after this I opened the egs_gui directory in terminal, typed "make" hit enter and I got the error: _f Makefile_ my_machine=
make: f: No such file or directory
make: [all] Error 1 (ignored)_

**Comment by rtownson** [comment]
You are missing the leading / on the `QTDIR` path. Try the following (confirm the path is correct):
```
export QTDIR=/usr/local/cellar/qt@4/4.8.7_5
```

**Comment by nkosie18** [comment]
this is what I am getting now, I think I should do a fresh install of EGSnrc and try to build the GUIs again:

make -j12 -f Makefile_osx my_machine=osx
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile_osx.Release
make[2]: Nothing to be done for `first'.

**Comment by rtownson** [comment]
We haven't heard any follow-up so I am going to close this issue for now. Others have since successfully compiled the GUIs on OS X.
