### ISSUE TITLE
Prune KERMA-INSERT macro and dead code block

### ISSUE THREAD

**Issue by dworogers** [nrc-cnrc/EGSnrc#543]
While reading the code for another reason I found (so far) two pieces of dead code which could be removed just to avoid confusion. $KERMA-INSERT is defied in egsnrc.macros as a default null and appears in egsnrc.mortran but just uses the default null.  I cannot find it in any application so just remove it.

At around line 6685 in egsnrc.mortran there is a section starting 
"The following convoluted logic is difficult to follow"
which is completely commented out since 2002. Let's just remove it. It also mentions $KERMA-INSERT

**Comment by ftessier** [comment]
This has been done in commit d06cc9350ffb92ffde4c5a9c98476797da9bb756, which will eventually be merged into the next release via the `small-stuff` branch, so I am closing it now. Thank you @dworogers!

**Comment by ftessier** [comment]
I checked that the string `KERMA-INSERT` currently does not exist in any file in the EGSnrc repository.
