### ISSUE TITLE
Where did these spectrums come from?

### ISSUE THREAD

**Issue by BINDX93** [nrc-cnrc/EGSnrc#546]
I would like to know where did those spectrums that are in the $/HEN_HOUSE/spectra directory come from? I mean from which database I can find them?

**Comment by ojalaj** [comment]
/HEN_HOUSE/spectra/egsnrc/README.md and /HEN_HOUSE/spectra/lnhb/README.md give some info.

**Comment by rtownson** [comment]
Closing this; the spectra references are in the readme files.

**Comment by BINDX93** [comment]
Thank you very much. I find it.




------------------ 原始邮件 ------------------
发件人: "Reid Townson"<notifications@github.com>; 
发送时间: 2019年8月21日(星期三) 凌晨3:01
收件人: "nrc-cnrc/EGSnrc"<EGSnrc@noreply.github.com>; 
抄送: "斌DX"<1021641320@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nrc-cnrc/EGSnrc] Where did these spectrums come from? (#546)




Closing this; the spectra references are in the readme files.

**Comment by BINDX93** [comment]
> /HEN_HOUSE/spectra/egsnrc/README.md and /HEN_HOUSE/spectra/lnhb/README.md give some info.

thanks a lot
