### ISSUE TITLE
dosxyznrc .egslst files not generated

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#57]
I just migrated a cluster from Egs circa 2012 to EGSnrc 2016. 

Upon doing so an old egsinp (read unmodified) that had previous to the migration produced an egslst no longer does so. 

I found this in testing but thought it was a configuration issue on my test system. As this is a clean install from git I am now starting to think that it might be a regression with the dosxyznrc code. 

What information do you need from me for troubleshooting this one?

**Comment by blakewalters** [comment]
Hi:

Can you attach the .egsinp file that's giving you trouble.

Thanks,
Blake

**Comment by crcrewso** [comment]
Here is the input and the results of the run 




[sample for dosx.zip](https://github.com/nrc-cnrc/EGSnrc/files/237402/sample.for.dosx.zip)

**Comment by blakewalters** [comment]
There's no problem with your .egsinp file.  Try going into $EGS_HOME/dosxyznrc and deleting the blank line at the top of file dosxyznrc.io (where unit numbers are assigned to their "proper" output names).  Let me know if this works.

**Comment by crcrewso** [comment]
Perfect that worked. As I overwrote my *.io with the one from HEN_HOUSE after the installation should the HEN_HOUSE copy be modified?

**Comment by ftessier** [comment]
This blank line is an issue #43 reported by @mainegra. I don't want to take these blank lines out unless there is no other way;  @blakewalters, is it possible to modify the code to allow blank first lines in `.io` files?

**Comment by ftessier** [comment]
Fixed in c89f8ff
