### ISSUE TITLE
How to set a calculated X-ray spectrum as photon source

### ISSUE THREAD

**Issue by ziwanxu** [nrc-cnrc/EGSnrc#577]
How to set a calculated X-ray spectrum (eg: from SpekCalc toolset) as photon source instead of mono-energetic X-rays?
I want to simulate the interaction of X-rays from an orthovoltage X-ray unit (Philips RT 250) and my particles. However, I don't know the exact geometry of the machine, but I can get a calculated X-ray spectrum from SpekCalc toolset. So I am wondering how to set a calculated X-ray spectrum as my photon source. Thanks for help!

**Comment by ojalaj** [comment]
https://www.reddit.com/r/EGSnrc/ is great forum for this kind of questions!

Without knowing more details about which EGSnrc application you are about to use, there is some info on using custom spectra e.g. in https://nrc-cnrc.github.io/EGSnrc/doc/pirs509a-beamnrc.pdf Chapter 5

**Comment by ziwanxu** [comment]
> https://www.reddit.com/r/EGSnrc/ is great forum for this kind of questions!
> 
> Without knowing more details about which EGSnrc application you are about to use, there is some info on using custom spectra e.g. in https://nrc-cnrc.github.io/EGSnrc/doc/pirs509a-beamnrc.pdf Chapter 5

Thank you for the quick reply! I want to know the dose distribution and secondary electron generation after the interaction of X-rays and my heavy-metal-based particles.

**Comment by rtownson** [comment]
I'm closing this issue since the question will be addressed over on the reddit page.
