### ISSUE TITLE
GUI installation

### ISSUE THREAD

**Issue by jpramila** [nrc-cnrc/EGSnrc#578]
Hi, I'm Jaya. New to linux installation (using Ubuntu 18.04.4LTS) . Not a programmer background. 
I followed the steps given.
When comes to the gui part, I'm having error.

cd ~/EGSnrc/HEN_HOUSE/gui/ && make --quiet --print-directory
make: Entering directory '/home/jaya/EGSnrc/HEN_HOUSE/gui'
make[1]: Entering directory '/home/jaya/EGSnrc/HEN_HOUSE/gui'
make[2]: Entering directory '/home/jaya/EGSnrc/HEN_HOUSE/gui/egs_configure'
make[2]: f: Command not found
make[2]: Leaving directory '/home/jaya/EGSnrc/HEN_HOUSE/gui/egs_configure'
make[2]: Entering directory '/home/jaya/EGSnrc/HEN_HOUSE/gui/egs_gui'
make[2]: f: Command not found
make[2]: Leaving directory '/home/jaya/EGSnrc/HEN_HOUSE/gui/egs_gui'
make[2]: Entering directory '/home/jaya/EGSnrc/HEN_HOUSE/gui/egs_inprz'
make[2]: f: Command not found
make[2]: Leaving directory '/home/jaya/EGSnrc/HEN_HOUSE/gui/egs_inprz'
make[1]: Leaving directory '/home/jaya/EGSnrc/HEN_HOUSE/gui'
make: Leaving directory '/home/jaya/EGSnrc/HEN_HOUSE/gui'

May I know how to rectify this situation?

**Comment by rtownson** [comment]
Hello! For questions like this, you'll get a faster response on the subreddit: https://www.reddit.com/r/EGSnrc/

You don't need to worry about building the GUIs yourself. Just download the pre-build GUIs from here (EGSnrc-guis-linux.tar.gz):
https://github.com/nrc-cnrc/EGSnrc/releases

Extract the archive and place the contents in the corresponding directories in EGSnrc/HEN_HOUSE. After doing this, open a new terminal session. Then you should be able to launch them from the command line, e.g. by typing `egs_gui`.

**Comment by rtownson** [comment]
Closing this, because it was minor and we haven't heard back.
