### ISSUE TITLE
Segmentation fault in pegsless mode when AE = UE

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#58]
In pegsless mode, a segmentation fault occurs if AE = UE.

See the simple input file below, which should be run with egs_chamber in pegsless mode.

[pegsless.txt](https://github.com/nrc-cnrc/EGSnrc/files/241191/pegsless.txt)

I know this is a weird edge case, but I figured there might be a better way to handle this than segfaulting. Maybe an error message and exiting?

**Comment by ftessier** [comment]
This one has your name on it @blakewalters!

**Comment by ftessier** [comment]
Fixed in c89f8ff
