### ISSUE TITLE
EGS_CONFIG issue

### ISSUE THREAD

**Issue by shankyR91** [nrc-cnrc/EGSnrc#581]
Respected all,

I am trying to install EGSnrc and i followed all the process for installation. But after installing i have facing some issues. Kindly check the issues and please give me the some feedback. 

" The environment variable  EGS_CONFIG is not set but it must be for the proper operation of EGSnrc and BEAMnrc."

Kindly give me the your important feedback.

**Comment by ojalaj** [comment]
Assuming you installing on Linux, have you strictly followed the steps in https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-Linux - especially the steps on setting the environment variables?

**Comment by shankyR91** [comment]
I have install on Window 10

**Comment by rtownson** [comment]
Run the windows EGSnrc installer GUI again, and this time check the checkbox 'set environment' before you click 'install'. That should solve the issue.

**Comment by rtownson** [comment]
This question has been asked on reddit, so I am closing the thread here to handle it over there.
