### ISSUE TITLE
Compilation error, DOSXYZnrc 

### ISSUE THREAD

**Issue by MrSlon** [nrc-cnrc/EGSnrc#590]
Hi everyone,

I installed EGS on Windows 10 (64 bit). Followed the installation instruction very closely. Made sure that all environmental variables are set correctly. Then tried to execute on of the example scripts, but got the following message:
![error](https://user-images.githubusercontent.com/62914849/79079295-e9c27380-7cd3-11ea-8a98-9ebe93e6997c.jpg)

It's complaining about  .obj files that ARE in place. The path to these files is set in environmental variables. Could you please suggest where the problem can stem from and how to fix it?

Thanks a lot!!!

**Comment by mainegra** [comment]
@MrSlon from the error messages it looks like the directory separator character is not being properly passed by make. Is this the first application you are trying to compile? Have others failed too?
In some instances the approach used to generate directory separators on Windows fails. It is not a common occurence but it has been reported on certain system which are managed by a system administrator implementing strict security measures.
The line defiining the directory separator is in the configuration file, which in your case seems to be _C:\EGSnrc\HEN_HOUSE\specs\Default.conf_ (pointed to by the _%EGS_CONFIG%_ environment variable). It should be:

`DSEP := $(subst /,\,/)`

Are you running on your system with Admin privileges? This should not be a requirement, but Iam just trying to figure out what is causing this to fail! On my Windows machine I am running as an administrator but only because I want to have full control.

An better alternative would be to install Windfows Subsystem for Linux (wsl) and work from bash.

**Comment by rtownson** [comment]
Could you post your installation log (found in HEN_HOUSE/log), and a screenshot of your environment variables? Even if things seem correct sometimes I can spot an issue in there.

**Comment by MrSlon** [comment]
Thank you so much for your replies, gentlemen!

The only file that I found in in HEN_HOUSE/log was 'config_win3264'
I hope this is the installation log required. There are 1500 lines of text, so I'm trying to attach the file as a whole. Hope, that works.
[config_win3264.log](https://github.com/nrc-cnrc/EGSnrc/files/4490606/config_win3264.log)

**Comment by MrSlon** [comment]
Here are the environmental variables (both system and user)

I'm probably running as administrator, which I'm not sure about. I'm using my personal laptop, and I'm the only user and admin of it.
![env var 1](https://user-images.githubusercontent.com/62914849/79526512-11467280-802b-11ea-98cb-e236ab401bd8.jpg)
![env var 2](https://user-images.githubusercontent.com/62914849/79526513-11df0900-802b-11ea-8585-307cb658c6bb.jpg)

**Comment by MrSlon** [comment]
Here is a path definition 
![path2](https://user-images.githubusercontent.com/62914849/79526554-27543300-802b-11ea-92b5-30ed509903f1.jpg)

**Comment by MrSlon** [comment]
I should let you know that I re-installed EGS, cause I thought, the configuration name 'Default' that I chose when installing the program might be causing those problems. Apparently, I was wrong. Because, now eve though I have installed it with the suggested config. name win6432, I'm still facing the same problem. So, the error now looks slightly different, but is essentially the same as before:  

![error](https://user-images.githubusercontent.com/62914849/79527281-c88fb900-802c-11ea-9b00-53df0df97525.jpg)

The directory in question is now called: 
C:\EGSnrc\HEN_HOUSE\lib\win3264

(instead of C:\EGSnrc\HEN_HOUSE\lib\default that it was before)

HOWEVER, this directory IS in the path among environmental variables, see above!

**Comment by MrSlon** [comment]
I did notice, too, that there were no slashes in the path to that folder, as reported in the error message. 
I checked the configuration file, as you suggested, and the line DSEP := $(subst /,\,/) is correct. It looks exactly the same!

So, I'm still wandering if it's:
1) a windows compatibility issue, or 
2) an error in the environmental variables. I'm still not 100% sure if all the path definitions are ok.
3) Or it's a version of mingw-32 compliler used. I'm pretty sure that, when installing, I picked up a right compiler version for my 64-bit Windows. I followed the installation guide very closely.

Your help is much appreciated!!

**Comment by MrSlon** [comment]
P.S. Actually, there ARE errors in the log file that I attached, just checked that. But I'm still not absolutely sure if they are related to installation, haven't figured that out yet.

P.P.S I did try other examples. Many of them failed, as well. In particular, very first sample application form the 'Getting started' manual returned with the following error: 

![error2](https://user-images.githubusercontent.com/62914849/79529420-38ed0900-8032-11ea-93c1-b04bca414bf0.jpg)

**Comment by rtownson** [comment]
One issue _might_ be the installation location of mingw. I know that we have seen some issues in the past due to installing mingw in a location with a space in the path (e.g. C:/Program Files/mingw-w64), because the mingw32-make utility is not good at handling spaces. I would try moving it elsewhere and updating your environment variables to reflect the move. Then run the EGSnrc installer again.

**Comment by MrSlon** [comment]
Rtownson thank you for your reply!
I tried what you suggested, but there's still the same error:

![error](https://user-images.githubusercontent.com/62914849/79608612-ef94cc00-80ba-11ea-859d-1f714c02ef82.jpg)

I wonder, there's so many underscores in file paths, even in core directories like this:
C:\EGSnrc\HEN_HOUSE\lib\win3264

Hen_House etc.

can this be an issue? Is there any way to overcome this in Windows?

**Comment by ojalaj** [comment]
Just to be sure - did you actually uninstall and re-install mingw to a location with no spaces, or move, as @rtownson wrote above?

**Comment by MrSlon** [comment]
@ojalaj   ,   yes! I did uninstall MinGW using this menu:

![screen](https://user-images.githubusercontent.com/62914849/79619663-2c6cbd00-80d3-11ea-98af-9943033cdb82.jpg)

to make sure that it gets removed completely.

Then I reinstalled it using path without dashes and underscores ( C:\Program Files\Mingw  ) but it's still not working and returning the sane error!

**Comment by MrSlon** [comment]
@rtownson, @ojalaj, @mainegra do you thinks there's a way to fix those issues and run the application under windows? 

Or is it better to try Linux, such as using a virtual machine?

**Comment by MrSlon** [comment]
One more thing! 

Is minGW compiler alone enough to handle the entire EGSnrc? Because, I did not install any other compilers, for C, C++ or Fortran. As I understood from the installation guide, just minGW should be ok.

**Comment by rtownson** [comment]
There is no issue with underscores or dashes, it's only spaces that cause a problem. So `C:\Program Files\Mingw` is not a good path, try something like `C:\Mingw` instead.

**Comment by MrSlon** [comment]
@rtownson I tried shorter path without spaces, but it still didn't work. 
However, I installed EGS on another computer, following your suggestions and it seems to work now. At least, it shows progress and generates .3ddose files for DOSXYZ, which is what I needed.
Thank you @rtownson, @mainegra, @ojalaj for your help!!

**Comment by rtownson** [comment]
Closing this issue since it was resolved by the user.
