### ISSUE TITLE
Phase Space Output Not Updating

### ISSUE THREAD

**Issue by danieldcecchi** [nrc-cnrc/EGSnrc#599]
While modifying egsinp files to have IAEA phase space outputs from a simulation run, it seems that setting the correct parameter for a particular integer (0, 1, 2) in the egsinp file does not visually change the format in the GUI (should be between `None`, `DOSXYZ Coordinates`, and `BEAMnrc Coordinates`).  While the code does return the correct IAEA phase space files, it does not show the user in the GUI that anything has changed.

**Comment by blakewalters** [comment]
@ftessier, this should also be addressed with https://github.com/nrc-cnrc/EGSnrc/pull/1171.
