### ISSUE TITLE
Old problem with relative path to libiaea_phsp.dylib on OSX

### ISSUE THREAD

**Issue by blakewalters** [nrc-cnrc/EGSnrc#6]
When running user codes that use IAEA phase space functionality on OSX, one obtains the message:
`dyld: Library not loaded: ../egs++/dso/darwin/libiaea_phsp.dylib`
This can be circumvented by actually creating directory `../egs++/dso/darwin/` and placing `libiaea_phsp.dylib` in it, but why is a relative path (..) being used in the first place?

**Comment by ftessier** [comment]
This issue should be fixed now that the egsnrc_bashrc_additions explicitly add the $HEN_HOUSE/egs++/dso/... path to the DYLD_LIBRARY_PATH environement variable in osx. Leaving the issue open until this is confirmed.

**Comment by pakoliver** [comment]
I'm not sure if this is the correct place to make this comment, but I needed to use this workaround for my EGSnrc installation on Mac OS Big Sur. My understanding is that on newer Mac OS versions, there's new feature called System Integrity Protection, which silently ignores the DYLD_LIBRARY_PATH environment variable (see here: https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html).

**Comment by ftessier** [comment]
Thanks @pakoliver for this update. Arghh, I understand Apple's will to buttress security, but it is making it hard on non-macos deverlopers. VirtualBox? 🙂
