### ISSUE TITLE
Pegsless mode cannot read density correction files when using material.dat file

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#60]
Density correction files fail to be read when using a `material.dat` file in pegsless mode. See the sample material and `egs_chamber` input files below. There is no problem when the material is directly defined in the input file, with or without a density correction file.

[material_short.txt](https://github.com/nrc-cnrc/EGSnrc/files/243150/material_short.txt)
[pegsless_material_file.txt](https://github.com/nrc-cnrc/EGSnrc/files/243151/pegsless_material_file.txt)

**Comment by ftessier** [comment]
Thank you for reporting this problem; @blakewalters can you check into this?

**Comment by blakewalters** [comment]
Hi Marc:

I think I found the source of this problem, but to make sure, could you go into your $HEN_HOUSE/src/get_media_inputs.mortran file and look for the code:

        IF(mindex>0 & eindex>mindex)[
         "remove everything up to ="
         text_string=text_string(eindex+1:);

Change this to:

        IF(mindex>0 & eindex>mindex)[
         "remove everything up to ="
         text_string=text_save(eindex+1:);

and recompile your code.  Does this fix the problem?

Blake

**Comment by mchamberland** [comment]
@blakewalters, yes this fixes the problem. Thanks!

**Comment by ftessier** [comment]
Fixed in c89f8ff
