### ISSUE TITLE
bug in sprrznrc output of D/Dmax vs radius

### ISSUE THREAD

**Issue by dworogers** [nrc-cnrc/EGSnrc#607]
In [sprrznrc.mortran  near line 4669](https://github.com/nrc-cnrc/EGSnrc/blob/7b994519a169b2e519da36f1fa4ed18bcf7ff054/HEN_HOUSE/user_codes/sprrznrc/sprrznrc.mortran#L4669-L4673):
```
   DO IX=1, NR [
       XCOORD(IX) = RCYL(IX);
       YCOORD(IZ) = SCDOSE(IZ,IX,3)/Dmax;
       UNCERT(IZ) = SCDOSE(IZ,IX,3)*SCDOSE2(IZ,IX,3)/(Dmax*100.);
    ]
```
should be 
```
   DO IX=1, NR [
       XCOORD(IX) = RCYL(IX);
       YCOORD(IX) = SCDOSE(IZ,IX,3)/Dmax;
       UNCERT(IX) = SCDOSE(IZ,IX,3)*SCDOSE2(IZ,IX,3)/(Dmax*100.);
    ]
```

**Comment by rtownson** [comment]
Yikes, thanks Dave!

**Comment by ftessier** [comment]
Thank you @dworogers! After reviewing the git "blame" view, this bug has been there at least since the port to git 5 years ago. Let me know if you need further forensics on this 😄
