### ISSUE TITLE
Duplicated Introduction section in egs++ apps descriptions

### ISSUE THREAD

**Issue by mainegra** [nrc-cnrc/EGSnrc#611]
The online egs++ manual PIRS-898 shows in the description/manuals of the C++ apps two Introduction sections in the list of contents. One link goes to the proper intro section while the other goes to the common_intro.

**Comment by mainegra** [comment]
@rtownson this issue has been fixed, right? All looks good on the egs++ manual page now!

**Comment by rtownson** [comment]
I can't find when it got fixed, but yes, looks good! I'll close this...
