### ISSUE TITLE
How can I calculate the absolute energy deposited for a parallel beam?

### ISSUE THREAD

**Issue by BINDX93** [nrc-cnrc/EGSnrc#629]
In page 29 of _Getting Started with EGSnrc_,  the absolute energy deposited in the geometry, _E_dep can be calculated for a collimated beam by:
<img width="609" alt="1" src="https://user-images.githubusercontent.com/53430658/91515106-f4944280-e91a-11ea-8429-cd81a291c04d.PNG">

And I would like to ask how can I calculate the absolute energy deposited in the geometry for a parallel beam?
Or how can I calculate the fluence when using a parallel beam?  
Because I don`t know how to transform _E_dep per fluence to _E_dep per particle for the parallel beam.

The input file is in the attachment.

Thanks a lot.

[test.egsinp.txt](https://github.com/nrc-cnrc/EGSnrc/files/5139758/test.egsinp.txt)

**Comment by BINDX93** [comment]
<img width="381" alt="2" src="https://user-images.githubusercontent.com/53430658/91530223-55cd0d80-e93d-11ea-88bc-288bbdbf236d.PNG">
For the parallel beam, what is the expression to calculate the fluence?

**Comment by ftessier** [comment]
I have answered [your question on reddit](https://www.reddit.com/r/EGSnrc/comments/ii6yeo/how_can_i_calculate_the_absolute_energy_deposited/): , which is the preferred venue for EGSnrc community support.
