### ISSUE TITLE
Print CI log on failure

### ISSUE THREAD

**Issue by mxxo** [nrc-cnrc/EGSnrc#639]
For PRs that fail CI, it would be very helpful to get the entire failure log.

I am in a position with #637 where it compiles locally but fails to build egs++ on CI https://travis-ci.com/github/nrc-cnrc/EGSnrc/builds/186712821

`Building the EGSnrc C++ class library ...         Failed`

**Comment by ftessier** [comment]
I agree with you @mxxo! The problem at hand is that these failures are bogus. I normally just restart the build and it passes (without ANY change!?). When I set up Travis a long time ago I think I had the configure.log dumped to the screen but turned it off since---normally---upon failure I would compile locally to flesh out the problem. Now that Travis fails for apparently a bogus reason, I will look it that again.

**Comment by ftessier** [comment]
I need to setup a better CI pipeline. Suggestions welcome! Up to now it has just been used to test compilation; I want to augment it with actual small test simulations to check that code and apps run, and perhaps give expected results (along the lines of the `egs_quality` project by @rtownson.

**Comment by mxxo** [comment]
I understand, thank you for letting me know. There is every possibly the issue is with #637, perhaps it's using a feature not supported by the CI compiler (C++14 things perhaps?). My idea for testing the `egs_mesh` PR was a `test` folder with a simple script essentially runs `./some_test && echo TEST PASSED || echo TEST FAILED`

**Comment by ftessier** [comment]
@mxxo The entire configuration logs are printed out at the end of the CI run, for inspection. This is available via the `Details` link, and then a link to open the job on Travis (but maybe this is only available for repo admins, I don't know):

![image](https://user-images.githubusercontent.com/1444241/115618745-1a62c300-a2c1-11eb-8df2-2ac8fb8815ed.png)

Now I presume the builds were failing to the parallel `-j12` option to `make`, which has now been removed in Release 2021 (see #649). At any rate, I see that your pull request #637 is now passing the Travis check, so I am closing this issue for now. Reopen it if needed, or let me know at any time if you want to see the travis log.
