### ISSUE TITLE
Issue with user code g

### ISSUE THREAD

**Issue by NoureenR** [nrc-cnrc/EGSnrc#641]
I am trying to execute g_template input file by using EGSnrc GUI, I am getting this error message:
At line 1022 of file g_win6432.f (unit = 9)
Fortran runtime error: Cannot open file '$HEN_HOUSE/spectra/co60.spectrum': No such file or directory

Another issue, in user code egs_kerma there is a data file emuen_icru90_1.5MeV, I am trying to regenerate this file by using g code. Can somebody please help with the input file for this.

I appreciate if somebody can help me with these issues.
Thanks

**Comment by mainegra** [comment]
@NoureenR I have answered [your question on reddit](https://www.reddit.com/r/EGSnrc/comments/j1c2hr/issue_with_user_code_g/) , which is the preferred venue for EGSnrc community support.

**Comment by NoureenR** [comment]
Thanks
