### ISSUE TITLE
EGSnrc installation issue on Mac OS Catalina 10.15.7

### ISSUE THREAD

**Issue by minghui1973** [nrc-cnrc/EGSnrc#642]
HI Gurus,

Kinda new on the EGSnrc on MacOS. I am trying to set up EGSnrc package on my macbook pro (MacOS Catalina 10.15.7). I followed the installation instruction here
https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-Linux

===========================
and installed prerequisites below 

~$gfortran --version
GNU Fortran (GCC) 10.2.0
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ make --version  
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

================================
using option1 to get a clone of EGSnrc

======================
Now when i try to configure the EGSnrc by running
$ ./HEN_HOUSE/scripts/configure

i got the following Error message...........

You can exit this script at any time by typing Ctrl-C.

Press enter to continue.

Checking system type ...                          i386-apple-darwin19.6.0
Checking for make ...                             yes (/usr/bin/make)

Looking for available fortran compilers ...       found: gfortran

Input fortran compiler:                           [gfortran] 
Testing if gfortran works ...                     yes. Object extension is 'o'
_**Testing if gfortran can create executables ...    no
error: this FORTRAN compiler can not create executables!**_

Can anyone help why?

thanks!

**Comment by rtownson** [comment]
I know of one other user who managed to install successfully on Catalina - you could try sending them a message. Please let us know if they followed any steps different from our instructions. See their reddit post here:
https://www.reddit.com/r/EGSnrc/comments/iy2ery/adding_statements_to_profile_on_macbook/

Also note that the MacOS installation instructions are slightly different than for linux, but it seems like you managed to install gfortran.. Here are the instructions for Sierra, which I imagine are the same.
https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS-Sierra

**Comment by hukui4860** [comment]
> I know of one other user who managed to install successfully on Catalina - you could try sending them a message. Please let us know if they followed any steps different from our instructions. See their reddit post here:
> https://www.reddit.com/r/EGSnrc/comments/iy2ery/adding_statements_to_profile_on_macbook/
> 
> Also note that the MacOS installation instructions are slightly different than for linux, but it seems like you managed to install gfortran.. Here are the instructions for Sierra, which I imagine are the same.
> https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS-Sierra

https://github.com/nrc-cnrc/EGSnrc/issues/644#issuecomment-715903595

**Comment by hukui4860** [comment]
> I know of one other user who managed to install successfully on Catalina - you could try sending them a message. Please let us know if they followed any steps different from our instructions. See their reddit post here:
> https://www.reddit.com/r/EGSnrc/comments/iy2ery/adding_statements_to_profile_on_macbook/
> 
> Also note that the MacOS installation instructions are slightly different than for linux, but it seems like you managed to install gfortran.. Here are the instructions for Sierra, which I imagine are the same.
> https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS-Sierra

https://github.com/nrc-cnrc/EGSnrc/issues/644#issuecomment-715903595
I am stuck during EGSnrc installation, I am looking forward to your help! 
Best regards!
[Compiling dosxyz_show ... Failed.pdf](https://github.com/nrc-cnrc/EGSnrc/files/5432833/Compiling.dosxyz_show.Failed.pdf)
[error in compiling egs_view.pdf](https://github.com/nrc-cnrc/EGSnrc/files/5432834/error.in.compiling.egs_view.pdf)

**Comment by hukui4860** [comment]
> I know of one other user who managed to install successfully on Catalina - you could try sending them a message. Please let us know if they followed any steps different from our instructions. See their reddit post here:
> https://www.reddit.com/r/EGSnrc/comments/iy2ery/adding_statements_to_profile_on_macbook/
> 
> Also note that the MacOS installation instructions are slightly different than for linux, but it seems like you managed to install gfortran.. Here are the instructions for Sierra, which I imagine are the same.
> https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS-Sierra

[issues during EGSnrc installation.docx](https://github.com/nrc-cnrc/EGSnrc/files/5432852/issues.during.EGSnrc.installation.docx)
I have two issues during EGSnrc installation, and this is the command on Mac OS Catalina 10.15.5 terminal, looking forward to your help!
Best regards!

**Comment by hukui4860** [comment]
> I know of one other user who managed to install successfully on Catalina - you could try sending them a message. Please let us know if they followed any steps different from our instructions. See their reddit post here:
> https://www.reddit.com/r/EGSnrc/comments/iy2ery/adding_statements_to_profile_on_macbook/
> 
> Also note that the MacOS installation instructions are slightly different than for linux, but it seems like you managed to install gfortran.. Here are the instructions for Sierra, which I imagine are the same.
> https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS-Sierra

I moved file "egs_config1.h" to "/Users/caiqian890307/Downloads/EGSnrc/HEN_HOUSE/egs++/view", then qmake and make egs_view, there is another error:
ld: library not found for -legspp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../../bin/egs_view.app/Contents/MacOS/egs_view] Error 1
I have tried the wiki(https://github.com/nrc-cnrc/EGSnrc/wiki/Build-static-GUIs-on-macOS), but I failed to figure out the commands. Of course, I still can't find out the problem.

**Comment by rtownson** [comment]
Did you end up solving this issue? Have you set the QTDIR environment variable?

**Comment by ftessier** [comment]
Migrated to #704.

**Comment by ftessier** [comment]
Please consult the updated [macOS installation instructions](https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS), which are known to work on macOS 11 (Big Sur), and report any outstanding or further issue in #704.
