### ISSUE TITLE
EGSnrc installation issue during compiling egs_view on mac os catalina 10.15.5:

### ISSUE THREAD

**Issue by hukui4860** [nrc-cnrc/EGSnrc#644]
I installed EGSnrc following the wiki, and there are two issue.
The first one is:
Compiling dosxyz_show ... Failed
I compiled egs_gui and egs_inprz successfully, the second one occurred during compiling egs_view:
Compiling dosxyz_show ... Failed.pdf
Uploading Compiling dosxyz_show ... Failed.pdf…

In file included from main.cpp:43:
In file included from ./viewcontrol.h:36:
In file included from .ui/ui_viewcontrol.h:70:
In file included from ../egs_vector.h:41:
In file included from ../egs_functions.h:35:
../egs_libconfig.h:54:10: fatal error: 'egs_config1.h' file not found
#include "egs_config1.h"
^~~~~~~~~~~~~~~
1 error generated.
make: *** [.obj/main.o] Error 1
error in compiling egs_view.pdf
[error in compiling egs_view.pdf](https://github.com/nrc-cnrc/EGSnrc/files/5434102/error.in.compiling.egs_view.pdf)

There are two files named "egs_config1.h"
/Users/caiqian890307/Downloads/EGSnrc/HEN_HOUSE/pieces/egs_config1.h /Users/caiqian890307/Downloads/EGSnrc/HEN_HOUSE/lib/osx/egs_config1.h
And I diff -q these two file named "egs_config1.h", of course, the result is differ.

I know of one other user who managed to install successfully on Catalina - you could try sending them a message. Please let us know if they followed any steps different from our instructions. See their reddit post here:
https://www.reddit.com/r/EGSnrc/comments/iy2ery/adding_statements_to_profile_on_macbook/

Also note that the MacOS installation instructions are slightly different than for linux, but it seems like you managed to install gfortran.. Here are the instructions for Sierra, which I imagine are the same.
https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS-Sierra

_Originally posted by @rtownson in https://github.com/nrc-cnrc/EGSnrc/issues/642#issuecomment-704456500_

**Comment by hukui4860** [comment]
I installed EGSnrc following  the wiki, and there are two issue. 
The first one is:
Compiling dosxyz_show ... Failed
I compiled egs_gui and egs_inprz successfully, the second one occurred during compiling egs_view:
[Compiling dosxyz_show ... Failed.pdf](https://github.com/nrc-cnrc/EGSnrc/files/5432827/Compiling.dosxyz_show.Failed.pdf)
[Uploading Compiling dosxyz_show ... Failed.pdf…]()


In file included from main.cpp:43:
In file included from ./viewcontrol.h:36:
In file included from .ui/ui_viewcontrol.h:70:
In file included from ../egs_vector.h:41:
In file included from ../egs_functions.h:35:
../egs_libconfig.h:54:10: fatal error: 'egs_config1.h' file not found
#include "egs_config1.h"
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [.obj/main.o] Error 1
[error in compiling egs_view.pdf](https://github.com/nrc-cnrc/EGSnrc/files/5432817/error.in.compiling.egs_view.pdf)

**Comment by hukui4860** [comment]
I moved file "egs_config1.h" to "/Users/caiqian890307/Downloads/EGSnrc/HEN_HOUSE/egs++/view", then qmake and make egs_view, there is another error:
ld: library not found for -legspp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../../bin/egs_view.app/Contents/MacOS/egs_view] Error 1
I have tried the wiki(https://github.com/nrc-cnrc/EGSnrc/wiki/Build-static-GUIs-on-macOS), but I failed to figure out the action. Of course, I still can't find out the problem.

**Comment by rtownson** [comment]
Did you solve this issue? Have you set the QTDIR environment variable? It should point to the directory that contains bin/qmake (i.e. the path in QTDIR doesn't include /bin at the end).

**Comment by ftessier** [comment]
Migrated to #704.

**Comment by ftessier** [comment]
Please consult the updated [macOS installation instructions](https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS), which are known to work on macOS 11 (Big Sur), and report any outstanding or further issue in #704.

**Comment by Mariag-hub** [comment]
Hi! I'm having the same issue here but I can't find the solution in the new macOS installation guide (which I followed).
I'm at the step of run the 'make' command in egs_view directory and the error is
```
../egs_libconfig.h:54:10: fatal error: 'egs_config1.h' file not found
#include "egs_config1.h"
         ^~~~~~~~~~~~~~~
1 error generated.
```
What should I do now? I successfully compiled egs_gui and egs_inprz with 'make'
