### ISSUE TITLE
fails to parallel build with Intel compilers => probably incorrect Make-dependencies between object-files

### ISSUE THREAD

**Issue by SiebertChris** [nrc-cnrc/EGSnrc#649]
I tried to build the newest EGSnrc using Intel compilers but unfortunately it fails.

EGSnrc source is from 2nd of December 2020 - tried both .zip-archive and git clone.
Intel compilers are newest (i.e., icc, ifort and icpc 19.1.2.254).

Building comes until 
```
Building the EGSnrc C++ class library ...         Failed
```

In configure.log the error is
```
../../dso/linux/egs_nd_geometry.o: file not recognized: File truncated
```

The actual problem seems to be the parallel build with incorrect Make-dependencies between object-files.
Workaround: replacing line 145 in scripts/configure `-j12` by `-j1` (i.e., disabling parallel build)
=> works with this workaround, but doesn't fix the actual problem.

BTW. the (parallel) build interestingly works with GCC-compilers.

**Comment by ftessier** [comment]
Thanks @SiebertChris for reporting this issue. WE mostly use `gcc` and don't regularly test with intel compilers. You are right, I will add dependencies between make rules to ensure that parallel make completes in the correct order. It is interesting indeed that `gcc` works, but in my experience in rare occasions is does trip as well (in which case I just remake), so in fact with `gcc` it work _most of the time_.

**Comment by ftessier** [comment]
Turns out this also explains why our Travis CI builds fail on occasion, so thanks again for pointing this out!

**Comment by SiebertChris** [comment]
I'm glad I could help.

**Comment by MartinMartinov** [comment]
To add this with some very recent experiences, @ftessier.  I'm trying to compile a version of EGSnrc with custom source libraries that depend on geometry libraries, and when I compile with the default configure script (with -j12 flag), all the source libraries get built before the geometry libraries I need and my custom source build fails.  If I use -j1 in configure instead, the build works no problem.

I was thinking that potentially adding an input flag in configure to choose the number of cores wouldn't be too hard and would help when building either more intricately dependent libraries or using more unique compilers.

**Comment by ftessier** [comment]
Incidentally, I have also been trying to include an external class (provided as EGSnrc-independent `.h` and `.cpp` files) and integrate them in the app `Makefile` build, and it is not obvious. We could revert the default to `-j1` as a stop gap, but since anyone could use `-j*` (say in a `make` alias), we really ought to clean up the build dependencies and facilitate the inclusion of independent code. I find the EGSnrc build convoluted, but I am not sure immediately how to improve it. Suggestions welcome!

**Comment by MartinMartinov** [comment]
Unfortunately, I think I'm in the same boat.  I've only learned enough about GNU makefiles to get by, and am just removing the -j12 flag for now.  I'll keep an eye out for a more elegant solution, though.

**Comment by ftessier** [comment]
The `-j12` flag for `make` has been removed in Release 2021, specifically in commit b08afa94d5ca11a421ea9873f17a1359f4025412.
