### ISSUE TITLE
Mac OS Big Sur configuration Error

### ISSUE THREAD

**Issue by finjoetri** [nrc-cnrc/EGSnrc#671]
I ran  `./HEN_HOUSE/scripts/configure` in Mac and I got following error:
```
Checking system type ...                          sed: 1: ":/:_:g": unused label '/:_:g'
i386-apple-darwin20.3.0
Checking for make ...                             yes (/usr/local/bin/gmake)

Looking for available fortran compilers ...       found: gfortran

Input fortran compiler:                           [gfortran]  
Testing if gfortran works ...                     no
Error: your FORTRAN compiler failed to compile a simple test program
```

**Comment by ftessier** [comment]
I can confirm this issue. At my end it occurs because of a library version mismatch for `libquadmath`. Working on a solution!

**Comment by ftessier** [comment]
My error occurs at a different point in the configuration. @finjoetri can you share your configuration log file `HEN_HOUSE/scripts/configure.log`?

**Comment by ftessier** [comment]
Migrated to #704.

**Comment by finjoetri** [comment]
> Oh, my error occurs later in the configuration, so it is probably not related. @finjoetri can you share your configuration log file `HEN_HOUSE/scripts/configure.log`?

Currently, I used Ubuntu to run EGSnrc, it worked and reinstalled the Big Sur wiping the whole system, so currently I don't have the file `HEN_HOUSE/scripts/configure.log`

**Comment by ftessier** [comment]
Please consult the updated [macOS installation instructions](https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS), which are known to work on macOS 11 (Big Sur), and report any outstanding or further issue in #704.
