### ISSUE TITLE
[Feature Request] egs-parallel settings file of some kind

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#678]
> Yes, that's a good idea. I won't change it for this merge, but will give it some thought for sure! I would prefer to gather all user settings in as few places as possible. Perhaps these egs-parallel defaults could go in `$EGS_CONFIG` (and even adjust the configuration script to define them when configuring EGSnrc)?

_Originally posted by @ftessier in https://github.com/nrc-cnrc/EGSnrc/pull/628#discussion_r601597149_

This is to track a feature that came up in discussions re the new egs-parallel  submission system. It would be nice if the default values were definable globally per user, so the user doesn't have to remember their flags.

**Comment by ftessier** [comment]
On the other hand, maybe it is better if users learn the flags 😆

**Comment by ftessier** [comment]
I am moving this to the new Discussions tab, so as to keep Issues for actionable bugs.
