### ISSUE TITLE
EGS_XYZGeometry documentation: x/y/z-planes vs. x/y/z-slabs?

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#681]
In https://nrc-cnrc.github.io/EGSnrc/doc/pirs898/classEGS__XYZGeometry.html it suggests that:

The other new possibility to define a XYZ geometry is

```
:start geometry:
    library = egs_ndgeometry
    type = EGS_XYZGeometry
    x-slabs = Xo  Dx  Nx
    y-slabs = Yo  Dy  Ny
    z-slabs = Zo  Dz  Nz
:stop geometry:
```

which should be self explanatory.

However, in a simple simulation, using above with x/y/z-slabs resulted in very long simulation times (e.g. 44-fold) compared to x/y/z-planes, as in other examples. Why is this happening and which one is right or both?

**Comment by ftessier** [comment]
Hi @ojalaj, that is indeed quite strange. Are you sure that your two inputs define the same geometry? Can you share a small sample input that reproduces the problem?

**Comment by ftessier** [comment]
As far as I can tell the implementation is essentially the same, except for the constructor variant:
```c++
new EGS_PlanesX(xslab[0],xslab[1],nx,"",EGS_XProjector("x-planes"))   // for x-slabs
new EGS_PlanesX(xpos,"",EGS_XProjector("x-planes")                    // for x-planes
```

**Comment by ftessier** [comment]
Implementation of the slab constructor seems fine to me:
```c++
    EGS_PlanesT(EGS_Float xo, EGS_Float dx, int np, const string &Name,
                const T &A) : EGS_BaseGeometry(Name), a(A) {
        if (np < 1) egsFatal("...",np);
        if (dx <= 0) egsFatal("...",dx);
        p = new EGS_Float [np+1];
        p[0] = xo;
        for (int j=0; j<np; j++) {
            p[j+1] = p[j] + dx;
        }
        nreg = np;
        p_last = p[nreg];
        n_plane = np;
        is_uniform = true;
        dp = dx;
    };
```
If you have a simple example input on hand, I will take a look at it.

**Comment by ftessier** [comment]
Note by self-explanatory, what the author meant was "`Xo` is the position of the first x plane, `Dx` is the uniform slab thickness, and `Nx` is the number of slabs". Perhaps you interpreted "self-explanatory" differently? 😉

**Comment by ojalaj** [comment]
Hi @ftessier ! Actually, the reason is that! Sorry about this - I got confused with the notations :(

**Comment by ojalaj** [comment]
@ftessier I'm have not reached your level of "self-explanatory" :D

**Comment by ftessier** [comment]
I will expand the "self-explanatory" in the doc right away. Coincidentally you are the second person this week to trip on this notation. It is beyond me why anyone would write "self-explanatory" in documentation, rather than spell it out...

**Comment by ftessier** [comment]
Let me know if this is clearer:

> where along the x axis `Xo` is the position of the minimum boundary of the geometry, `Dx` is the uniform slab thickness, and `Nx` is the number of slabs (similarly for the y and z axes). The number of regions along x is `Nx` and the maximum x boundary is thus `Xo + Nx*Dx`.

**Comment by ojalaj** [comment]
Yes - this is now "self-explanatory"^2 :D
