### ISSUE TITLE
Unknown float option 'r' when compiling PIRS-701

### ISSUE THREAD

**Issue by lichuanlong** [nrc-cnrc/EGSnrc#70]
When compiling `pirs701-egsnrc.tex`, there is an error on [line 2009](https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/new_um_app2.tex#L2009):

```
./inputs/new_um_app2.tex:2009: LaTeX Error: Unknown float option `r'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
...                                                                                                 
l.2009 \begin{figure}[hrbt]
```

**Comment by rtownson** [comment]
I could not reproduce, using `pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013)`.

**Comment by lichuanlong** [comment]
> ~/EGSnrc/HEN_HOUSE/doc/src$ ./makedoc.sh pirs701-egsnrc/
> + cd pirs701-egsnrc
> + pdflatex -interaction=nonstopmode pirs701-egsnrc.tex
> + pdflatex -interaction=nonstopmode pirs701-egsnrc.tex
> + bibtex pirs701-egsnrc
> + makeindex pirs701-egsnrc.idx
> + pdflatex pirs701-egsnrc.tex
> 

when compile dir pirs701-egsnrc, it will stop here.
makedoc.sh script uses pdflatex, not pdfTex
