### ISSUE TITLE
Missing graceful error message in addphsp

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#724]
When adding egsphsp using addphsp, if the number of particles crosses the ~56 GiB barrier, with the number of particles exceeding a 32-bit int, addphsp fails with an exception. 

```#bash
At line 1078 of file addphsp_linux.f (unit = 3, file = 'noCollApr22_2.5cm.egsphsp1')
Fortran runtime error: Record number must be positive
```

[BeamNRC running in single thread mode handles this gracefully](https://www.reddit.com/r/EGSnrc/comments/cxq5kj/ask_phsp_file_error_while_writing/)

Proposed solution: addphsp should check the total number of particles that will be created at each additional phase space addition, stopping and reporting a graceful error. 

ie, if there are 40 egsphsp files, and the addition of the 37th one would cross the threshhold, then addphsp would stop at 36, and report as such to the user.

**Comment by ftessier** [comment]
Better yet, use a long int for the record number? And, of course, rewrite addphsp in python 😄

**Comment by ftessier** [comment]
@crcrewso can you send me the few lines around line 1078 in **your** `addphsp_linux.f` please?

**Comment by crcrewso** [comment]
> @crcrewso Better yet, use a long int for the record number?

That would be great, but can we do that? It's not going to break backwards compatibility? 

> @crcrewso can you send me the few lines around line 1078 in **your** `addphsp_linux.f` please?

Line:
```#fortran
              WRITE(3,REC=WRITE_PHSP_SOFAR(1)/TEMP_PHSP_COUNTER+1) STRIN
     *        G_TEMP_OUT(1) (28*(WRITE_PHSP_COUNTER(1)-NUM_PHSP_TOFLUSH)
     *        +1: 28*(WRITE_PHSP_COUNTER(1)-NUM_PHSP_TOFLUSH+TEMP_PHSP_C
     *        OUNTER))
```

Context:
```#fortran
1991      CONTINUE
            TEMP_PHSP_COUNTER=NUM_PHSP_TOFLUSH+1
2001        CONTINUE
              TEMP_PHSP_COUNTER=TEMP_PHSP_COUNTER-1
              REM_PHSP=MOD(WRITE_PHSP_SOFAR(1),TEMP_PHSP_COUNTER)
              IF(((REM_PHSP.EQ.0)))GO TO2002
            GO TO 2001
2002        CONTINUE
            CLOSE(3)
            IF ((IZLAST1.NE.0)) THEN
              PHSP_RECL=4*8*TEMP_PHSP_COUNTER
              OPEN(UNIT=3,FILE=OUTFILE,RECL=PHSP_RECL, ACCESS='DIRECT',F
     *        ORM='UNFORMATTED',STATUS='UNKNOWN')
              WRITE(3,REC=WRITE_PHSP_SOFAR(1)/TEMP_PHSP_COUNTER+1) STRIN
     *        G_TEMP_ZLAST_OUT(1) (32*(WRITE_PHSP_COUNTER(1)-NUM_PHSP_TO
     *        FLUSH)+1: 32*(WRITE_PHSP_COUNTER(1)-NUM_PHSP_TOFLUSH+TEMP_
     *        PHSP_COUNTER))
            ELSE
              PHSP_RECL=4*7*TEMP_PHSP_COUNTER
              OPEN(UNIT=3,FILE=OUTFILE,RECL=PHSP_RECL, ACCESS='DIRECT',F
     *        ORM='UNFORMATTED',STATUS='UNKNOWN')
              WRITE(3,REC=WRITE_PHSP_SOFAR(1)/TEMP_PHSP_COUNTER+1) STRIN
     *        G_TEMP_OUT(1) (28*(WRITE_PHSP_COUNTER(1)-NUM_PHSP_TOFLUSH)
     *        +1: 28*(WRITE_PHSP_COUNTER(1)-NUM_PHSP_TOFLUSH+TEMP_PHSP_C
     *        OUNTER))
            END IF
            WRITE_PHSP_SOFAR(1)=WRITE_PHSP_SOFAR(1)+TEMP_PHSP_COUNTER
            NUM_PHSP_TOFLUSH=NUM_PHSP_TOFLUSH-TEMP_PHSP_COUNTER
            IF(((NUM_PHSP_TOFLUSH.EQ.0)))GO TO1992
          GO TO 1991
1992
```

**Comment by blakewalters** [comment]
@crcrewso, @ftessier: I don't think this is an issue anymore with:
https://github.com/nrc-cnrc/EGSnrc/pull/729
That fix should stop adding (with a message) if the next phase space file added will take the total no. of particles over the 2^32-1 limit.  Let me know if you find otherwise.
