### ISSUE TITLE
Incorrect geometry for exit phase space

### ISSUE THREAD

**Issue by TonyPopescu** [nrc-cnrc/EGSnrc#749]
Hi Frederic, Blake, Reid and Ernesto,

In dosxyznrc.mortran (https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran), there is a missing equation just before line 3730 ("Write the particle to a phsp"). The code should include the following:

"to assign the correct z coordinate for a IAEA exit phase space"
		         IF(i_iaea_in=1)[
			             z(np) = z(np) + SAD_s20;
		         ]

 This was included in the Source 20 code submitted originally by JL and TP, but is now not present in the code. Without the above equation, the coordinates of the exit phase space (in BEAMnrc coordinates) would be incorrect. We did not notice this problem until now, because we have been using our own code version. 

For example, consider a phantom of 20 x 20 x 40 cm^3 with the centre at the linac isocentre. In the IAEAheader for the exit phase space, we should see the following coordinate ranges in BEAMnrc coordinates:

$STATISTICAL_INFORMATION_GEOMETRY:
 -10  10
 -10  10
 80  120

which is indeed the case with the above equation included. However, in its absence, as the current code stands, we would get the incorrect situation:

$STATISTICAL_INFORMATION_GEOMETRY:
 -10  10
 -10  10
 -20  20

Regards,
-Tony Popescu

**Comment by rtownson** [comment]
Thanks Tony! Hopefully @blakewalters can take a look soon, since I think he worked on this.

**Comment by TonyPopescu** [comment]
Great! Thanks, Reid.
Cheers,
-Tony
