### ISSUE TITLE
Error of Shared Object libBEAM_EX16MVp.so When Running Dosxyznrc Examples

### ISSUE THREAD

**Issue by phresher** [nrc-cnrc/EGSnrc#752]
Description
========

The error occured when running dosxyznrc examples via `ex dosxyznrc` command as follows or dosxyznrc GUI. 

```bash
cd $EGS_HOME/dosxyznrc
cp example/*.egsinp .
ex dosxyznrc 16MVp_h2o_phantom_beamsource_example.egsinp 700icru
```

The whole log is attached.

[dosxyznrc.log](https://github.com/nrc-cnrc/EGSnrc/files/6848687/dosxyznrc.log)

The excerpt is as follows:

```txt
================================================================================
EGSnrc version 4 for x86_64-unknown-linux-gnu          Tue Jul 20 21:17:49 2021
================================================================================
configuration...............................linux
user code...................................dosxyznrc
pegs file...................................700icru on HEN_HOUSE
using host..................................DESKTOP-LOUUQAH
input file..................................16MVp_h2o_phantom_beamsource_example
output file(s)..............................16MVp_h2o_phantom_beamsource_example
================================================================================

 Begin execution with large arrays being zeroed
 Thisis only needed for Linux g77 compiler - comment
 this code near the top of dosxyznrc.mortran if you are
 not using a linux g77 compiler
...
Failed to open library /home/phresher/EGSnrc/egs_home/bin/linux/libBEAM_EX16MVp.so
Error was: /home/phresher/EGSnrc/egs_home/bin/linux/libBEAM_EX16MVp.so: cannot open shared object file: No such file or directory
...
You have to load and initialize the library first
```

**In short, a shared library was failed to compile.** 

Possible Reason
==========

It's likely due to compatibility issues because my colleague success somehow on Windows 10 with .exe GUI installer while I failed with the same method.

Environment
========

The EGSnrc toolkit was compiled following the official instruction strictly via the command line procedure. The logs are attached as follows. 

[configure-linux.log](https://github.com/nrc-cnrc/EGSnrc/files/6848663/configure-linux.log)
[configure-linux-phresher.log](https://github.com/nrc-cnrc/EGSnrc/files/6848664/configure-linux-phresher.log)

**We tried RHEL 7, Windows exe configure tool and WSL Ubuntu 20.04. The issue could be reproduced.** 

The building tools' version are shown below

```
$ gfortran --version
GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

The version of EGSnrc is v2021.

**We look forward to your reply and request for a list of compatible building tools.**

Thanks in advance!

**Comment by rtownson** [comment]
Thanks for the detailed report! I believe this is because you have not compile the BEAMnrc accelerator that this example is referencing as a shared library source (I think this example needs better instructions). Go to the accelerator it is using as a source, i.e. `egs_home/BEAM_EX16MVp` and compile the accelerator as a shared library with `make library`. Then try running this example again.

**Comment by ROOTRT** [comment]
When I reading input files (with .egsinp suffix) in /root/EGSnrc/EGS_HOME via dosxyznrc GUI, the error occurs: can't read "options(25,1)":no such element in array.
![image](https://user-images.githubusercontent.com/87711551/126353286-830c3f03-3535-4be4-9f20-5e3e845db135.png)
I got confused and hope your help. Thanks!

**Comment by rtownson** [comment]
@ROOTRT can you post this as a new question, under discussions? This is unrelated to the other user's issue. Please also post your input file.

**Comment by ROOTRT** [comment]
@rtownson I'm sorry for doing that.  @phresher helps me solve problems, so I post my issue here. I'll do that thank you!

**Comment by phresher** [comment]
> Thanks for the detailed report! I believe this is because you have not compile the BEAMnrc accelerator that this example is referencing as a shared library source (I think this example needs better instructions). Go to the accelerator it is using as a source, i.e. `egs_home/BEAM_EX16MVp` and compile the accelerator as a shared library with `make library`. Then try running this example again.

Thanks so much, my life saver!
