### ISSUE TITLE
EGSnrc-configure-windows.exe only works if in c:\EGSNRC\

### ISSUE THREAD

**Issue by Jaap1957** [nrc-cnrc/EGSnrc#818]
The installation instructions suggest to download the configure-windows.exe .

I would like to stress this exe has to be downloaded to
c:\EGSNRC\configure-windows.exe

otherwise, it seems to work, but in the end does not do its job.

Please add this to 
[https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-Windows#3-configure-egsnrc](url)

after the sentence 
" Download the EGSnrc-configure-windows.exe executable from the latest release on the release page  "

**Comment by rtownson** [comment]
What part fails, specifically? I believe I usually run it from the downloads directory without issue.

**Comment by Jaap1957** [comment]
You are right (of course)

At the start of the install i made a folder to put everything in.
Like gfortran.exe which i found somewhere in the Octave distribution.
When starting the exe from that folder i got this error:


[cid:32ee07d5-a070-4262-ac5b-703f7e80982e]


After removing this gfortran.exe version i had no error.




________________________________

**Comment by rtownson** [comment]
Ok, I'm glad you found source of the problem! I don't think we need to do anything about this, so I'll close this issue.
