### ISSUE TITLE
Unnecessary warning when lowest energy input for density correction is equal to AE

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#82]
This is just a minor inconvenience. When the lowest energy input for the density effect is exactly equal to AE, a warning is output saying that it is higher:

 *_**LOWEST ENERGY INPUT FOR DENSITY EFFECT IS 5.120E-01
                   WHICH IS HIGHER THAN THE VALUE OF AE= 5.120E-01 MEV
 *__IT HAS BEEN SET TO AE_**

It would be nicer to only output a warning if the lowest energy input is strictly lower than AE (and silently allow lowest energy input == AE).

**Comment by rtownson** [comment]
I believe this is now fixed in the master branch.
