### ISSUE TITLE
Bug in CD geometry's howfar

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#83]
[Line 525](https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/egs%2B%2B/geometry/egs_cd_geometry/egs_cd_geometry.h#L525) in egs_cd_geometry.h should read:

`
ibase_n = bg->howfar(ibase_n,xtmp,u,tb,pmednew,pn);
`

because the next line uses `ibase_n` to check if we're entering the base geometry or not. This resolves a subset of long-standing CD geometry errors.

**Comment by ftessier** [comment]
Nice catch @mchamberland, this might just be it! On a related note, in the same code section @mainegra, why is the hard-coded 1e-4 cm considered small enough? Seems large for micron size simulations... Why not 1e-8 cm? If an atomic size fuzz is a problem, then the algorithm is not appropriate anyways.

**Comment by mainegra** [comment]
@ftessier hard-coded values like this one can be found all over the geometry library. This is why I proposed using a general epsilon that could be set for all geometries and remove all the hard-coded limits. One could then allow users to re-define the default value for epsilon depending on their world's dimensions. BTW such an epsilon is already in place in the base geometry class. It is just not used. I suggest we come up with a default value (1e-10 m) and implement a way to allow users redefining it via input.

**Comment by ftessier** [comment]
Good idea! Indeed we ought to clean this up. Let's open the general epsilon approach as a separate issue (enhancement).

**Comment by mchamberland** [comment]
Just an FYI, in case you forgot (and because I've been delving into those issues lately): the egs_stack_geometry already implements a `tolerance` input. You may want to harmonize it with the rest once you have the general epsilon implemented.

Also: I've got two more improvements / fixes to CD geometry to propose, but I'll need your feedback to make sure my fixes are appropriate. Should I just open a pull request and we can review and discuss the code on the pull request page?

**Comment by ftessier** [comment]
Yes, please open pull requests (or add it to your previous one if your improvements are related). We will have little time until mid-June, but it is best to open issues and requests before we forget!
