### ISSUE TITLE
Use a default epsilon to check for geometrical round-off errors

### ISSUE THREAD

**Issue by mainegra** [nrc-cnrc/EGSnrc#86]
- Use a default epsilon and remove all the hard-coded limits. 
- Allow users to re-define the default value for epsilon depending on their world's dimensions. 
- Set default value to 1e-10 m.

**Comment by mchamberland** [comment]
I have a proposal: make the epsilon variable non-static, so that users can set epsilon on a per geometry basis, similar to the `tolerance` input from `EGS_StackGeomery`.

**Comment by mchamberland** [comment]
I don't know if anyone has been working on this, but just for fun, I gave it a shot. I may have open a pull request on it once I test it out a little.
