### ISSUE TITLE
choose 1 or 2 can't compile user code when configure.

### ISSUE THREAD

**Issue by lichuanlong** [nrc-cnrc/EGSnrc#88]
> You may now compile user codes. Please select:
>     1. Compile all
>     2. Compile selected
>     3. Compile none (default)
> 
> Choose 1 (all), 2 (some) or 3 (none):             [3] 

when configure, choose 1 or 2 compile failed.

> Choose 1 (all), 2 (some) or 3 (none):             [3] 1
>     Compiling cavity ...                          failed
>     Compiling cavrznrc ...                        failed
>     Compiling cavsphnrc ...                       failed
>     Compiling dosrznrc ...                        failed
>     Compiling dosxyznrc ...                       failed
>     Compiling edknrc ...                          failed
>     Compiling egs_cbct ...                        failed
>     Compiling egs_chamber ...                     failed
>     Compiling egs_fac ...                         failed
>     Compiling examin ...                          failed
>     Compiling flurznrc ...                        failed
>     Compiling g ...                               failed
>     Compiling ranlux_test ...                     failed
>     Compiling ranmar_test ...                     failed
>     Compiling sprrznrc ...                        failed
>     Compiling tutor1 ...                          failed
>     Compiling tutor2 ...                          failed
>     Compiling tutor2pp ...                        failed
>     Compiling tutor3 ...                          failed
>     Compiling tutor4 ...                          failed
>     Compiling tutor5 ...                          failed
>     Compiling tutor6 ...                          failed
>     Compiling tutor7 ...                          failed
>     Compiling tutor7pp ...                        failed
>

**Comment by rtownson** [comment]
Can you provide more information? Did you follow the steps on the installation instructions?

https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-Linux

**Comment by ftessier** [comment]
It seems that you don't have compilers installed, or they are not in your path. You can look inside the configuration log files in `$HEN_HOUSE/logs` for more details on the problem, or else go inside one application directory, say `$EGS_HOME/examin` and issue the `make` command to see why it fails.

**Comment by lichuanlong** [comment]
In configure-linux-lcl.log there are the logs.
and i have compile edknrc in $EGS_HOME/edknrc and run it. but in ./configure choose 1 , all usercode compile failed.

> ###############################################################################
> EGSnrc configuration for the user lcl
> Generated by finalize_egs_foruser version 1.0 Aug 25 2015
> ###############################################################################
> 
> EGS_HOME:                                         /home/lcl/EGSnrc/egs_home/
> EGS_CONFIGURAION:                                 /home/lcl/EGSnrc/HEN_HOUSE/specs/linux.conf
> HEN_HOUSE:                                        /home/lcl/EGSnrc/HEN_HOUSE/
> OMEGA_HOME:                                       /home/lcl/EGSnrc/HEN_HOUSE/omega
> 
> Compilation selection: 1
> Compilation list:  cavity cavrznrc cavsphnrc dosrznrc dosxyznrc edknrc egs_cbct egs_chamber egs_fac examin flurznrc g ranlux_test ranmar_test sprrznrc tutor1 tutor2 tutor2pp tutor3 tutor4 tutor5 tutor6 tutor7 tutor7pp
> *************** Compiling cavity ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling cavrznrc ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling cavsphnrc ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling dosrznrc ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling dosxyznrc ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling edknrc ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling egs_cbct ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling egs_chamber ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling egs_fac ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling examin ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling flurznrc ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling g ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling ranlux_test ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling ranmar_test ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling sprrznrc ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor1 ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor2 ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor2pp ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor3 ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor4 ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor5 ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor6 ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor7 ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed
> *************** Compiling tutor7pp ****************** 
> /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: 1: /home/lcl/EGSnrc/HEN_HOUSE//scripts/compile_user_code: Syntax error: Unterminated quoted string
> failed

**Comment by lichuanlong** [comment]
I find it.
in ubuntu sh link to dash not bash. default shell is not bash.

so compile_user_code the first line #!/bin/sh change to #!/bin/bash
may fix it.
