### ISSUE TITLE
can't find qmake

### ISSUE THREAD

**Issue by lichuanlong** [nrc-cnrc/EGSnrc#89]
```
lcl@ThinkPad:~/EGSnrc/HEN_HOUSE/gui$ ls
egs_configure  egs_gui  egs_inprz  gui.pro  Makefile
lcl@ThinkPad:~/EGSnrc/HEN_HOUSE/gui$ make
/bin/qmake my_machine=linux MAKEFILE=Makefile_linux QMAKE=/bin/qmake
make: /bin/qmake: Command not found
make: *** [Makefile_linux] Error 127
```

In ubuntu 14.04 maybe `qmake` is `/usr/lib/x86_64-linux-gnu/qt4/bin/qmake` or `/usr/lib/x86_64-linux-gnu/qt5/bin/qmake` but EGSnrc can't find it.

**Comment by rtownson** [comment]
In ~/.bashrc try setting an environment variable $QTDIR, then start a new terminal.

For example:
export QTDIR=/usr/lib/x86_64-linux-gnu/qt4

**Comment by lichuanlong** [comment]
I have made a symbol link in /bin/ name qmake linking my qt4 qmake.
But I think it is not a fine way to fix it, because it is automatic.
In my opinion EGS should find it by itself.
So I post it here.
