### ISSUE TITLE
'WARNING in +ve/-ve bar of SYNCJAWS' & 'Please contact the NRC'

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#90]
In a parallel BEAMnrc simulation with `ISOURC=21` incident on the top of geometry starting with SLABS (0.2 cm), then SYNCJAWS (checked that parameters in sequence file not overlapping with CMs above of below, with air gaps ~1 cm and ~0.5 cm, respectively) and then another SLABS (0.1 cm) and other CMs, I get hundreds of negative usteps with following warning:

```
*****************
 ***WARNING in +ve (or -ve) bar of SYNCJAWS
 Particle is well above or below jaw, yet region number
 indicates theparticle is still in the jaw.
 The particle is being discardedbut this is a bug.
 Please contact the NRC.
*****************
```

Well, now I'm contacting NRC. The same simulation with smaller number of particle histories in interactive mode runs fine, so there shouldn't be any (major) problems in the input file.

**Comment by blakewalters** [comment]
Hi Jarkko:

Any chance you could attach the .egsinp file that's causing this warning.

Thanks!

**Comment by ojalaj** [comment]
Hi! Did you get my email?

**Comment by ojalaj** [comment]
Hi! Did you get my email?

**Comment by ojalaj** [comment]
I've sent you example files.

**Comment by rtownson** [comment]
Fixed in release-2017.
