### ISSUE TITLE
Compilation fails with -mcmodel=medium on macOS

### ISSUE THREAD

**Issue by ftessier** [nrc-cnrc/EGSnrc#904]
In #725 the compiler option `-mcmodel=medium` was added to the default flags, but this causes compilation failures on macOS (testing on version 11.6.7). On macOS, the `clang` linker is used, which apparently fails to link with code compiled with `-mcmodel=medium`. Specifically, out of the box on branch `develop` with the default options we get the following failures:

```
Compiling statdose ...                            Failed
...
Building the IAEA phase space library ...         Failed
Building the EGSnrc C++ class library ...         Failed
```

(I have no clue why `statdose` fails!). Hence, this compilation flag should **not** be set on macOS. Removing the `-mcmodel=medium` compiler option solves the problem.

**Comment by blakewalters** [comment]
@ftessier, have you tried compiling a shared library on Mac?  I'm using gfortran-8 and I'm running into errors with the flags "-Wl,-Bsymbolic." I get the error: "ld: unknown option: -Bsymbolic."  This goes away if I eliminate the "-Wl" flag and the shared library apparently compiles successfully (I haven't actually tried running it, though).  What do these flags do?  Does "-W" define a warning level?

**Comment by crcrewso** [comment]
Finally read this one 

I wonder, does -mcmodel=large also fail?
