### ISSUE TITLE
BEAMnrc mesh CM geometry error

### ISSUE THREAD

**Issue by CQUswl** [nrc-cnrc/EGSnrc#925]
When I run beamnrc on Windows, the used mesh module component shows 'can not get here'，what does that mean?
![图片](https://user-images.githubusercontent.com/114200268/191877744-ab040a28-ed2f-4d1f-ab66-8c307be6d44e.png)

**Comment by rtownson** [comment]
This usually means that the geometry is not well defined, like there is some dimension that doesn't make sense. Double check with the documentation, and if you're still stuck you are welcome to post the (non-proprietary) input here.

**Comment by CQUswl** [comment]
> This usually means that the geometry is not well defined, like there is some dimension that doesn't make sense. Double check with the documentation, and if you're still stuck you are welcome to post the (non-proprietary) input here.

Thanks！I compiled and ran this .egsinp input file using the beamnrc GUI, sometimes this error appears, sometimes it does not.
![图片](https://user-images.githubusercontent.com/114200268/192074131-80b33e36-ff9d-4a73-a902-5311468520af.png)
![图片](https://user-images.githubusercontent.com/114200268/192074145-2765dbf9-f1ee-4a09-9f7c-684850635df6.png)
![图片](https://user-images.githubusercontent.com/114200268/192074169-e01e351a-e470-4fd3-8648-054d341aa204.png)

**Comment by mxxo** [comment]
Hi @CQUswl,

Could you post your egsinp as text in the comment body or upload the files themselves? It's much easier to start debugging if you don't have to manually transcribe code from an image (and there's no chance of making transcription mistakes).

**Comment by CQUswl** [comment]
> Hi @CQUswl,
> 
> Could you post your egsinp as text in the comment body or upload the files themselves? It's much easier to start debugging if you don't have to manually transcribe code from an image (and there's no chance of making transcription mistakes).

Thanks，this is the egsinp file.
sandwich1                                                                        #!GUI1.0
AIR521ICRU
0, 0, 0, 0, 0, 2, 0,  IWATCH ETC.
1000000000, 33, 97, 99, 0, 0, 0, 0,  NCASE ETC.
0, 21, 1, -1, 0, 0, 0, 0, 0, 0,  IQIN, ISOURCE + OPTIONS
C:/EGSnrc/egs_home/BEAM_Sandwich/BEAM_Sandwich.egsphsp1
0, 0, 0.521, 0.01, 0, 0, 0,  0 , ECUT,PCUT,IREJCT,ESAVE
0, 0, 0, 0, 0,  PHOTON FORCING
3, 1, 2, 3,  SCORING INPUT
1, 1
1, 
1, 1
1, 
1, 1
1, 
0,  DOSE COMPONENTS
0.0, Z TO FRONT FACE
*********** start of CM SLABS with identifier air  ***********
1, RMAX
air
1, NSLABS
0, ZMIN
10, 0, 0, 0, 2, 0
AIR521ICRU
*********** start of CM SLABS with identifier filter  ***********
1, RMAX
filter
1, NSLABS
10, ZMIN
0.1, 0, 0, 0, 3, 0
CU521ICRU
*********** start of CM MESH with identifier sandwich  ***********
1, RMAX
sandwich
10.1, MESH
0.005, 0.5, 0.005, 5, , AIR AND WIRE WIDTHS
0.4975, 0.255, XTOTAL, YTOTAL
0.521, 0.01, 0, 3, 
0.521, 0.01, 0, 4, 
PB521ICRU
*********************end of all CMs*****************************
 #########################
 :Start MC Transport Parameter:
 
 Global ECUT= 0.521
 Global PCUT= 0.01
 Global SMAX= 5
 ESTEPE= 0.25
 XIMAX= 0.5
 Boundary crossing algorithm= EXACT
 Skin depth for BCA= 0
 Electron-step algorithm= PRESTA-II
 Spin effects= On
 Brems angular sampling= KM
 Brems cross sections= BH
 Bound Compton scattering= Norej
 Compton cross sections= default
 Pair angular sampling= Simple
 Pair cross sections= BH
 Photoelectron angular sampling= On
 Rayleigh scattering= On
 Atomic relaxations= EADL
 Electron impact ionization= Off
 Photon cross sections= xcom
 Photon cross-sections output= Off
 
 :Stop MC Transport Parameter:
 #########################

**Comment by rtownson** [comment]
I don't see any issues with the input file. If you only spot a few of these errors over millions of histories, the effect will be completely negligible. I believe it is a floating point error that is not properly handled, where a particle will appear to be in one region when it is in fact in a different one within a very small distance.

**Comment by CQUswl** [comment]
Thank you so much for your help, I understand.

**Comment by CQUswl** [comment]
> I don't see any issues with the input file. If you only spot a few of these errors over millions of histories, the effect will be completely negligible. I believe it is a floating point error that is not properly handled, where a particle will appear to be in one region when it is in fact in a different one within a very small distance.

How do I turn off Compton scattering while running beamnrc gui?
