### ISSUE TITLE
Two MLCE CMs in the same BEAMnrc linac fail to compile

### ISSUE THREAD

**Issue by rtownson** [nrc-cnrc/EGSnrc#928]
Two MLCE CMs in the same BEAMnrc linac fail to compile. We had a similar issue with the SYNC CMs that was fixed previously, I believe it was due to a few variables not including the CM number in their variable name. For now, the workaround is just to use SYNCMLCE instead.

Reported here, thanks /u/center2506:
https://www.reddit.com/r/EGSnrc/comments/xs5b3j/compilation_error/

**Comment by ftessier** [comment]
Fixed with pull request #931
