### ISSUE TITLE
error when compiling DOSXYZnrc 

### ISSUE THREAD

**Issue by YapingQi** [nrc-cnrc/EGSnrc#937]
Hi guys, 

I change some parameters in dosxyznrc user macros.mortran and recompiling with "make"  in folder /egs_home/dosxyznrc/, and I got the errors like following :
/usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
/root/es/EGSnrc/HEN_HOUSE/makefiles/standard_makefile:87: recipe for target '/root/es/EGSnrc/egs_home/bin/linux/dosxyznrc' failed

the make fortran option is okay.

Can anyone know how to fix this?

**Comment by rtownson** [comment]
Try changing the parameters back, and then go one at a time to see which one results in the failure. I'm guessing this is due to changing the maximum number of voxels. You might need to adjust compiler flags, see here:

https://www.reddit.com/r/EGSnrc/comments/gzy2de/statedose_voxel_limitation/

**Comment by rtownson** [comment]
Did you resolve this issue?

**Comment by YapingQi** [comment]
Yes, I did. I changed the maximum number of voxels and it worked. Thank you!
