### ISSUE TITLE
Typo in egs_chamber exapmle2

### ISSUE THREAD

**Issue by wkt84** [nrc-cnrc/EGSnrc#945]
The input file of egs_chamber example seems to have tiny typos.

https://github.com/nrc-cnrc/EGSnrc/blob/a6fc389c6465c949645380976f38a013a639759c/HEN_HOUSE/user_codes/egs_chamber/example2_chamber_dd.egsinp#L302

```
x-planes = -30  30
y-planes = -30 30
```

This means  60x60cm^2, not 30x30 cm^2, right?
The same is true for the water region.

I'll send out a PR if you're willing to revise it.

**Comment by rtownson** [comment]
Thanks for noticing this, I'll fix it, I was planning to go through these examples anyway.
