### ISSUE TITLE
Photonuclear attenuation magnified with cross section enhancement

### ISSUE THREAD

**Issue by ftessier** [nrc-cnrc/EGSnrc#956]
### Description

- The photonuclear cross section is magnified when the cross section enhancement (`xcse`) variance reduction technique is turned on, biasing calculated quantities.

### Expected behavior

- `xcse` is a true variance reduction technique, hence it should not alter calculated quantities.

### Impact

- The bug arises when `xcse` is used while `Photonuclear attenuation = On`, and scales with the enhancement factor.
- The most severe bias occurs when the relative photonuclear cross section is largest, as shown further down.
- It affects the following EGSnrc applications: `cavrznrc`, `cavsphnrc`, `dosrznrc`, and `egs_chamber`.
- It was introduced when photonuclear attenuation was added to EGSnrc, around 2012.

### Root cause

- There are no `ausgab` calls for `BeforePhotoNuc` (`PHOTONUCAUSB`) nor `AfterPhotoNuc` (`PHOTONUCAUSA`) events in application that implement cross section enhancement. When `xcse` is turned, the total photon cross section is increased by the enhancement factor. However, there is no compensation for this biasing in the `ausgab` routine, for the photonuclear interaction (only).

### Examples

- The dose to the air cavity of a Farmer ionization chamber surrounded by a tungsten buildup cap is **decreased** by about 2% for a bremsstralung beam emitted by 15 MeV electrons striking an aluminum target, and an `xcse` factor of 32 inside the tungsten cap. The discrepancy scales with the `xcse` factor. This is how this bug was initially revealed.

- A more contrived example, although by no means far-fetched, is the dose to an air cavity inside a spherical shell of PMMA, 1 cm thick, irradiated by a uniform monoenergectic beam of 23 MeV photons, as depicted below. When `xcse` is turned on (enhancement of 1024), the dose is reduced by ~40% ([input file](https://github.com/nrc-cnrc/EGSnrc/files/10583168/photonuclear-xcse-bug.egsinp.txt) for `egs_chamber`):

  |                      | `xcse` factor | Dose per incident fluence |
  | :------------------- | :------------ | :------------------------ |
  | `cs enhancement = 0` | —             | `9.6485e-12 +/- 0.09%`    |
  | `cs enhancement = 1` | 1024          | `5.5757e-12 +/- 0.33%`    |

  ![image](https://user-images.githubusercontent.com/1444241/216739726-45ecc8b1-0e84-43a8-8980-24f6ca5fdb56.png)

  Relative photonuclear cross section for a few common materials, for reference:
  
![photonuc-small](https://user-images.githubusercontent.com/1444241/216712817-be9741fa-f172-493e-9022-cbf0ecff1817.png)

**Comment by mainegra** [comment]
Wow @ftessier ! This is quite an effect! Good catch!

**Comment by ojalaj** [comment]
@ftessier Dumb question: To my knowledge `xcse` feature is not used/available in `beamnrc`/`cavrznrc`/`cavsphnrc`/`dosrznrc` so how it can affect their results? Or with those applications, do you mean `BCSE ` or any such feature? Is `dosxyznrc` affected? And if e.g. with beamnrc `BCSE` is not used, there is no problem even if `Photonuclear attenuation = On`?

**Comment by ftessier** [comment]
Hi @ojalaj! Support for `xcse` was [added in `beamnrc` in 2005](https://github.com/nrc-cnrc/EGSnrc/blob/a6fc389c6465c949645380976f38a013a639759c/HEN_HOUSE/omega/beamnrc/beamnrc.mortran#L13674-L13709), but the option is not available in the gui (but it can be added in the input file), as far as I can tell. So by and large there is no issue if you have not entered `CSE IN CMS` in the input file. It is turned off by default. There is no issue with `bcse`. The `dosxyznrc` application is not affected. See #958 to see what files are affected and how.

**Comment by ojalaj** [comment]
Thanks @ftessier for confirmation (& sorry for dumb questions)!
