### ISSUE TITLE
EGSnrc library not found on macOS: /usr/lib/libSystem.B.dylib

### ISSUE THREAD

**Issue by ftessier** [nrc-cnrc/EGSnrc#964]
### Discussed in https://github.com/nrc-cnrc/EGSnrc/discussions/963

<div type='discussions-op-text'>

<sup>Originally posted by **hbouchard** February 15, 2023</sup>
When _running_ EGSnrc application on macOS, there is _dynamic library not loaded_ error for `/usr/lib/libSystem.B.dylib`.

We experience this issue on **MacBook Pros M1** 8GB RAM (Monterey and Ventura) when changing `$MAXRADII` from `4` to `16` in flurznrc. It compiles fine, but attempting to run yields the following error:

```
dyld[18643]: dyld cache '(null)' not loaded: syscall to map cache into shared region failed
dyld[18643]: Library not loaded: /usr/lib/libSystem.B.dylib
  Referenced from: <C4F425D6-E281-31CB-9A2B-2FB3103A1A67> /Users/hbouchard/EGSnrc/egs_home/bin/osx/flurznrc
  Reason: tried: '/Users/hbouchard/EGSnrc/HEN_HOUSE/egs++/dso/osx/libSystem.B.dylib' (no such file), '/Users/hbouchard/EGSnrc/HEN_HOUSE/egs++/dso/osx/libSystem.B.dylib' (no such file), '/libSystem.B.dylib' (no such file), '/usr/lib/libSystem.B.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/libSystem.B.dylib' (no such file), '/usr/lib/libSystem.B.dylib' (no such file, no dyld cache), '/usr/local/lib/libSystem.B.dylib' (no such file)
Abort trap: 6 
```

There is a post [complaining about this issue](https://developer.apple.com/forums/thread/722360), without apparent solution.

This problem doesn't occur on an iMac Intel i7 16GB RAM.
</div>

**Comment by ftessier** [comment]
See also https://developer.apple.com/forums/thread/655588

**Comment by mchamberland** [comment]
This issue is reproducible on an M2 MacBook Air, macOS Ventura 13.2, 24 GB of RAM.

**Comment by mchamberland** [comment]
[This seems to be related](https://developer.apple.com/forums/thread/697494), i.e., it involves static arrays, as this case does.

**Comment by mchamberland** [comment]
[Does this explain the issue? ](https://developer.apple.com/forums/thread/676684)The executable is not >2GB, but perhaps the static arrays are that large? So when loaded in memory, they extend into the address range where the shared cache lives. This is definitely way outside my comfort zone, but it sounds plausible.

**Comment by ftessier** [comment]
Yes, that is the issue, thanks for the instructive reference. In the mortran codes, most variables are global and on the stack (!). These large arrays should be created on the heap obviously. I will close this issue, because we will not implement head allocation before we rewrite EGSnrc!
